# AUTO-GENERATED by Meta/emit_export_headers_bazel.py --libweb — do not edit.
# LibWeb's generate_export_header output. It lives here rather than in the
# root package because Libraries/LibWeb is its own Bazel package, so only
# this package may declare an output inside it.
load("@rules_cc//cc:defs.bzl", "cc_library")

def libweb_export_header():
    native.genrule(
        name = 'gen_LibWeb_Export_h',
        outs = ['genroot/LibWeb/Export.h'],
        cmd = "cat > $@ <<'LADYBIRD_EOF'\n\n#ifndef WEB_API_H\n#define WEB_API_H\n\n#ifdef LIBWEB_STATIC_DEFINE\n#  define WEB_API\n#  define LIBWEB_NO_EXPORT\n#else\n#  ifndef WEB_API\n#    ifdef LibWeb_EXPORTS\n        /* We are building this library */\n#      define WEB_API __attribute__((visibility(\"default\")))\n#    else\n        /* We are using this library */\n#      define WEB_API __attribute__((visibility(\"default\")))\n#    endif\n#  endif\n\n#  ifndef LIBWEB_NO_EXPORT\n#    define LIBWEB_NO_EXPORT __attribute__((visibility(\"hidden\")))\n#  endif\n#endif\n\n#ifndef LIBWEB_DEPRECATED\n#  define LIBWEB_DEPRECATED __attribute__ ((__deprecated__))\n#endif\n\n#ifndef LIBWEB_DEPRECATED_EXPORT\n#  define LIBWEB_DEPRECATED_EXPORT WEB_API LIBWEB_DEPRECATED\n#endif\n\n#ifndef LIBWEB_DEPRECATED_NO_EXPORT\n#  define LIBWEB_DEPRECATED_NO_EXPORT LIBWEB_NO_EXPORT LIBWEB_DEPRECATED\n#endif\n\n/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */\n#if 0 /* DEFINE_NO_DEPRECATED */\n#  ifndef LIBWEB_NO_DEPRECATED\n#    define LIBWEB_NO_DEPRECATED\n#  endif\n#endif\n\n#endif /* WEB_API_H */\nLADYBIRD_EOF\n",
    )
    cc_library(
        name = 'generated_export_header',
        hdrs = ['genroot/LibWeb/Export.h'],
        includes = ['genroot'],
    )
