#!/usr/bin/env python3
"""Emit the Bazel rules that make Bazel own fetching every Rust crate.

Ring 2, part 2 — the last one. Finding 33 closed vcpkg; this closes Rust, which
was the only reason a `git clone && bazel build //:ladybird` still needed a CMake
build first (10 production crates were consumed as a prebuilt 260 MB
`librust_combined.a` out of `Build/full/cargo/`, and `flapc` was the reference
build's binary).

The shape mirrors emit_vcpkg_bazel.py deliberately — a foreign build system owns
a recipe we do not want to reimplement, so Bazel takes fetching/hashing/
sandboxing and cargo stays the recipe. One thing is *better* here, and it is
worth naming because it is the difference between the two problems:

  **There is nothing to capture.** vcpkg needed an instrumented run
  (Meta/vcpkg_capture_assets.sh) because portfiles are CMake *programs* that
  compute their URLs at run time. `Cargo.lock` is a *manifest*: it carries a
  sha256 `checksum` for every registry crate, and crates.io's download URL is a
  pure function of (name, version). So this emitter needs no cargo, no network,
  no CMake — the lock file IS the pin, and `--check` proves it round-trips.

What it emits (one pass over the lock files, selected by flag):

  cargo_crates.bzl      one http_archive per registry crate (`.crate` is a
                        .tar.gz), sha256 straight out of Cargo.lock.
  cargo_index.bzl       the crate -> label index + CARGO_CRATE_SPECS, the
                        per-crate build recipe (features, FFI headers, manifest).
  cargo_extension.bzl   the module extension that creates those repos.
  cargo_ring.bzl        the 10 cargo_crate targets + flapc + the link group,
                        as a macro the ROOT package instantiates (the crate
                        sources live at the repo root, and glob() is
                        package-relative).
  --use-repo            the `use_repo(...)` block MODULE.bazel needs.

Three things here are load-bearing, and each was measured rather than reasoned:

  * **Features are per crate and come from CMake, not from a guess.** The spec
    for this work said `libgfx_rust` is built `--features allocator`; at the
    commit this overlay targets it is NOT (cargo fails outright: "the package
    'libgfx_rust' does not contain this feature"). The features live in
    `import_rust_crate(... FEATURES ...)` in `Libraries/*/CMakeLists.txt`, behind
    a `if (NOT BUILD_SHARED_LIBS)` for three of them, so this parses the CMake
    and reports what it found. Getting them wrong changes the ABI silently —
    the finding-23 lesson.
  * **The FFI header list is not derivable from the crate name, and CMake's own
    list is INCOMPLETE.** `libweb_rust`'s `import_rust_crate` declares one header
    (`HTML/Parser/RustFFI.h`), but its build script writes *two*: it depends on
    `libweb_html_tokenizer`, whose build script emits
    `HTMLTokenizerRustFFI.h` into the same `$FFI_OUTPUT_DIR` — and three LibWeb
    TUs include it. CMake never notices because it declares outputs it does not
    enumerate; Bazel deletes undeclared outputs. So the header list is the union
    of CMake's declaration and the observed set, and the observed set wins where
    they differ (see FFI_HEADERS_OBSERVED).
  * **The registry/workspace split is the whole reason this is cheap.** 155 of
    the 166 `[[package]]` entries have a checksum; the other 11 are the in-tree
    workspace members, which have no checksum because they are *sources*. A
    crate with no checksum must never become a fetch rule (it would 404), and a
    registry crate that silently drops out is a build failure a long way from its
    cause — so both halves are counted and reported.

Usage:
  emit_cargo_bazel.py --crates    > cargo_crates.bzl
  emit_cargo_bazel.py --index     > cargo_index.bzl
  emit_cargo_bazel.py --extension > cargo_extension.bzl
  emit_cargo_bazel.py --ring      > cargo_ring.bzl
  emit_cargo_bazel.py --use-repo            # paste into MODULE.bazel
  emit_cargo_bazel.py --report              # what resolved, and what did not
  emit_cargo_bazel.py --check <dir>         # regenerate and byte-compare
"""
import os
import re
import sys

try:
    import tomllib
except ImportError:  # py<3.11
    tomllib = None

ROOT = os.environ.get(
    "LADYBIRD_ROOT", os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

HEADER = "# AUTO-GENERATED by Meta/emit_cargo_bazel.py — do not edit.\n"

# The two cargo workspaces. Flap is `exclude`d from the root workspace and has
# its own lock with exactly 3 packages (flapc, in-tree bytecode_def, and
# smallvec from crates.io), so it needs the same treatment at 1/50th the size.
LOCKS = ["Cargo.lock", "Libraries/LibJS/Flap/Cargo.lock"]

# The host triple cargo builds for. Not a guess: `rustc -vV`'s `host:` line is
# what CMake reads (Meta/CMake/rust_crate.cmake), and it names the directory the
# archive lands in. Hard-coded because the rest of this overlay is x86_64-linux
# only (the .bazelrc has -march=native and a k8 output path).
TRIPLE = "x86_64-unknown-linux-gnu"

# The toolchain pin, from rust-toolchain.toml. Read, never assumed: a crate built
# by "whatever rustc is on PATH" is not a pinned build.
TOOLCHAIN_COMPONENTS = ["rustc", "cargo", "rust-std"]


def _toml(path):
    with open(path, "rb") as f:
        if tomllib is not None:
            return tomllib.load(f)
    raise RuntimeError("python 3.11+ (tomllib) required to read %s" % path)


def toolchain_channel():
    """The pinned channel from rust-toolchain.toml (e.g. "1.96.1")."""
    return _toml(os.path.join(ROOT, "rust-toolchain.toml"))["toolchain"]["channel"]


def root_workspace_members():
    """The root cargo workspace's member directories, read from Cargo.toml.

    Which workspace a crate belongs to decides its SOURCE SET, and it is the one
    thing here that must not be guessed. `Libraries/LibWasm/Rust` is member #7 of
    the root workspace, so cargo resolves the whole workspace when asked for it
    and its input set is the shared `crate_srcs`; `Libraries/LibJS/Flap` is in
    `exclude` and has its own lock, so its input set is its own subtree. Reading
    the member list means adding a crate to either workspace needs no edit here.
    """
    ws = _toml(os.path.join(ROOT, "Cargo.toml"))["workspace"]
    return {os.path.normpath(m) for m in ws.get("members", [])}


# ---------------------------------------------------------------------------
# The lock files.
# ---------------------------------------------------------------------------
def lock_packages(rel):
    """[(name, version, checksum-or-None)] for one Cargo.lock, in lock order."""
    d = _toml(os.path.join(ROOT, rel))
    return [(p["name"], p["version"], p.get("checksum"))
            for p in d.get("package", [])]


def split_packages(pkgs):
    """(registry, workspace) — the ones with a checksum, and the ones without.

    The distinction is not cosmetic: a `[[package]]` with no `checksum` is an
    in-tree path dependency (a workspace member), i.e. a *source* Bazel already
    has. Emitting a fetch rule for it would build a URL for a crate that does
    not exist on crates.io. Emitting nothing for a registry crate is worse: the
    offline build fails with "no matching package" far from the missing rule.
    """
    registry = [(n, v, c) for (n, v, c) in pkgs if c]
    workspace = [(n, v) for (n, v, c) in pkgs if not c]
    return registry, workspace


def all_registry_crates():
    """{(name, version): sha256} across every lock file.

    Merged rather than kept per-workspace because a crate shared by both locks
    (smallvec 1.15.1, pinned `=1.15.1` by flapc) is ONE fetch: same name, same
    version, and — checked here rather than assumed — the same checksum. If the
    two locks ever disagreed on a shared crate's hash, one repo name would have
    to serve two contents, which is the silent-wrong-content bug vcpkg's
    hash-suffixed repo names exist to prevent. So it is a hard error.
    """
    out = {}
    for rel in LOCKS:
        registry, _ = split_packages(lock_packages(rel))
        for name, version, checksum in registry:
            key = (name, version)
            if key in out and out[key] != checksum:
                raise SystemExit(
                    "error: %s-%s has two different checksums across lock files "
                    "(%s vs %s)" % (name, version, out[key], checksum))
            out[key] = checksum
    return out


def crate_url(name, version):
    """The crates.io download URL. A pure function of (name, version).

    This is the whole reason no capture is needed: vcpkg's URLs are computed by a
    CMake program, crates.io's are computed by this one line.
    """
    return "https://static.crates.io/crates/%s/%s-%s.crate" % (name, name, version)


def repo_name(name, version):
    """A Bazel repo name per crate-version.

    (name, version) is already unique in a lock file, so unlike the vcpkg case
    there is no hash needed to disambiguate — but `-` and `.` are not legal in a
    repo name, so both are normalized.
    """
    return "crate_%s_%s" % (name.replace("-", "_"),
                            re.sub(r"[^A-Za-z0-9]", "_", version))


# ---------------------------------------------------------------------------
# The build recipe, parsed out of CMake.
# ---------------------------------------------------------------------------
# The FFI headers each crate's build script ACTUALLY writes into
# $FFI_OUTPUT_DIR, observed by running the reference cargo build with
# FFI_OUTPUT_DIR pointed at an empty directory per crate and listing it.
#
# This exists because CMake's own declaration is incomplete, in a way CMake
# cannot notice and Bazel cannot tolerate: `import_rust_crate(... libweb_rust
# FFI_HEADERS HTML/Parser/RustFFI.h)` names one header, but the crate depends on
# libweb_html_tokenizer, whose build script writes HTMLTokenizerRustFFI.h into
# the same FFI_OUTPUT_DIR. Three LibWeb TUs include <LibWeb/HTMLTokenizerRustFFI.h>.
# Under CMake the file is simply there (nothing declares or deletes it); under
# Bazel an undeclared output is deleted, and the include fails with a
# file-not-found a long way from its cause.
#
# So: CMake's list is the *claim*, this is the *measurement*, and --report
# compares them. Keyed by crate, paths relative to FFI_OUTPUT_DIR.
FFI_HEADERS_OBSERVED = {
    "libgfx_rust": ["RustFFI.h"],
    "libjs_rust": ["RustFFI.h"],
    "libregex_rust": ["RustFFI.h"],
    "libtextcodec_rust": ["RustFFI.h"],
    "liburl_rust": ["RustFFI.h"],
    "libunicode_rust": ["RustFFI.h"],
    # Upstream consolidated libweb_css_rust and libweb_layout_rust BACK into
    # libweb_rust, so this one crate now writes what three used to -- eleven
    # files of its own plus HTMLTokenizerRustFFI.h from its path-dependency
    # libweb_html_tokenizer, which lands in the same FFI_OUTPUT_DIR. Two of them
    # are .inc, not .h: an undeclared .inc is deleted by Bazel exactly like an
    # undeclared header, and it is #included the same way.
    "libweb_rust": ["ComputedValuesRustFFI.h", "HTML/Parser/RustFFI.h",
                    "HTMLTokenizerRustFFI.h", "Layout/LayoutRustFFI.h",
                    "Layout/TreeBuilderRustFFI.h", "RustFFI.h",
                    "SelectorRustFFI.h", "StyleEngineBridgeGenerated.h",
                    "StyleEngineBridgeGenerated.inc", "StyleEngineRustFFI.h",
                    "StyleEngineStateFactsGenerated.inc", "StyleValueRustFFI.h"],
    "libweb_content_blocker_rust": ["ContentBlockerRustFFI.h"],
    # A BINARY crate that also emits a header -- see BINARY_CMAKELISTS below.
    "libwasm_cranelift": ["CraneliftFFI.h"],
}

# Where each crate's headers are included FROM. CMake sets FFI_OUTPUT_DIR to the
# consuming library's CMAKE_CURRENT_BINARY_DIR (Build/full/Libraries/LibX), and
# the build's -IBuild/full/Libraries makes <LibX/RustFFI.h> resolve. We reproduce
# the same include spelling by staging each crate's headers under
# <prefix>/ and adding the parent as an include dir.
FFI_PREFIX = {
    "libgfx_rust": "LibGfx",
    "libjs_rust": "LibJS",
    "libregex_rust": "LibRegex",
    "libtextcodec_rust": "LibTextCodec",
    "liburl_rust": "LibURL",
    "libunicode_rust": "LibUnicode",
    "libweb_rust": "LibWeb",
    "libweb_content_blocker_rust": "LibWeb",
    "libwasm_cranelift": "LibWasm",
}

# The non-Rust files each crate's build script reads, taken from the DEPFILES the
# reference cargo build wrote (`--emit=dep-info`), not from reading the build
# scripts. That is the same instrument-don't-predict tactic as the vcpkg capture,
# and it matters for the same reason: libweb_css_rust's build.rs *generates Rust*
# from eight CSS data files, and a build that does not declare them silently
# keeps a stale archive when Properties.json changes. Reading build.rs would have
# found most of these; the depfile finds all of them, including the ones reached
# through a `manifest_dir.parent()` join.
CRATE_EXTRA_INPUTS = {
    # libjs_rust's build script derives its instruction types from the Flap
    # interpreter (upstream a32d9c9f: `include_str!("../../Interpreter/
    # interpreter.flap")` via flapc::metadata), so the .flap file is a compile
    # input reached by a `manifest_dir.parent()` join -- exactly the shape the
    # depfile finds and reading build.rs nearly misses. It replaced
    # Libraries/LibJS/Bytecode/Bytecode.def, which that commit DELETED.
    "libjs_rust": ["Libraries/LibJS/Interpreter/interpreter.flap"],
    # libwasm_cranelift's build.rs reads `manifest_dir.join("../Opcode.h")` and
    # generates a Rust constant per `M(name, value, ...)` line, so the WASM
    # opcode table is a compile input to the cranelift compiler binary.
    "libwasm_cranelift": ["Libraries/LibWasm/Opcode.h"],
    # The LibWeb ones are NOT here: they are inside the Libraries/LibWeb package,
    # so they ride in that package's rust_crate_srcs filegroup instead --
    # PACKAGE_EXTRA_INPUTS below. Same measurement, different side of a package
    # boundary.
}

# The same measurement for the files that live inside ANOTHER Bazel package, so
# the root package cannot glob them: libweb_rust's build script generates Rust
# from the CSS data files and reads the HTML name headers + Entities.json. Kept
# here rather than in emit_libweb_bazel.py so ONE place holds the measurement and
# ONE --report checks it against the reference build's depfiles.
PACKAGE_EXTRA_INPUTS = {
    "Libraries/LibWeb": [
        "CSS/Enums.json",
        "CSS/Keywords.json",
        "CSS/LogicalPropertyGroups.json",
        "CSS/Properties.json",
        "CSS/PseudoClasses.json",
        "CSS/PseudoElementPropertyGroups.txt",
        "CSS/PseudoElements.json",
        "CSS/TransformFunctions.json",
        "CSS/Units.json",
        "HTML/AttributeNames.h",
        "HTML/Parser/Entities.json",
        "HTML/TagNames.h",
    ],
}

# The crate source trees. A crate depends on more than its own directory: every
# one of them `#[path = "../../../RustAllocator.rs"]`s the shared allocator shim,
# and several are path-dependencies of each other (libweb_rust ->
# libweb_html_tokenizer, liburl_rust -> libregex_rust, libjs_rust -> flapc),
# which cargo resolves through the workspace. So the source set is "all the
# in-tree crates plus the shim", declared once. Over-declaring costs a rebuild of
# every crate when any .rs changes; under-declaring silently reuses a stale
# archive. For a first landing that trade is the right way round, and it is
# honest debt to name (todo 6f39dd58).
#
# DERIVED from Cargo.toml's member list and the manifests' `path =`
# dependencies, never written down -- because a directory written down here is a
# glob that outlives the directory. Upstream a32d9c9f deleted
# Libraries/LibJS/BytecodeDef/, which was a hardcoded `allow_empty = False` glob
# pattern in this list, and the whole build then failed at LOADING time with
# "glob pattern didn't match anything" -- before any target could report why.
# Deriving the patterns means a deleted crate deletes its own pattern.
#
# Split in two because BAZEL PACKAGES CUT ACROSS THE CARGO WORKSPACE: some of the
# crates live under Libraries/LibWeb, which is its own package, and glob() is
# package-relative -- the root package cannot see them at all. So they arrive as
# a filegroup label that LibWeb's own BUILD file defines
# (//Libraries/LibWeb:rust_crate_srcs, emitted by emit_libweb_bazel.py from
# package_crate_globs() HERE, so the two sides cannot disagree about which
# directories exist). This is the first place in this migration where the two
# systems' unit of grouping genuinely disagree: cargo says "one workspace", Bazel
# says "two packages", and a label is the only thing that crosses.
FOREIGN_PACKAGES = {"Libraries/LibWeb": "//Libraries/LibWeb:rust_crate_srcs"}

# Files at the repo root that every crate needs: the two workspace files, the
# toolchain pin and the shared allocator shim. Not a directory between them, so
# nothing here can outlive a crate.
CRATE_SRC_ROOT_FILES = [
    "Cargo.toml",
    "Cargo.lock",
    "rust-toolchain.toml",
    "Libraries/RustAllocator.rs",
]

# `target/` is cargo's own output dir: never an input, and a developer who has run
# cargo by hand in the tree would otherwise have it globbed into every crate's
# action inputs (the reference build sets CARGO_TARGET_DIR into the build dir, so
# it does not exist here -- but that is a property of how we invoke cargo, not of
# the tree).
#
# ANCHORED to each crate root, NOT `**/target/**`. The unanchored form is wrong
# and fails loudly, which is the only good thing about it: flapc has a Rust MODULE
# at `src/target/` (the code generator's per-architecture backends), so
# `**/target/**` dropped 40 source files and the build died with
# `error[E0583]: file not found for module 'target'`. A glob exclusion is a
# pattern over paths and knows nothing about what a directory MEANS; "the dir
# cargo writes to" is `<crate root>/target`, and only the anchored form says that.
def crate_src_glob_excludes(dirs):
    return [d + "/target/**" for d in dirs]


def _manifest_path_deps(manifest_rel):
    """The `path = "..."` dependency dirs declared by one manifest, ROOT-relative.

    Read from the manifest rather than from the workspace member list, because a
    path dependency can point OUTSIDE the workspace: libjs_rust build-depends on
    `flapc = { path = "../Flap" }`, and Libraries/LibJS/Flap is `exclude`d from
    the root workspace. Miss it and touching a flapc source does not rebuild the
    crate whose instruction types are derived from it.
    """
    path = os.path.join(ROOT, manifest_rel)
    if not os.path.exists(path):
        return []
    d = os.path.dirname(manifest_rel)
    out = []
    for m in re.finditer(r'path\s*=\s*"([^"]+)"', open(path).read()):
        p = os.path.normpath(os.path.join(d, m.group(1)))
        if os.path.isdir(os.path.join(ROOT, p)):
            out.append(p)
    return out


def crate_dirs():
    """Every in-tree crate DIRECTORY the root workspace resolves, ROOT-relative.

    Starts from Cargo.toml's `members` and closes over `path =` dependencies, so
    a crate that is added, moved or deleted upstream needs no edit here.
    """
    seen = set()
    queue = sorted(root_workspace_members())
    while queue:
        d = queue.pop()
        if d in seen or not os.path.isdir(os.path.join(ROOT, d)):
            continue
        seen.add(d)
        queue += _manifest_path_deps(os.path.join(d, "Cargo.toml"))
    return sorted(seen)


def _in_foreign_package(d):
    for pkg in FOREIGN_PACKAGES:
        if d == pkg or d.startswith(pkg + "/"):
            return pkg
    return None


def crate_src_globs():
    """The ROOT package's glob patterns for the shared crate source set."""
    return CRATE_SRC_ROOT_FILES + [
        d + "/**" for d in crate_dirs() if not _in_foreign_package(d)]


def crate_src_labels():
    """One filegroup label per foreign package that actually holds a crate."""
    return sorted({FOREIGN_PACKAGES[p] for p in
                   (_in_foreign_package(d) for d in crate_dirs()) if p})


def package_crate_globs(pkg):
    """The crate globs for a foreign package, PACKAGE-relative.

    Called by emit_libweb_bazel.py, so the filegroup on that side of the boundary
    and the glob on this side are derived from one list.
    """
    return sorted(os.path.relpath(d, pkg) + "/**"
                  for d in crate_dirs() if _in_foreign_package(d) == pkg)


def _excluded_dirs():
    """The workspaces Cargo.toml `exclude`s, which resolve their own locks."""
    ws = _toml(os.path.join(ROOT, "Cargo.toml"))["workspace"]
    return [os.path.normpath(d) for d in ws.get("exclude", [])
            if os.path.isdir(os.path.join(ROOT, d))]


def flapc_src_globs():
    """The `exclude`d flapc workspace: its own subtree, plus what it reads out of
    the tree above it.

    One `<dir>/**` rather than a pattern per subdirectory, because the manifest's
    TARGET list is part of the input set whether or not those targets are built:
    Cargo.toml declares `[[bench]] name = "compiler"`, and cargo validates every
    declared target while PARSING the manifest, before it decides what to build
    ("can't find `compiler` bench at benches/compiler.rs"). That bench also
    include_str!s tests/interpreter-layout.conf. A distinction CMake never makes,
    and one only a sandbox reveals -- and a whole-subtree glob cannot lose a
    subdirectory the way an enumerated list of them can.
    """
    dirs = _excluded_dirs()
    extra = ["rust-toolchain.toml"]
    for d in dirs:
        # src/metadata.rs include_str!s the interpreter definition from two
        # directories up: flapc DERIVES the bytecode from it (upstream a32d9c9f),
        # so it is an input, and it lives outside the excluded subtree.
        extra += [x for x in _include_str_paths(d) if not x.startswith(d + "/")]
    return sorted(d + "/**" for d in dirs) + sorted(set(extra))


def _include_str_paths(d):
    """ROOT-relative paths a crate subtree include_str!s, derived by scanning it.

    Derived rather than listed for the same reason as everything else here: the
    one file flapc reads from outside its own subtree changed name and location
    in the commit this repin follows.
    """
    out = set()
    pat = re.compile(r'include_str!\s*\(\s*"([^"]+)"')
    for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, d)):
        dirnames[:] = [x for x in dirnames if x != "target"]
        for fn in filenames:
            if not fn.endswith(".rs"):
                continue
            full = os.path.join(dirpath, fn)
            try:
                text = open(full, errors="replace").read()
            except OSError:
                continue
            for m in pat.finditer(text):
                p = os.path.normpath(os.path.join(
                    os.path.relpath(dirpath, ROOT), m.group(1)))
                if os.path.exists(os.path.join(ROOT, p)):
                    out.add(p)
    return sorted(out)

# Where each crate's Cargo.toml lives, relative to the source root. Parsed from
# the import_rust_crate() call site: MANIFEST_PATH is relative to the CMakeLists
# that calls it.
RE_IMPORT = re.compile(r"import_rust_crate\s*\((.*?)\)", re.S)
RE_BINARY = re.compile(r"build_rust_binary\s*\((.*?)\)", re.S)


def _arg(block, key):
    """A single-valued cmake_parse_arguments key."""
    m = re.search(key + r"\s+([^\s\)]+)", block)
    return m.group(1).strip('"') if m else None


def _multi(block, key, stops):
    """A multi-valued key: everything up to the next keyword."""
    m = re.search(key + r"\s+((?:(?!\b(?:%s)\b)[^\)])*)" % "|".join(stops), block)
    if not m:
        return []
    return [t.strip('"') for t in m.group(1).split() if t.strip('"')]


CMAKELISTS = [
    "Libraries/LibGfx/CMakeLists.txt",
    "Libraries/LibJS/CMakeLists.txt",
    "Libraries/LibRegex/CMakeLists.txt",
    "Libraries/LibTextCodec/CMakeLists.txt",
    "Libraries/LibURL/CMakeLists.txt",
    "Libraries/LibUnicode/CMakeLists.txt",
    "Libraries/LibWeb/CMakeLists.txt",
    # LibWasm calls build_rust_binary(), not import_rust_crate() -- see
    # parse_cmake_binaries() for why that distinction is load-bearing and why it
    # nevertheless has to be in the SAME list.
    "Libraries/LibWasm/CMakeLists.txt",
]

_KEYS = ["MANIFEST_PATH", "CRATE_NAME", "FFI_OUTPUT_DIR", "FFI_HEADER",
         "FFI_HEADERS", "FEATURES", "BINARY_NAME", "OUTPUT_NAME",
         "OUTPUT_PATH_VAR"]


def parse_cmake_crates():
    """[{crate, manifest, features, ffi_headers}] from import_rust_crate calls.

    Deliberately parses CMake rather than hard-coding the answer: the features
    and the header lists are the two things that change when Ladybird moves code
    between crates (it did twice in the week this was written), and a hand-kept
    copy of them is exactly the kind of drift finding 23 is about.

    The `FEATURES` argument is sometimes a VARIABLE, not a literal:

        set(css_rust_features "")
        if (NOT BUILD_SHARED_LIBS)
            set(css_rust_features FEATURES allocator)
        endif()
        import_rust_crate(... ${css_rust_features} ...)

    which is CMake for "features only in a static build". Ladybird's Release
    preset is BUILD_SHARED_LIBS=ON and the Bazel overlay mirrors the *static*
    shape (one archive per crate, linked into cc_librarys), so the `${...}`
    branch is resolved by reading the `set()` inside the `if (NOT
    BUILD_SHARED_LIBS)` — the same branch the Distribution preset takes. That
    resolution is reported, not silent.
    """
    out = []
    for rel in CMAKELISTS:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            continue
        with open(path) as f:
            text = f.read()
        pkgdir = os.path.dirname(rel)
        # var -> features, for the `if (NOT BUILD_SHARED_LIBS)` idiom above.
        vars_ = {}
        for m in re.finditer(
                # `-` is legal in a cargo feature name (`style-recording`), so it
                # has to be in the character class -- a class that excludes it
                # truncates the feature rather than failing to match it.
                r"set\(\s*(\w+)\s+FEATURES\s+([\w\s-]+?)\s*\)", text):
            vars_[m.group(1)] = m.group(2).split()
        for block in RE_IMPORT.findall(text):
            crate = _arg(block, "CRATE_NAME")
            manifest = _arg(block, "MANIFEST_PATH")
            if not (crate and manifest):
                continue
            features = _multi(block, "FEATURES", _KEYS)
            for m in re.finditer(r"\$\{(\w+)\}", block):
                features += vars_.get(m.group(1), [])
            headers = _multi(block, "FFI_HEADERS", _KEYS)
            one = _arg(block, "FFI_HEADER")
            if one:
                headers.append(one)
            out.append({
                "crate": crate,
                "manifest": os.path.normpath(os.path.join(pkgdir, manifest)),
                "features": sorted(set(features)),
                "cmake_ffi_headers": sorted(set(headers)),
            })
    return sorted(out, key=lambda c: c["crate"])


def parse_cmake_binaries():
    """[{crate, bin, manifest, ffi_headers}] from build_rust_binary() calls.

    The SECOND kind of Rust target CMake has, and the one this migration missed
    for a long time, with a consequence worth recording: because
    `Libraries/LibWasm/CMakeLists.txt` was absent from CMAKELISTS and
    `build_rust_binary` was not parsed, the Cranelift crate was **entirely absent
    from the Bazel graph** -- and every browser binary failed with
    `CraneliftFFI.h: No such file or directory`, 1,600 actions into a build that
    could not have worked. The reference build hid it twice over: the header was
    sitting in `Build/full/Libraries/LibWasm`, which a global `-I` reached, and
    the compiler binary was reached by an ABSOLUTE PATH baked into a
    `-DWASM_CRANELIFT_COMPILER_PATH=` -- i.e. two host escapes covering for one
    missing target.

    Two things make a build_rust_binary crate different from an
    import_rust_crate one, and both matter here:

      * There is NO archive to link. `cargo rustc --bin` is the whole build, and
        what the C++ side consumes is the *executable*, spawned at run time.
      * It can STILL emit an FFI header. libwasm_cranelift's build.rs runs
        cbindgen exactly like the staticlib crates do, and
        `Libraries/LibWasm/CraneliftBridge.cpp` includes the result -- bare
        (`#include <CraneliftFFI.h>`), because CMake's FFI_OUTPUT_DIR is
        LibWasm's own binary dir.

    Everything else it shares with import_rust_crate, FEATURES included, and that
    is parsed here for the same reason: upstream's `style-replay` binary is built
    `FEATURES style-recording` out of the same crate as libweb_rust's staticlib.
    A parser that only read FEATURES on the staticlib side would build a
    different binary than CMake does and say nothing -- the finding-23 shape,
    where the two build systems agree on the target list and disagree on the ABI.

    So a binary crate needs both halves: a cargo_binary for the executable, and
    the same declared-header treatment the staticlib crates get. The two are
    reported separately for the same reason import_rust_crate's list is parsed
    rather than hard-coded: which kind a crate is, and whether it emits a header,
    is a property of the CMake call site.
    """
    out = []
    for rel in CMAKELISTS:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            continue
        with open(path) as f:
            text = f.read()
        pkgdir = os.path.dirname(rel)
        # The same `if (NOT BUILD_SHARED_LIBS)` variable form the staticlib side
        # resolves -- see parse_cmake_crates() for why that branch is the one the
        # Bazel overlay mirrors.
        vars_ = {}
        for m in re.finditer(r"set\(\s*(\w+)\s+FEATURES\s+([\w\s-]+?)\s*\)", text):
            vars_[m.group(1)] = m.group(2).split()
        for block in RE_BINARY.findall(text):
            crate = _arg(block, "CRATE_NAME")
            manifest = _arg(block, "MANIFEST_PATH")
            binary = _arg(block, "BINARY_NAME")
            if not (crate and manifest and binary):
                continue
            # FFI_OUTPUT_DIR present at the call site means the build script is
            # expected to write a header. Which header it writes is the
            # observation (FFI_HEADERS_OBSERVED), exactly as for the staticlibs:
            # build_rust_binary has no FFI_HEADERS argument at all, so CMake
            # declares nothing and there is nothing to compare against.
            emits_ffi = _arg(block, "FFI_OUTPUT_DIR") is not None
            features = _multi(block, "FEATURES", _KEYS)
            for m in re.finditer(r"\$\{(\w+)\}", block):
                features += vars_.get(m.group(1), [])
            out.append({
                "crate": crate,
                "bin": binary,
                "manifest": os.path.normpath(os.path.join(pkgdir, manifest)),
                "output_name": _arg(block, "OUTPUT_NAME") or binary,
                "features": sorted(set(features)),
                "emits_ffi": emits_ffi,
            })
    return sorted(out, key=lambda c: c["crate"])


def binary_specs():
    """The per-binary-crate recipe, with the FFI headers each one emits.

    `ffi_bare_include` is derived the same way the staticlib crates' is (by
    scanning the tree for a directory-less `#include`), not asserted: LibWasm
    spells it `#include <CraneliftFFI.h>`, and it must be that scan that says so.
    """
    specs = []
    for b in parse_cmake_binaries():
        headers = sorted(FFI_HEADERS_OBSERVED.get(b["crate"], [])) \
            if b["emits_ffi"] else []
        specs.append(dict(b, ffi_headers=headers,
                          ffi_prefix=FFI_PREFIX.get(b["crate"], "")))
    bare = crates_included_bare(_bare_scan_specs())
    for sp in specs:
        sp["ffi_bare_include"] = bool(bare.get(sp["crate"]))
    return specs


def _bare_scan_specs():
    """Every Rust crate that emits a header, staticlib and binary alike.

    ONE list, because the bare-include scan is a question about the whole tree:
    it looks for a directory-less `#include <X>` where X is any crate's header
    basename, and a scan that only knew about the staticlibs would answer "no"
    for CraneliftFFI.h no matter how many TUs include it that way.
    """
    return [{"crate": c["crate"], "manifest": c["manifest"],
             "ffi_headers": sorted(set(c["cmake_ffi_headers"]) |
                                   set(FFI_HEADERS_OBSERVED.get(c["crate"], [])))}
            for c in parse_cmake_crates()] + \
           [{"crate": b["crate"], "manifest": b["manifest"],
             "ffi_headers": sorted(FFI_HEADERS_OBSERVED.get(b["crate"], []))
             if b["emits_ffi"] else []}
            for b in parse_cmake_binaries()]


def crates_included_bare(specs):
    """Crates whose FFI header is #included with NO directory prefix.

    Derived by scanning the source tree for `#include <X>` where X is exactly a
    crate's FFI header basename, rather than hard-coding a list: which TUs spell
    the include bare is a property of Ladybird's source and changes when someone
    edits an include line.

    Why it matters: 8 of the 10 crates emit a header named `RustFFI.h`. CMake
    gives each library only its OWN crate's binary dir, so a bare
    `#include <RustFFI.h>` is unambiguous there. Bazel propagates every dep's
    include dirs onto one command line, so exposing an unprefixed dir for all
    crates lets one crate's RustFFI.h satisfy another's include -- silently, since
    both exist and only ORDER decides. So the unprefixed dir is opt-in per crate,
    and only for crates that actually need it.
    """
    bare = {}
    pat = re.compile(r'^\s*#\s*include\s*<([^/>]+)>\s*$', re.M)
    wanted = {}
    owner_dir = {}
    for sp in specs:
        # The crate's manifest lives at <Library>/[sub/]Rust/Cargo.toml, so the
        # owning library directory is the manifest's path with the trailing
        # Rust/Cargo.toml removed -- that is the tree whose TUs may include this
        # crate's header bare.
        d = os.path.dirname(sp["manifest"])
        while d and os.path.basename(d) in ("Rust", "rust"):
            d = os.path.dirname(d)
        owner_dir[sp["crate"]] = d
        for h in sp["ffi_headers"]:
            wanted.setdefault(os.path.basename(h), set()).add(sp["crate"])
    for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, "Libraries")):
        dirnames[:] = [d for d in dirnames if d not in ("Rust", "target")]
        for fn_ in filenames:
            if not fn_.endswith((".cpp", ".h")):
                continue
            fpath = os.path.join(dirpath, fn_)
            try:
                with open(fpath, errors="replace") as f:
                    text = f.read()
            except OSError:
                continue
            for m in pat.finditer(text):
                inc = m.group(1)
                if inc not in wanted:
                    continue
                # Attribute the bare include to the crate owned by the library
                # this file lives in, so we never enable the unprefixed dir for
                # an unrelated crate that happens to emit the same basename.
                rel = os.path.relpath(fpath, ROOT)
                for crate in wanted[inc]:
                    owner = owner_dir.get(crate)
                    if owner and rel.startswith(owner + os.sep):
                        bare[crate] = True
    return bare


def crate_specs():
    """The per-crate build recipe the Bazel rule consumes.

    `ffi_headers` is the union of what CMake declares and what the build scripts
    were observed to write, because the two disagree (see FFI_HEADERS_OBSERVED)
    and Bazel needs the *observed* set: an output it does not declare is deleted,
    and one it declares but cargo never writes fails the action.
    """
    specs = []
    for c in parse_cmake_crates():
        observed = FFI_HEADERS_OBSERVED.get(c["crate"])
        headers = sorted(set(c["cmake_ffi_headers"]) | set(observed or []))
        specs.append({
            "crate": c["crate"],
            "manifest": c["manifest"],
            "features": c["features"],
            "ffi_headers": headers,
            "ffi_prefix": FFI_PREFIX.get(c["crate"], ""),
        })
    # Derived from the source tree, not hard-coded: which crates' headers are
    # included without a directory prefix. Scanned over EVERY crate that emits a
    # header (binaries included), so the answer does not depend on which emitter
    # asked.
    bare = crates_included_bare(_bare_scan_specs())
    for sp in specs:
        sp["ffi_bare_include"] = bool(bare.get(sp["crate"]))
    return specs


# ---------------------------------------------------------------------------
# Emitters.
# ---------------------------------------------------------------------------
def emit_crates(crates):
    sys.stdout.write(HEADER)
    print('load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")')
    print()
    print("# %d crates.io crates, every sha256 lifted verbatim out of the two" % len(crates))
    print("# Cargo.lock files. Nothing is re-hashed here and nothing was captured:")
    print("# the lock file is the pin and the URL is a function of (name, version),")
    print("# so this regenerates with no cargo, no network and no CMake.")
    print("#")
    print("# A `.crate` IS a gzipped tar whose single top-level dir is")
    print("# <name>-<version>/, so http_archive unpacks it directly with")
    print("# strip_prefix and an explicit type=\"tgz\" (the .crate extension is")
    print("# not one http_archive recognises) -- no custom repository rule and no")
    print("# per-crate BUILD file: the vendor directory cargo wants is assembled")
    print("# by a normal build action later (see cargo.bzl), not at fetch time.")
    print()
    print("def cargo_crates():")
    for (name, version), sha in sorted(crates.items()):
        print("    http_archive(")
        print("        name = %r," % repo_name(name, version))
        print("        urls = [%r]," % crate_url(name, version))
        print("        sha256 = %r," % sha)
        print("        strip_prefix = %r," % ("%s-%s" % (name, version)))
        # `.crate` is not a suffix http_archive recognises, so the archive type
        # has to be stated. It IS a gzipped tar -- cargo just gives it its own
        # extension -- and without `type` the fetch fails with a confusing
        # "Expected a file with a .zip/.tar.gz/... suffix".
        print("        type = \"tgz\",")
        # A crate has no BUILD file and needs none: the staging action reads the
        # tree through a filegroup, so give every repo the same trivial one.
        print("        build_file_content = _CRATE_BUILD,")
        print("    )")
    print()
    print("# Files only -- deliberately NOT `exclude_directories = 0`. Globbing the")
    print("# directories as well makes Bazel stage both a directory and its")
    print("# contents into the sandbox, which fails with a bare \"File exists\" on")
    print("# the first one (adblock's benches/) -- a message that names the path")
    print("# but not the cause. The staging script rebuilds the tree from the file")
    print("# paths, so the directory entries were never needed.")
    print('_CRATE_BUILD = """filegroup(')
    print("    name = \"srcs\",")
    print('    srcs = glob(["**"]),')
    print('    visibility = ["//visibility:public"],')
    print(")")
    print('"""')


def emit_index(crates, specs):
    sys.stdout.write(HEADER)
    print("# The two tables the build action needs.")
    print("#")
    print("# CARGO_CRATE_FILES: \"<name> <version> <sha256>\" -> the fetched repo's")
    print("# filegroup. The KEY carries the version and hash because the vendor")
    print("# directory cargo reads is named <name>-<version> and its")
    print("# .cargo-checksum.json must contain the crate's own sha256 -- cargo")
    print("# verifies both and refuses the directory otherwise.")
    print()
    print("CARGO_CRATE_FILES = {")
    for (name, version), sha in sorted(crates.items()):
        print("    %r: %r," % ("%s %s %s" % (name, version, sha),
                               "@%s//:srcs" % repo_name(name, version)))
    print("}")
    print()
    print("# The per-crate recipe, parsed from import_rust_crate() in CMake --")
    print("# NOT hand-written. `features` is per crate and changes the ABI")
    print("# silently when wrong; `ffi_headers` is the union of CMake's")
    print("# declaration and what each build script was observed to write")
    print("# (they disagree: libweb_rust's dependency emits a second header")
    print("# CMake never declares, and three LibWeb TUs include it).")
    print()
    print("CARGO_CRATE_SPECS = {")
    for s in specs:
        print("    %r: {" % s["crate"])
        print("        \"manifest\": %r," % s["manifest"])
        print("        \"features\": %r," % s["features"])
        print("        \"ffi_headers\": %r," % s["ffi_headers"])
        print("        \"ffi_prefix\": %r," % s["ffi_prefix"])
        print("        \"ffi_bare_include\": %r," % s["ffi_bare_include"])
        print("    },")
    print("}")
    print()
    print("# The toolchain pin from rust-toolchain.toml, and the triple CMake")
    print("# derives from `rustc -vV`. Both are read, not chosen.")
    print("RUST_CHANNEL = %r" % toolchain_channel())
    print("RUST_TRIPLE = %r" % TRIPLE)


def emit_ring(crates, specs, binaries):
    """cargo_ring.bzl: the whole Rust ring as a macro for the ROOT package.

    A macro instantiated in the root package rather than its own `Meta/cargo`
    package, for one concrete reason: the crate sources live at the repo root
    (Cargo.toml, Cargo.lock, Libraries/RustAllocator.rs, Libraries/*/Rust/**),
    `glob()` is package-relative, and a package under Meta/ cannot glob them. The
    root package can, and this mirrors codegen_root.bzl's root_codegen().

    Generated rather than hand-written for the reason the whole repo works this
    way: the features and the header lists come out of CMake, so when Ladybird
    moves code between crates -- twice in the week this was written; the CSS and
    Layout crates were both split out of libweb_rust -- regenerating IS the fix,
    and a hand-kept copy of them would be the bug (finding 23).
    """
    sys.stdout.write(HEADER)
    print('load(":cargo.bzl", "cargo_binary", "cargo_crate", "cargo_lib", "cargo_bare_include", "rust_sysroot")')
    print('load(":cargo_index.bzl", "CARGO_CRATE_FILES", "CARGO_CRATE_SPECS")')
    print()
    print("# Ladybird's %d production Rust crates and %d binary crates, BUILT BY BAZEL"
          % (len(specs), len(binaries)))
    print("# from the %d crates.io crates Bazel fetched -- replacing the prebuilt" % len(crates))
    print("# 260 MB librust_combined.a that was copied out of Build/full/cargo/, the")
    print("# `ar -M` merge that produced it (README step 1b), and the reference build's")
    print("# flapc and cranelift-compiler binaries. Nothing here names Build/full.")
    print("#")
    print("# Every attribute comes from CARGO_CRATE_SPECS, which")
    print("# Meta/emit_cargo_bazel.py parses out of import_rust_crate() and")
    print("# build_rust_binary() in CMake, so a feature or header list cannot drift from")
    print("# the reference build without the emitter's --report saying so.")
    print()
    print("def cargo_ring():")
    print("    # The pinned toolchain (rust-toolchain.toml says %s), assembled from"
          % toolchain_channel())
    print("    # three fetched components into one tree rustc can find itself in.")
    print("    rust_sysroot(")
    print("        name = \"rust_sysroot\",")
    print("        components = [")
    for component in sorted(TOOLCHAIN_COMPONENTS):
        print("            %r," % ("@rust_%s_%s//:tree" % (
            component.replace("-", "_"), toolchain_channel().replace(".", "_"))))
    print("        ],")
    print("    )")
    print()
    print("    # The crate sources: ONE list for all the crates, because they are one")
    print("    # cargo WORKSPACE. Each of them path-depends on")
    print("    # Libraries/RustAllocator.rs and several are path-dependencies of each")
    print("    # other, so cargo resolves the whole workspace whichever crate you ask")
    print("    # for. Over-declaring costs a rebuild of every crate when any .rs")
    print("    # changes; under-declaring silently reuses a stale archive. The trade is")
    print("    # the right way round, and it is real debt: per-crate source sets need")
    print("    # the path-dependency graph read out of the manifests.")
    print("    #")
    print("    # The patterns are DERIVED from Cargo.toml's member list closed over the")
    print("    # manifests' `path =` deps, not written down: a directory written down")
    print("    # here is an allow_empty=False glob that outlives the directory, and")
    print("    # loading then fails before any target can say why.")
    root_dirs = [d for d in crate_dirs() if not _in_foreign_package(d)]
    print("    crate_srcs = native.glob(%r, exclude = %r, allow_empty = False) + %r"
          % (crate_src_globs(), crate_src_glob_excludes(root_dirs),
             crate_src_labels()))
    for s in specs:
        extra = CRATE_EXTRA_INPUTS.get(s["crate"], [])
        srcs = "crate_srcs"
        if extra:
            srcs = "crate_srcs + %r" % extra
        print()
        print("    cargo_crate(")
        print("        name = %r," % s["crate"])
        print("        crate = %r," % s["crate"])
        print("        crates = CARGO_CRATE_FILES,")
        print("        crate_features = CARGO_CRATE_SPECS[%r][\"features\"]," % s["crate"])
        print("        ffi_headers = CARGO_CRATE_SPECS[%r][\"ffi_headers\"]," % s["crate"])
        print("        ffi_prefix = CARGO_CRATE_SPECS[%r][\"ffi_prefix\"]," % s["crate"])
        print("        ffi_bare_include = CARGO_CRATE_SPECS[%r][\"ffi_bare_include\"],"
              % s["crate"])
        print("        manifest = CARGO_CRATE_SPECS[%r][\"manifest\"]," % s["crate"])
        if extra:
            print("        # Build-script inputs, taken from the reference build's DEPFILES")
            print("        # rather than from reading build.rs: this crate's build script")
            print("        # generates Rust from these, so they are compile inputs.")
        print("        srcs = %s," % srcs)
        print("        sysroot = \":rust_sysroot\",")
        print("    )")
        print()
        print("    # The consumable target: this crate's archive to link and this")
        print("    # crate's generated FFI headers to include, one for one with")
        print("    # CMake's per-library edge. NOT a shared --start-group over all")
        print("    # ten archives: the crates have no true cross-crate symbol")
        print("    # references (measured: 0), the shared symbols are each crate's")
        print("    # own copy of rust-std, and a group makes ld satisfy one crate's")
        print("    # std symbol from another crate's object -- dragging that")
        print("    # crate's C++ FFI into a target that never linked it. See the")
        print("    # block comment in cargo.bzl.")
        print("    cargo_lib(")
        print("        name = %r," % (s["crate"] + "_lib"))
        print("        crate = %r," % (":" + s["crate"]))
        print("    )")
        if s["ffi_bare_include"]:
            # The owning library's TUs spell this crate's header with no
            # directory. That dir must NOT ride on cargo_lib (it propagates
            # transitively and 8 crates ship a RustFFI.h), so it is its own
            # target, depended on by exactly one library.
            print("    cargo_bare_include(")
            print("        name = %r," % (s["crate"] + "_bare_include"))
            print("        crate = %r," % (":" + s["crate"]))
            print("    )")
    print()
    print("    # The BINARY crates: cargo `--bin` targets, declared in CMake with")
    print("    # build_rust_binary() rather than import_rust_crate(). Two of them, and")
    print("    # they are two different shapes:")
    print("    #")
    print("    #   flapc              a pure build TOOL -- Bazel runs it in a genrule to")
    print("    #                      produce the interpreter assembly. Its workspace is")
    print("    #                      `exclude`d from the root one and has its own lock")
    print("    #                      with exactly 3 packages (flapc, in-tree")
    print("    #                      bytecode_def, and smallvec from crates.io pinned")
    print("    #                      =1.15.1 -- the same version AND checksum the big")
    print("    #                      workspace pins, so it is the same fetch rule, not a")
    print("    #                      second one).")
    print("    #   cranelift-compiler a RUNTIME tool -- LibWasm spawns it to AOT-compile")
    print("    #                      WebAssembly, and its build script ALSO emits the")
    print("    #                      CraneliftFFI.h that LibWasm's CraneliftBridge.cpp")
    print("    #                      includes. It is a root-workspace member, so its")
    print("    #                      source set is the shared crate_srcs.")
    for b in binaries:
        member = os.path.dirname(b["manifest"])
        in_root_ws = member in root_workspace_members()
        extra = CRATE_EXTRA_INPUTS.get(b["crate"], [])
        print("    cargo_binary(")
        print("        name = %r," % b["bin"])
        print("        bin = %r," % b["bin"])
        print("        crate = %r," % b["crate"])
        print("        crates = CARGO_CRATE_FILES,")
        print("        manifest = %r," % b["manifest"])
        if b["features"]:
            print("        # build_rust_binary() takes FEATURES too, and this one does:")
            print("        # the same crate builds a staticlib and this binary, and only")
            print("        # the features distinguish what each gets.")
            print("        crate_features = %r," % b["features"])
        if b["ffi_headers"]:
            print("        # This binary crate's build script runs cbindgen too, so the")
            print("        # header is a DECLARED output -- Bazel deletes what nothing")
            print("        # declares, and LibWasm includes this one bare.")
            print("        ffi_headers = %r," % b["ffi_headers"])
            print("        ffi_prefix = %r," % b["ffi_prefix"])
            print("        ffi_bare_include = %r," % b["ffi_bare_include"])
        if in_root_ws:
            print("        # A member of the ROOT cargo workspace (Cargo.toml lists it), so")
            print("        # cargo resolves the whole workspace whichever crate you ask for")
            print("        # and the source set is the shared one -- same over-declaration,")
            print("        # same reason, as the staticlib crates.")
            srcs = "crate_srcs"
            if extra:
                srcs += " + %r" % extra
            print("        srcs = %s," % srcs)
        else:
            print("        # Its OWN workspace (`exclude`d from the root one), so its source")
            print("        # set is its own subtree plus what it include_str!s from above")
            print("        # it -- both derived, the subtree from Cargo.toml's `exclude`")
            print("        # and the rest by scanning for include_str!.")
            print("        srcs = native.glob(%r, exclude = %r, allow_empty = False),"
                  % (flapc_src_globs(), crate_src_glob_excludes(_excluded_dirs())))
        print("        sysroot = \":rust_sysroot\",")
        print("    )")
        if b["ffi_headers"]:
            print()
            print("    # The consumable target, IDENTICAL in shape to a staticlib crate's:")
            print("    # this crate's generated header to include. There is no archive to")
            print("    # link -- what C++ consumes from a binary crate is the EXECUTABLE,")
            print("    # spawned at run time -- so cargo_lib yields a headers-only CcInfo.")
            print("    cargo_lib(")
            print("        name = %r," % (b["crate"] + "_lib"))
            print("        crate = %r," % (":" + b["bin"]))
            print("    )")
            if b["ffi_bare_include"]:
                print("    cargo_bare_include(")
                print("        name = %r," % (b["crate"] + "_bare_include"))
                print("        crate = %r," % (":" + b["bin"]))
                print("    )")


def emit_extension(crates):
    sys.stdout.write(HEADER)
    print("# http_archive is a REPOSITORY rule, so under bzlmod it cannot be")
    print("# called from MODULE.bazel -- it has to come from a module extension.")
    print("# That indirection is also what lets one use_repo() name %d repos"
          % (len(crates) + len(TOOLCHAIN_COMPONENTS)))
    print("# without MODULE.bazel enumerating a single URL or hash.")
    print('load(":cargo_crates.bzl", "cargo_crates")')
    print('load(":cargo.bzl", "rust_toolchain_archives")')
    print()
    print("def _cargo_deps_impl(_ctx):")
    print("    cargo_crates()")
    print("    # The pinned toolchain is fetched the same way the crates are:")
    print("    # rust-toolchain.toml names a channel, and honouring it without")
    print("    # rustup means three versioned http_archives.")
    print("    rust_toolchain_archives()")
    print()
    print("cargo_deps = module_extension(implementation = _cargo_deps_impl)")


def emit_use_repo(crates):
    """The use_repo() block MODULE.bazel needs.

    Emitted rather than hand-maintained because bzlmod requires every repo an
    extension creates to be named there to be visible, and 157 names kept in
    sync by hand is guaranteed drift whose failure ("no such repository") lands
    far from its cause.
    """
    names = [repo_name(n, v) for n, v in crates]
    names += ["rust_%s_%s" % (c.replace("-", "_"),
                              toolchain_channel().replace(".", "_"))
              for c in TOOLCHAIN_COMPONENTS]
    print("use_repo(")
    print("    cargo_deps,")
    for n in sorted(names):
        print("    %r," % n)
    print(")")


def report(crates):
    """What resolved, and — the part that matters — what did not.

    Counts both halves of the registry/workspace split, and diffs CMake's
    declared FFI headers against the observed ones, because a header CMake
    forgets to declare is invisible until a TU that includes it fails to compile.
    """
    rc = 0
    for rel in LOCKS:
        pkgs = lock_packages(rel)
        registry, workspace = split_packages(pkgs)
        print("%s: %d packages = %d registry + %d workspace members"
              % (rel, len(pkgs), len(registry), len(workspace)))
        for name, _v in workspace:
            print("    workspace member (a source, never fetched): %s" % name)
    print("distinct crates to fetch: %d" % len(crates))
    print("rust toolchain pin: %s (%s)" % (toolchain_channel(), TRIPLE))
    print()
    for c in parse_cmake_crates():
        observed = FFI_HEADERS_OBSERVED.get(c["crate"])
        print("%-30s features=%-12s manifest=%s"
              % (c["crate"], ",".join(c["features"]) or "-", c["manifest"]))
        if observed is None:
            print("    NO OBSERVED HEADER LIST -- run the reference cargo build "
                  "with FFI_OUTPUT_DIR set and add it to FFI_HEADERS_OBSERVED")
            rc = 1
            continue
        extra = sorted(set(observed) - set(c["cmake_ffi_headers"]))
        missing = sorted(set(c["cmake_ffi_headers"]) - set(observed))
        if extra:
            print("    written but NOT declared by CMake: %s" % ", ".join(extra))
        if missing:
            print("    declared by CMake but never written: %s" % ", ".join(missing))
            rc = 1
    print()
    # The binary crates are reported separately, because the two kinds fail
    # differently: a missing staticlib crate is a link error, a missing binary
    # crate is a header that never appears (CraneliftFFI.h) plus a tool that has
    # to be found at run time.
    for b in binary_specs():
        print("%-30s bin=%-20s manifest=%s"
              % (b["crate"], b["bin"], b["manifest"]))
        if b["emits_ffi"] and not b["ffi_headers"]:
            print("    FFI_OUTPUT_DIR is set at the call site but no header is "
                  "listed in FFI_HEADERS_OBSERVED -- run the reference cargo "
                  "build with FFI_OUTPUT_DIR set and add what it wrote")
            rc = 1
        for h in b["ffi_headers"]:
            print("    emits %s (bare-included: %s)"
                  % (h, "yes" if b["ffi_bare_include"] else "no"))
    known = ({c["crate"] for c in parse_cmake_crates()} |
             {b["crate"] for b in parse_cmake_binaries()})
    for crate in sorted(set(FFI_HEADERS_OBSERVED) - known):
        print("%-30s observed but no import_rust_crate/build_rust_binary found "
              "-- did a crate get renamed or moved?" % crate)
        rc = 1
    return rc


GENERATED = {
    "cargo_crates.bzl": "--crates",
    "cargo_index.bzl": "--index",
    "cargo_extension.bzl": "--extension",
    "cargo_ring.bzl": "--ring",
}


def check(dirpath):
    """Regenerate every file into memory and byte-compare with the checked-in one.

    The rule this repo runs on ("never hand-edit a generated BUILD file") is only
    enforceable if the check is cheap, so it is one flag.
    """
    import io
    rc = 0
    crates = all_registry_crates()
    specs = crate_specs()
    for fn, flag in sorted(GENERATED.items()):
        buf = io.StringIO()
        real, sys.stdout = sys.stdout, buf
        try:
            {"--crates": lambda: emit_crates(crates),
             "--index": lambda: emit_index(crates, specs),
             "--extension": lambda: emit_extension(crates),
             "--ring": lambda: emit_ring(crates, specs, binary_specs())}[flag]()
        finally:
            sys.stdout = real
        path = os.path.join(dirpath, fn)
        if not os.path.exists(path):
            print("MISSING  %s" % path)
            rc = 1
            continue
        with open(path) as f:
            have = f.read()
        if have == buf.getvalue():
            print("ok       %s" % fn)
        else:
            print("DRIFTED  %s" % fn)
            rc = 1
    return rc


def main():
    argv = sys.argv[1:]
    if "--check" in argv:
        return check(argv[argv.index("--check") + 1])
    crates = all_registry_crates()
    if "--crates" in argv:
        emit_crates(crates)
    elif "--index" in argv:
        emit_index(crates, crate_specs())
    elif "--extension" in argv:
        emit_extension(crates)
    elif "--ring" in argv:
        emit_ring(crates, crate_specs(), binary_specs())
    elif "--use-repo" in argv:
        emit_use_repo(crates)
    else:
        return report(crates)
    return 0


if __name__ == "__main__":
    sys.exit(main())
