#!/usr/bin/env python3
"""Re-pin Chromium's HSTS preload table, and write hsts_preload.bzl.

CMake fetches net/http/transport_security_state_static.json from Chromium's
**main** at configure time (Meta/CMake/hsts_preload.cmake), unversioned. That is
an upstream defect we cannot fix from the overlay, so the overlay pins it
downstream: one immutable commit URL plus the sha256 this script MEASURED by
downloading it.

Two properties this script exists to preserve, both of them learned the hard way:

  * Pin a COMMIT, not a release tag. The tag 139.0.7258.5 serves an 18.7 MB file
    generating 168,593 entries; the commit main pointed at when the reference
    CMake build configured serves 10.5 MB and 94,626. A tag is a pin, but a pin
    to a *different table* -- so pinning to one trades a hermeticity gap for a
    parity gap. `--commit` defaults to the newest commit touching the path, which
    is the one `main` serves.
  * Never write a hash you did not measure. The sha256 in the output is computed
    from the bytes downloaded from the URL being pinned. `--expect-sha256`
    additionally asserts the pinned bytes equal a file you already have (the one
    CMake downloaded), which is how the current pin was shown to keep byte-parity
    with the reference build.

Usage:
    # re-pin to the newest commit touching the path
    python3 Meta/pin_hsts_preload.py > hsts_preload.bzl

    # re-pin, and refuse unless it matches what CMake already downloaded
    python3 Meta/pin_hsts_preload.py \
        --expect-same-as Build/caches/HSTSPreload/transport_security_state_static.json \
        > hsts_preload.bzl

    # just report what the pin would be, without writing
    python3 Meta/pin_hsts_preload.py --check
"""
import argparse
import hashlib
import json
import shutil
import subprocess
import sys

PATH = "net/http/transport_security_state_static.json"
COMMITS_API = "https://api.github.com/repos/chromium/chromium/commits?path={path}&per_page=1"
COMMIT_API = "https://api.github.com/repos/chromium/chromium/commits/{commit}"
RAW_URL = "https://raw.githubusercontent.com/chromium/chromium/{commit}/" + PATH

TEMPLATE = '''\
# Chromium's HSTS preload table, pinned to a commit. GENERATED by
# Meta/pin_hsts_preload.py -- see that script to re-pin; do not hand-edit.
#
# WHY THIS FILE EXISTS. `Meta/CMake/hsts_preload.cmake` downloads
# net/http/transport_security_state_static.json from Chromium's **main** at
# configure time -- an unversioned ref. The generator turns it into a ~95,000
# entry `constexpr Array` of domains LibHTTP forces to HTTPS, so "whatever main
# served the day you configured" decides a security-relevant table, and two
# developers who configured on different days build different browsers.
#
# The fix belongs upstream (pin the URL in hsts_preload.cmake). We cannot make
# that change from here, so we pin DOWNSTREAM: Bazel fetches one immutable
# commit URL with a sha256, and the upstream unpinned fetch is filed as a bug.
#
# Pinning downstream is only honest if it does not break byte-parity with CMake,
# and this pin does not: the bytes this commit serves are byte-identical to the
# ones CMake's `main` fetch downloaded for the reference build ({size:,} bytes,
# checked with --expect-same-as, which refuses to write this file otherwise).
# Pinning to a Chromium *release tag* would NOT have that property: 139.0.7258.5
# serves 18.7 MB and generates 168,593 entries against this commit's 94,626.
#
# Two consequences worth knowing:
#
#   * CMake still tracks `main`, so a CMake configure NEWER than this pin will
#     disagree with Bazel. That is now a visible, dated disagreement between one
#     pinned input and one unpinned one, instead of two unpinned fetches that
#     happened to agree. `download_file` is a no-op when the file already exists
#     (verified with ENABLE_NETWORK_DOWNLOADS=OFF), so staging the Bazel-fetched
#     file into Build/caches/HSTSPreload/ before configuring makes CMake consume
#     this same pin -- see README, "Getting the three inputs".
#   * Bumping the pin is a deliberate, reviewable act: re-run
#     Meta/pin_hsts_preload.py, which resolves the newest commit touching the
#     path, downloads it, and writes this file with the hash it measured.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

# The pinned commit: "{subject}" ({date}).
# raw.githubusercontent.com paths are immutable for a full commit sha, unlike the
# `main` path CMake uses.
HSTS_PRELOAD_COMMIT = "{commit}"

HSTS_PRELOAD_SHA256 = "{sha256}"

HSTS_PRELOAD_URL = "https://raw.githubusercontent.com/chromium/chromium/{{}}/net/http/transport_security_state_static.json".format(
    HSTS_PRELOAD_COMMIT,
)

def _hsts_preload_impl(_ctx):
    http_file(
        name = "hsts_preload_json",
        urls = [HSTS_PRELOAD_URL],
        sha256 = HSTS_PRELOAD_SHA256,
        downloaded_file_path = "transport_security_state_static.json",
    )

hsts_preload = module_extension(implementation = _hsts_preload_impl)
'''


def _get(url, timeout):
    """GET url, as bytes.

    Shells out to curl rather than using urllib: this runs behind
    TLS-intercepting proxies (urllib rejected ours with CERTIFICATE_VERIFY_FAILED
    while curl, which reads the system CA bundle the same way git and Bazel do,
    succeeded). A pin script that cannot run in the environment the build runs in
    is not a pin script.
    """
    if shutil.which("curl") is None:
        sys.exit("curl not found; it is how this script reaches the network")
    p = subprocess.run(["curl", "-sSL", "--fail", "--max-time", str(timeout), url],
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if p.returncode != 0:
        sys.exit("fetch failed for %s: %s" % (url, p.stderr.decode().strip()))
    return p.stdout


def newest_commit():
    """The newest commit touching the path -- i.e. what `main` currently serves."""
    commits = json.loads(_get(COMMITS_API.format(path=PATH), 60))
    if not commits:
        sys.exit("no commits returned for %s" % PATH)
    c = commits[0]
    return c["sha"], c["commit"]["message"].splitlines()[0], c["commit"]["committer"]["date"][:10]


def describe(commit):
    """Subject line + date for a commit, so the pin records WHAT it pinned."""
    c = json.loads(_get(COMMIT_API.format(commit=commit), 60))
    return (c["commit"]["message"].splitlines()[0],
            c["commit"]["committer"]["date"][:10])


def fetch(commit):
    blob = _get(RAW_URL.format(commit=commit), 300)
    return blob, hashlib.sha256(blob).hexdigest()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--commit", help="pin this commit instead of the newest one touching the path")
    ap.add_argument("--expect-same-as", metavar="FILE",
                    help="fail unless the pinned bytes equal FILE (e.g. the file CMake downloaded)")
    ap.add_argument("--check", action="store_true",
                    help="report the pin on stderr and write nothing")
    args = ap.parse_args(argv)

    if args.commit:
        commit = args.commit
        subject, date = describe(commit)
    else:
        commit, subject, date = newest_commit()

    blob, sha256 = fetch(commit)

    if args.expect_same_as:
        want = open(args.expect_same_as, "rb").read()
        if want != blob:
            sys.exit(
                "PARITY: the pinned bytes differ from %s (%d vs %d bytes).\n"
                "Chromium's main has moved since that file was downloaded. Pinning this\n"
                "commit would make Bazel's generated table differ from CMake's; either\n"
                "re-run CMake's configure (or stage the pinned file into\n"
                "Build/caches/HSTSPreload/), or pin the older commit with --commit."
                % (args.expect_same_as, len(want), len(blob))
            )
        print("parity OK: pinned bytes identical to %s" % args.expect_same_as, file=sys.stderr)

    print("commit %s  %s  %s  %d bytes  sha256 %s"
          % (commit[:12], date, subject, len(blob), sha256), file=sys.stderr)
    if args.check:
        return 0

    sys.stdout.write(TEMPLATE.format(
        commit=commit, sha256=sha256, size=len(blob),
        subject=subject, date=date,
    ))
    return 0


if __name__ == "__main__":
    sys.exit(main())
