#!/bin/bash
# Build Ladybird's vcpkg dependency tree with ZERO network access, from
# distfiles Bazel already fetched. Driver for the vcpkg_tree build action.
#
# This is Ring 2 part 2. Part 1 (Meta/emit_vcpkg_bazel.py) made Bazel own
# fetching; this makes vcpkg build from what Bazel fetched and nothing else.
#
# Contract:
#   $1  install root to produce (the vcpkg_installed/ equivalent)
#   $2  index file: "<sha512> <path>" per line, the Bazel-fetched distfiles
#   $3  vcpkg checkout (its own git tree, for ports/ and versions/)
#   $4  Ladybird source root (manifest + overlay-ports + overlay-triplets)
#   $5  triplet (e.g. x64-linux-dynamic)
#
# Five things here are load-bearing, each established by testing (findings 23/24):
#
#   1. --x-asset-sources with x-script routes every download to a script that
#      resolves it from the index BY HASH; x-block-origin makes vcpkg hard-fail
#      instead of silently falling back to the network. That is what makes this
#      hermetic rather than merely cached, and it is why the boundary can be
#      verified: with x-block-origin, a missing distfile is an error, not a
#      download. (x-asset-sources is an experimental `x-` feature -- the main
#      design risk in this approach.)
#   2. The manifest is COPIED VERBATIM. Never reconstructed: a hand-derived
#      dependency list loses feature selections on transitive deps, and
#      libpng[apng] alone is 20 exported symbols.
#   3. build-vcpkg-variables.cmake must sit at <install-root>/.. because
#      base-triplets/base.cmake includes ${_VCPKG_INSTALLED_DIR}/../build-vcpkg-variables.cmake.
#      It carries LDFLAGS=-Wl,-z,noseparate-code (a patchelf/binutils-2.43.50
#      workaround). Without it, 15 of 21 libraries came out with 5 LOAD segments
#      instead of 3 -- a cross-system input, generated by the CMake step, that is
#      load-bearing for byte-parity of the vcpkg step.
#   4. The binary cache is OFF by default (--binarysource=clear), because a run
#      that restores prebuilt archives proves nothing about building from source.
#      But a 45-minute action that loses everything when it is interrupted is not
#      viable either -- a sandbox restart killed this at 57/76 ports after 14
#      minutes, twice. So VCPKG_BAZEL_CACHE opts into a local cache dir, and the
#      distinction is the same one as the capture's resume rule: vcpkg's binary
#      cache is keyed by each port's ABI HASH (a digest of its source, features,
#      triplet, toolchain and dependencies' hashes), which makes it
#      content-addressed and therefore safe to keep across interruptions, exactly
#      as downloads/ is. The install tree and buildtrees are not, and are still
#      discarded. Use it for iteration; leave it unset for the from-source proof.
#   5. vcpkg_from_git bypasses asset caching entirely (it shells out to `git
#      fetch`, which no asset source intercepts), but it DOES honour a
#      pre-placed downloads/${PORT}-${REF}.tar.gz. Those are staged here.
set -euo pipefail

OUT="${1:?install root}"
INDEX="${2:?distfile index}"
VCPKG_TREE="${3:?vcpkg checkout}"
SRC="${4:?ladybird source root}"
TRIPLET="${5:-x64-linux-dynamic}"
WHEELS="${6-}"

# vcpkg's buildtrees peak around 3 GB and $TMPDIR is frequently a tmpfs sized well
# under that (7.9 GB here, shared with everything else), which surfaces as
# `cp: error writing ...: No space left on device` from the ASSET SCRIPT -- a
# message that blames the pin for a full disk.
#
# So do not use $TMPDIR at all: put the scratch dir NEXT TO THE DECLARED OUTPUT,
# which is inside bazel-out and therefore on whatever real filesystem the output
# base lives on. That also removes a flag from the recipe -- pointing $TMPDIR
# somewhere bigger needs BOTH --action_env and --host_action_env (this action runs
# in the target AND exec configurations, finding 26's duplication again), and an
# `env =` on the rule silently beats --action_env anyway, so the flag route is two
# ways wrong. Report the free space either way: a 3 GB build on a 2 GB disk should
# say so in its own voice rather than 20 minutes later in someone else's.
# mkdir first: Bazel creates the declared output dir but not necessarily its parent
# before the action runs, and mktemp does not create intermediate dirs. Absolute,
# because vcpkg rejects a relative $HOME outright ("was not an absolute path") and
# $OUT arrives execroot-relative -- the same relative-vs-absolute distinction that
# broke the asset index above, in a third place.
mkdir -p "$(dirname "$OUT")"
OUT_PARENT="$(cd "$(dirname "$OUT")" && pwd)"
WORK="$(mktemp -d "$OUT_PARENT/vcpkg-scratch.XXXXXX")"
echo "vcpkg_build: scratch dir $WORK ($(df -h "$WORK" | awk 'NR==2{print $4}') free)" >&2
# Cleaned up on the way out INCLUDING on failure -- an interrupted run used to
# leave a multi-GB tree behind, and several of them is how the disk filled.
trap 'rm -rf "$WORK"' EXIT INT TERM

# The index arrives as an EXECROOT-RELATIVE path (bazel-out/.../x.index), and the
# asset-cache script below is run by vcpkg from vcpkg's own working directory, not
# ours -- so a relative path there resolves against the wrong dir and awk reports
# "cannot open". Absolutize it here, once, while we are still in the execroot.
#
# Why this survived so long: on the machine this was developed on, the vcpkg
# checkout already had downloads/tools/cmake-4.4.0-linux populated by an earlier
# `Meta/ladybird.py vcpkg` run, so vcpkg found its tools locally and never invoked
# the asset script for one. Only a clone with a pristine checkout makes vcpkg ask
# for cmake -- and then the script fails, is reported as "no asset cache hits",
# and x-block-origin correctly refuses to reach the network.
#
# The index's VALUES are execroot-relative for the same reason, so rewrite them
# to absolute here too: awk finding the row is only half the job, and `cp` from a
# relative path fails identically once vcpkg has chdir'd. Both halves have to be
# absolutized in the same place, or the failure just moves one line down.
EXECROOT="$PWD"
INDEX_ABS="$WORK/index"
awk -v root="$EXECROOT" \
    '{ if ($2 ~ /^\//) print $1, $2; else print $1, root "/" $2 }' \
    "$INDEX" > "$INDEX_ABS"
INDEX="$INDEX_ABS"

# vcpkg reads $HOME (for its own config/telemetry dirs) and hard-fails "unable to
# read $HOME" without it. Bazel deliberately does not pass HOME through to
# actions -- that is the sandbox doing its job, since anything an action reads
# from a real home directory is an undeclared input. So point HOME at the
# action's own scratch dir: vcpkg gets a writable HOME, and it is one that cannot
# leak state between builds.
export HOME="$WORK/home"
mkdir -p "$HOME"

# --- pip: offline, from Bazel-fetched wheels only ----------------------------
#
# vcpkg's asset cache does NOT cover pip. The angle overlay-port calls
# x_vcpkg_get_python_packages, which runs `pip install ply` inside a venv, and
# neither x-script nor x-block-origin ever sees the request -- so the 76-distfile
# pin says nothing about it and, with this action running `no-sandbox` and
# inheriting the shell env, pip happily used the caller's HTTP_PROXY for months
# (finding 36). `requires-network: "0"` did not stop it: that is a scheduling hint,
# not a namespace.
#
# pip's own offline switches are the fix, so no portfile patch is needed:
# PIP_NO_INDEX forbids talking to an index at all, PIP_FIND_LINKS points at a
# directory of wheels Bazel fetched by URL+hash. A package that is not pinned then
# fails with "No matching distribution found", which is the pip-side equivalent of
# x-block-origin -- an error instead of a download.
#
# Unset the proxy variables too. Leaving them would make the *failure* mode depend
# on the caller's environment: --no-index means pip should not reach an index, and
# an inherited proxy is exactly how this went unnoticed. Belt and braces, because
# the lesson of finding 36 is that one unenforced control is not a control.
FINDLINKS="$WORK/wheels"
mkdir -p "$FINDLINKS"
if [ -n "$WHEELS" ]; then
    IFS=',' read -r -a _wheels <<< "$WHEELS"
    for w in "${_wheels[@]}"; do
        [ -n "$w" ] && cp "$w" "$FINDLINKS/"
    done
fi
export PIP_NO_INDEX=1
export PIP_FIND_LINKS="$FINDLINKS"
export PIP_DISABLE_PIP_VERSION_CHECK=1
unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy
echo "vcpkg_build: pip is offline; $(ls "$FINDLINKS" | wc -l) pinned wheel(s)" >&2

# --- the asset-cache script: resolve by hash, never fetch --------------------
cat > "$WORK/fetch.sh" <<EOF
#!/bin/bash
# args: <url> <sha512> <dst>. Resolve from the Bazel-fetched index by HASH, so
# the URL is irrelevant -- what is verified is the content.
set -euo pipefail
src=\$(awk -v s="\$2" 'tolower(\$1)==tolower(s) {print \$2; exit}' "$INDEX")
if [ -n "\$src" ]; then cp "\$src" "\$3"; exit 0; fi
echo "vcpkg_build: distfile MISSING FROM INDEX: \$1 sha512=\$2" >&2
exit 1
EOF
chmod +x "$WORK/fetch.sh"

# --- a writable vcpkg root (vcpkg writes buildtrees/downloads/packages) -----
ROOT="$WORK/root"
mkdir -p "$ROOT"
cp -r "$VCPKG_TREE/." "$ROOT/" 2>/dev/null || true
rm -rf "$ROOT/installed" "$ROOT/packages" "$ROOT/buildtrees"
mkdir -p "$ROOT/downloads"

# Pre-place the git-sourced externals (see note 5).
#
# This used to be `if [ -d ... ]; then cp ... 2>/dev/null || true; fi` -- three
# separate ways to succeed while copying nothing, in four lines. On the machine
# that developed this, the directory existed because I had created it by hand; on a
# fresh clone it does not, so all four archives were silently absent and the build
# failed ~20 minutes later inside skia's portfile with
# `git fetch https://android.googlesource.com/.../piex.git ... Error code: 128`,
# naming neither this directory nor the tarball. Exactly the finding-35 shape: a
# copy that cannot fail is indistinguishable from a copy that is not needed.
#
# So: fail here, naming what is missing and where it comes from. VCPKG_GIT_ARCHIVES
# in vcpkg_git_archives.bzl lists the four expected names -- that file is GENERATED
# and checked in, and (finding 36) is currently loaded by nothing at all, which is
# the deeper bug this only reports. These are `git archive` output, so unlike the 76
# distfiles they have no URL to http_file; making Bazel produce them needs a repo
# rule that clones at the pinned ref (gap 7).
GIT_ARCHIVES="$SRC/Meta/CMake/vcpkg/git-archives"
if ! compgen -G "$GIT_ARCHIVES/*.tar.gz" > /dev/null; then
    echo "vcpkg_build: no git-sourced externals at $GIT_ARCHIVES" >&2
    echo "vcpkg_build: 4 are required (see VCPKG_GIT_ARCHIVES in" >&2
    echo "vcpkg_build: vcpkg_git_archives.bzl). vcpkg_from_git bypasses the asset" >&2
    echo "vcpkg_build: cache entirely, so without them skia and angle will try to" >&2
    echo "vcpkg_build: 'git fetch' and fail ~20 minutes into the build with an" >&2
    echo "vcpkg_build: error naming a googlesource URL rather than this directory." >&2
    exit 1
fi
cp "$GIT_ARCHIVES"/*.tar.gz "$ROOT/downloads/"

# --- manifest, verbatim (note 2) --------------------------------------------
MANIFEST="$WORK/manifest"
mkdir -p "$MANIFEST"
cp "$SRC/vcpkg.json" "$MANIFEST/"
[ -f "$SRC/vcpkg-configuration.json" ] && cp "$SRC/vcpkg-configuration.json" "$MANIFEST/"
# vcpkg-configuration.json names its overlay-ports RELATIVE to the manifest
# root, so the overlay has to exist at that relative path too.
mkdir -p "$MANIFEST/Meta/CMake/vcpkg"
cp -r "$SRC/Meta/CMake/vcpkg/overlay-ports" "$MANIFEST/Meta/CMake/vcpkg/"

# --- optional content-addressed resume (note 4) ------------------------------
if [ -n "${VCPKG_BAZEL_CACHE:-}" ]; then
    mkdir -p "$VCPKG_BAZEL_CACHE"
    VCPKG_BINARY_SOURCE="--binarysource=clear;files,$VCPKG_BAZEL_CACHE,readwrite"
    echo "vcpkg_build: ABI-hash-keyed cache at $VCPKG_BAZEL_CACHE (resumable)" >&2
fi

# --- the LDFLAGS file, at the path the triplet includes (note 3) ------------
mkdir -p "$OUT"
printf 'set(ENV{LDFLAGS} -Wl,-z,noseparate-code)\n' \
    > "$(dirname "$OUT")/build-vcpkg-variables.cmake"

exec "$ROOT/vcpkg" install \
    --x-manifest-root="$MANIFEST" \
    --overlay-ports="$SRC/Meta/CMake/vcpkg/overlay-ports" \
    --overlay-triplets="$SRC/Meta/CMake/vcpkg/release-triplets" \
    --triplet="$TRIPLET" \
    --host-triplet="$TRIPLET" \
    --x-install-root="$OUT" \
    --x-buildtrees-root="$WORK/bt" \
    --downloads-root="$ROOT/downloads" \
    ${VCPKG_BINARY_SOURCE:---binarysource=clear} \
    --x-asset-sources="clear;x-script,$WORK/fetch.sh {url} {sha512} {dst};x-block-origin"
