#!/bin/bash
# Build Ladybird's vcpkg dependency tree with ZERO network access, from
# distfiles Bazel already fetched. Driver for the vcpkg_tree build action.
#
# This is Ring 2 part 2. Part 1 (Meta/emit_vcpkg_bazel.py) made Bazel own
# fetching; this makes vcpkg build from what Bazel fetched and nothing else.
#
# Contract:
#   $1  install root to produce (the vcpkg_installed/ equivalent)
#   $2  index file: "<sha512> <path>" per line, the Bazel-fetched distfiles
#   $3  vcpkg checkout (its own git tree, for ports/ and versions/)
#   $4  Ladybird source root (manifest + overlay-ports + overlay-triplets)
#   $5  triplet (e.g. x64-linux-dynamic)
#
# Five things here are load-bearing, each established by testing (findings 23/24):
#
#   1. --x-asset-sources with x-script routes every download to a script that
#      resolves it from the index BY HASH; x-block-origin makes vcpkg hard-fail
#      instead of silently falling back to the network. That is what makes this
#      hermetic rather than merely cached, and it is why the boundary can be
#      verified: with x-block-origin, a missing distfile is an error, not a
#      download. (x-asset-sources is an experimental `x-` feature -- the main
#      design risk in this approach.)
#   2. The manifest is COPIED VERBATIM. Never reconstructed: a hand-derived
#      dependency list loses feature selections on transitive deps, and
#      libpng[apng] alone is 20 exported symbols.
#   3. build-vcpkg-variables.cmake must sit at <install-root>/.. because
#      base-triplets/base.cmake includes ${_VCPKG_INSTALLED_DIR}/../build-vcpkg-variables.cmake.
#      It carries LDFLAGS=-Wl,-z,noseparate-code (a patchelf/binutils-2.43.50
#      workaround). Without it, 15 of 21 libraries came out with 5 LOAD segments
#      instead of 3 -- a cross-system input, generated by the CMake step, that is
#      load-bearing for byte-parity of the vcpkg step.
#   4. --binarysource=clear forces a genuine from-source build; otherwise vcpkg
#      restores prebuilt archives from its own cache and proves nothing.
#   5. vcpkg_from_git bypasses asset caching entirely (it shells out to `git
#      fetch`, which no asset source intercepts), but it DOES honour a
#      pre-placed downloads/${PORT}-${REF}.tar.gz. Those are staged here.
set -euo pipefail

OUT="${1:?install root}"
INDEX="${2:?distfile index}"
VCPKG_TREE="${3:?vcpkg checkout}"
SRC="${4:?ladybird source root}"
TRIPLET="${5:-x64-linux-dynamic}"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# --- the asset-cache script: resolve by hash, never fetch --------------------
cat > "$WORK/fetch.sh" <<EOF
#!/bin/bash
# args: <url> <sha512> <dst>. Resolve from the Bazel-fetched index by HASH, so
# the URL is irrelevant -- what is verified is the content.
set -euo pipefail
src=\$(awk -v s="\$2" 'tolower(\$1)==tolower(s) {print \$2; exit}' "$INDEX")
if [ -n "\$src" ]; then cp "\$src" "\$3"; exit 0; fi
echo "vcpkg_build: distfile MISSING FROM INDEX: \$1 sha512=\$2" >&2
exit 1
EOF
chmod +x "$WORK/fetch.sh"

# --- a writable vcpkg root (vcpkg writes buildtrees/downloads/packages) -----
ROOT="$WORK/root"
mkdir -p "$ROOT"
cp -r "$VCPKG_TREE/." "$ROOT/" 2>/dev/null || true
rm -rf "$ROOT/installed" "$ROOT/packages" "$ROOT/buildtrees"
mkdir -p "$ROOT/downloads"

# Pre-place the git-sourced externals (see note 5).
if [ -d "$SRC/Meta/CMake/vcpkg/git-archives" ]; then
    cp "$SRC/Meta/CMake/vcpkg/git-archives/"*.tar.gz "$ROOT/downloads/" 2>/dev/null || true
fi

# --- manifest, verbatim (note 2) --------------------------------------------
MANIFEST="$WORK/manifest"
mkdir -p "$MANIFEST"
cp "$SRC/vcpkg.json" "$MANIFEST/"
[ -f "$SRC/vcpkg-configuration.json" ] && cp "$SRC/vcpkg-configuration.json" "$MANIFEST/"
# vcpkg-configuration.json names its overlay-ports RELATIVE to the manifest
# root, so the overlay has to exist at that relative path too.
mkdir -p "$MANIFEST/Meta/CMake/vcpkg"
cp -r "$SRC/Meta/CMake/vcpkg/overlay-ports" "$MANIFEST/Meta/CMake/vcpkg/"

# --- the LDFLAGS file, at the path the triplet includes (note 3) ------------
mkdir -p "$OUT"
printf 'set(ENV{LDFLAGS} -Wl,-z,noseparate-code)\n' \
    > "$(dirname "$OUT")/build-vcpkg-variables.cmake"

exec "$ROOT/vcpkg" install \
    --x-manifest-root="$MANIFEST" \
    --overlay-ports="$SRC/Meta/CMake/vcpkg/overlay-ports" \
    --overlay-triplets="$SRC/Meta/CMake/vcpkg/release-triplets" \
    --triplet="$TRIPLET" \
    --host-triplet="$TRIPLET" \
    --x-install-root="$OUT" \
    --x-buildtrees-root="$WORK/bt" \
    --downloads-root="$ROOT/downloads" \
    --binarysource=clear \
    --x-asset-sources="clear;x-script,$WORK/fetch.sh {url} {sha512} {dst};x-block-origin"
