"""LibWeb's generated-source lists: derived, or a capture that outlives its pin?

`Libraries/LibWeb/generated_srcs.bzl` holds the two lists that tell Bazel which
of LibWeb's ~1,390 compile inputs come out of the Ring 1b codegen instead of the
source tree. Its first line said "AUTO-GENERATED by Meta/emit_libweb_bazel.py"
and it was not: no code path in that emitter wrote it. It was a capture of one
pin's answer, hand-maintained, and the header at the top asserted otherwise --
which is worse than an honest hand-written file, because it tells a reader (and
a repin) that re-running the emitter will refresh it.

The 71fb301a repin is what cashed that in. Upstream added five generated headers
(`Bindings/WindowGlobalMixin.h` and four siblings) and four generated .cpp; the
capture named none of them, so `Bindings/Window.h` -- itself generated, and
present in bazel-out -- included a header the cc_library did not declare:

    bazel-out/.../Bindings/Window.h:17:10: fatal error:
        LibWeb/Bindings/WindowGlobalMixin.h: No such file or directory

Note the shape: the missing file EXISTED on disk next to the file that included
it. Only the declaration was stale, and only for the 9 entries that had moved
since the capture. Nothing in the build could have reported it earlier, because
a list of paths is consistent with itself.

Both lists are derivable from facts the emitter already loads -- the CMake
reference's compile list, and codegen.bzl's own `outs` -- so these tests assert
they ARE derived, that the derivation distinguishes a genrule's outputs from its
inputs (the second bug, below), and that the checked-in file matches what the
emitter emits.
"""

import importlib.util
import os
import re
import tempfile

_WS = os.path.join(os.path.dirname(__file__), "..", "examples", "ladybird",
                   "workspace")
_EMIT = os.path.join(_WS, "Meta", "emit_libweb_bazel.py")
_GENERATED_SRCS = os.path.join(_WS, "Libraries", "LibWeb", "generated_srcs.bzl")


def _read(rel):
    with open(os.path.join(_WS, rel)) as f:
        return f.read()


def _load(root=None, model=None):
    """Load the emitter module, optionally pointed at a fixture checkout."""
    # The reference build dir is an env var (a repin needs two side by side), and
    # the fixture's is Build/full71 -- the same name the 71fb301a tree uses.
    os.environ["LADYBIRD_BUILD_REL"] = "Build/full71"
    os.environ["LADYBIRD_BUILD_DIR"] = os.path.join(root or ".", "Build/full71")
    for var, val in (("LADYBIRD_ROOT", root), ("LADYBIRD_MODEL", model)):
        if val:
            os.environ[var] = val
        else:
            os.environ.pop(var, None)
    spec = importlib.util.spec_from_file_location("emit_libweb_bazel", _EMIT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _lists(text):
    """Parse the two lists out of a generated_srcs.bzl body."""
    out = {}
    for name in ("LIBWEB_GENERATED_SRCS", "LIBWEB_GENERATED_HDRS"):
        m = re.search(re.escape(name) + r"\s*=\s*\[(.*?)\n\]", text, re.S)
        assert m, "no %s in generated_srcs.bzl" % name
        out[name] = re.findall(r"'([^']+)'", m.group(1))
    return out


# ---------------------------------------------------------------------------
# A fixture codegen.bzl. Tiny on purpose: it is the CONTRACT between the emitter
# and the genrules, not a copy of the real 1,390-entry file.
#
# It reproduces the two things that made the real file hard: a genrule whose
# `srcs` names checked-in headers (gen_dom_tree reads HTML/TagNames.h), and a
# generated .cpp that is emitted but NOT compiled by CMake (Extra.cpp, standing
# in for WebGL/GLFunctions.cpp).
# ---------------------------------------------------------------------------
CODEGEN_BZL = '''load("@rules_cc//cc:defs.bzl", "cc_library")

def libweb_codegen():
    native.genrule(
        name = 'gen_MediaControlsDOM',
        srcs = ['HTML/MediaControls.html', 'HTML/TagNames.h',
                'HTML/AttributeNames.h', 'SVG/TagNames.h'],
        outs = ['HTML/MediaControlsDOM.h', 'HTML/MediaControlsDOM.cpp'],
        cmd = "true",
    )
    native.genrule(
        name = 'gen_Extra',
        srcs = ['CSS/Thing.json'],
        outs = ['WebGL/Extra.cpp', 'WebGL/Extra.h'],
        cmd = "true",
    )

def libweb_bindings_codegen():
    native.genrule(
        name = 'gen_bindings',
        outs = [
            'Bindings/Window.cpp',
            'Bindings/Window.h',
            # A header with no matching .cpp -- the mixin shape that broke the
            # repin. Bindings/Window.h includes it.
            'Bindings/WindowGlobalMixin.h',
            'Bindings/Fragment.inc',
        ],
        cmd = "true",
    )
'''


def _fixture(compiled=("Bindings/Window.cpp", "HTML/MediaControlsDOM.cpp")):
    """A checkout with a codegen.bzl and a CMake model naming LibWeb's TUs."""
    import json
    d = tempfile.mkdtemp()
    os.makedirs(os.path.join(d, "Libraries/LibWeb"))
    with open(os.path.join(d, "Libraries/LibWeb/codegen.bzl"), "w") as f:
        f.write(CODEGEN_BZL)
    gen = "Build/full71/Libraries/LibWeb/"
    inputs = ["Libraries/LibWeb/DOM/Document.cpp"] + [gen + c for c in compiled]
    model = {"targets": {"LibWeb": {
        "kind": "shared_library", "role": "production", "deps": [],
        "actions": [{"mnemonic": "CppCompile", "inputs": inputs,
                     "arguments": ["-c"]}],
    }}}
    mpath = os.path.join(d, "model.json")
    with open(mpath, "w") as f:
        json.dump(model, f)
    with open(os.path.join(d, ".bazelrc"), "w") as f:
        f.write("build --cxxopt=-std=c++23\n")
    # emit_libweb_bazel imports emit_build_bazel (for rust_dep_labels), which at
    # IMPORT time parses the reference build's build.ninja for the root
    # package's generated sources. An empty one is a valid parse of "no
    # generators", and keeps this fixture about LibWeb rather than about ninja.
    os.makedirs(os.path.join(d, "Build/full71"))
    open(os.path.join(d, "Build/full71/build.ninja"), "w").close()
    return d, mpath


def _emit(compiled=("Bindings/Window.cpp", "HTML/MediaControlsDOM.cpp")):
    d, mpath = _fixture(compiled)
    mod = _load(d, mpath)
    targets = mod.load()
    return mod, _lists(mod.generated_srcs_bzl(targets["LibWeb"],
                                              mod.genrule_outputs()))


def test_a_generated_header_upstream_adds_reaches_the_hdrs_list():
    """THE regression: a new codegen output must appear without anyone editing.

    This is the 71fb301a failure reduced to its bones. The fixture's
    `gen_bindings` produces `Bindings/WindowGlobalMixin.h`, which no generated
    .cpp pairs with and which the compile list therefore never mentions -- so a
    derivation driven by "headers next to compiled sources" would miss it, the
    way the capture did. It is an OUTPUT of a genrule, and that is the only fact
    that makes it includable.
    """
    _, lists = _emit()
    hdrs = lists["LIBWEB_GENERATED_HDRS"]
    assert "Bindings/WindowGlobalMixin.h" in hdrs, hdrs
    # And the same for a non-.h generated header extension: LibWeb's real
    # codegen emits .inc files that TUs #include, and an extension allowlist
    # that forgot one would drop it just as silently.
    assert "Bindings/Fragment.inc" in hdrs, hdrs
    # Now delete the genrule that makes it and the entry goes away rather than
    # outliving the codegen -- the property the capture did not have in either
    # direction.
    d, mpath = _fixture()
    body = CODEGEN_BZL.replace("            'Bindings/WindowGlobalMixin.h',\n", "")
    with open(os.path.join(d, "Libraries/LibWeb/codegen.bzl"), "w") as f:
        f.write(body)
    mod = _load(d, mpath)
    hdrs2 = _lists(mod.generated_srcs_bzl(mod.load()["LibWeb"],
                                          mod.genrule_outputs()))["LIBWEB_GENERATED_HDRS"]
    assert "Bindings/WindowGlobalMixin.h" not in hdrs2, hdrs2


def test_a_genrules_own_inputs_are_not_mistaken_for_its_outputs():
    """The second bug, found while fixing the first, and never yet triggered.

    `genrule_outputs()` used to regex the WHOLE codegen.bzl for anything that
    looked like a path, so a genrule's `srcs` counted as outputs too. Four
    checked-in SOURCE headers (HTML/TagNames.h, HTML/AttributeNames.h,
    SVG/TagNames.h, SVG/AttributeNames.h -- read by generate_dom_tree.py) were
    thereby classified as generated. That is not cosmetic: the generated list is
    the cc_library's hdrs `exclude=`, so those four were dropped from the glob
    over the source tree AND re-added as labels no genrule produces. It never
    broke the build only because the stale capture was consulted instead of this
    answer -- i.e. one bug hid the other, and fixing the capture exposed it.
    """
    _, lists = _emit()
    hdrs = lists["LIBWEB_GENERATED_HDRS"]
    for src_hdr in ("HTML/TagNames.h", "HTML/AttributeNames.h",
                    "SVG/TagNames.h"):
        assert src_hdr not in hdrs, \
            "%s is a genrule INPUT (a checked-in header), not an output" % src_hdr
    assert "HTML/MediaControlsDOM.h" in hdrs, hdrs   # a real out= of that rule


def test_a_generated_cpp_cmake_does_not_compile_is_not_a_src():
    """The lists are not one set, and conflating them would be a link error.

    LibWeb's codegen emits WebGL/GLFunctions.cpp, which the CMake reference does
    not compile into LibWeb. SRCS is therefore the reference's compile list, not
    "every generated .cpp" -- while HDRS is every generated header, because a
    header costs nothing to declare and not declaring one is a hard failure.
    The fixture's WebGL/Extra.cpp stands in for GLFunctions.cpp.
    """
    _, lists = _emit()
    assert "WebGL/Extra.cpp" not in lists["LIBWEB_GENERATED_SRCS"]
    assert "WebGL/Extra.h" in lists["LIBWEB_GENERATED_HDRS"]
    # ...and the pairing is not assumed the other way either: a compiled
    # generated .cpp must be a declared output, or Bazel has no rule making it.
    mod, _ = _emit()
    try:
        mod.generated_srcs_bzl(
            mod.load()["LibWeb"], {"Bindings/Window.cpp"})
    except AssertionError as e:
        assert "not a genrule output" in str(e), e
    else:
        raise AssertionError("a compiled src absent from outs= was accepted")


def test_the_checked_in_generated_srcs_matches_what_the_emitter_emits():
    """The file says AUTO-GENERATED; this is what makes that claim checkable.

    Without it "derived" is a comment. The header line must also name the flag
    that reproduces the file, since the last one named a script that could not
    write it.
    """
    txt = open(_GENERATED_SRCS).read()
    assert txt.startswith("# AUTO-GENERATED by Meta/emit_libweb_bazel.py"), \
        txt.splitlines()[0]
    assert "--generated-srcs" in txt.splitlines()[0], \
        "the AUTO-GENERATED line must name the flag that regenerates the file"
    # Structural: the emitter may not carry either list as data. A capture is
    # exactly what a long run of path literals looks like, so count them -- the
    # emitter legitimately WRITES the string "LIBWEB_GENERATED_SRCS = [" into
    # its output, which is why the assignment itself cannot be the signal.
    code = _read("Meta/emit_libweb_bazel.py")
    code = re.sub(r'""".*?"""', "", code, flags=re.S)
    code = "\n".join(l for l in code.splitlines()
                     if not l.strip().startswith("#"))
    paths = re.findall(r"['\"]([A-Za-z][\w/-]*/[\w/-]+\.(?:cpp|h|inc))['\"]", code)
    assert len(paths) < 10, \
        "the emitter carries %d generated-file paths as data: %s" % (
            len(paths), sorted(set(paths))[:12])
    # The two lists in the checked-in file are sorted and disjoint by extension,
    # which is what lets a reviewer diff two pins' files usefully.
    lists = _lists(txt)
    for name, entries in lists.items():
        assert entries == sorted(entries), "%s is not sorted" % name
        assert len(entries) == len(set(entries)), "%s has duplicates" % name
    assert all(s.endswith(".cpp") for s in lists["LIBWEB_GENERATED_SRCS"])
    mod, _ = _emit()
    assert all(h.endswith(tuple(mod.HDR_EXTS))
               for h in lists["LIBWEB_GENERATED_HDRS"])


def test_every_generated_hdr_is_excluded_from_the_source_glob():
    """Why a wrong entry in HDRS is not merely a missing declaration.

    The cc_library globs `**/*.h` with `exclude = LIBWEB_GENERATED_HDRS`, so the
    list decides, per header, whether the SOURCE tree's copy or the genrule's
    output wins. A generated header missing from the list means a consumer can
    compile against a stale checked-in copy instead of the generated one (silent);
    a source header wrongly IN it means the header vanishes from the library
    (loud, but only for whoever includes it). This pins the exclude= wiring so
    the list keeps that meaning.
    """
    build = _read("Libraries/LibWeb/BUILD.bazel")
    assert "exclude = LIBWEB_GENERATED_HDRS" in build
    assert "+ LIBWEB_GENERATED_HDRS," in build
    # No generated header may ALSO be checked in under the same path: if one is,
    # the exclude= silently changes which file the compiler sees, and that is a
    # thing to know about rather than to resolve by glob precedence.
    hdrs = _lists(open(_GENERATED_SRCS).read())["LIBWEB_GENERATED_HDRS"]
    both = [h for h in hdrs
            if os.path.exists(os.path.join(_WS, "Libraries/LibWeb", h))]
    assert not both, "checked in AND generated: %s" % both


def test_every_file_claiming_to_be_generated_names_a_command_that_makes_it():
    """The general form of this session's bug, applied to all 15 such files.

    `generated_srcs.bzl` was not special. It carried a first line saying
    AUTO-GENERATED by an emitter, and the emitter had no code path that wrote
    it -- so the claim was load-bearing misinformation for every reader and
    every repin, and the cost was found only when the file's content went stale
    under an upstream change.

    The claim is checkable, cheaply, for the whole tree at once. A file that says
    a script generates it must name a script that EXISTS and, if the header names
    a flag, the script must parse that flag. This is deliberately not a
    round-trip test (that needs a CMake reference build, which the suite does not
    have); it is the weaker check that would nonetheless have caught the bug --
    the emitter named there could not have produced the file under any argument.
    """
    generated = []
    for dirpath, dirnames, filenames in os.walk(_WS):
        dirnames[:] = [d for d in dirnames
                       if d not in ("__pycache__", "Build", ".git")]
        for fn in filenames:
            if not fn.endswith((".bzl", ".bazel", ".tsv")):
                continue
            path = os.path.join(dirpath, fn)
            with open(path, errors="replace") as f:
                head = "".join(f.readline() for _ in range(3))
            m = re.search(r'GENERATED by ([\w/]*?([\w-]+\.py))((?: --?[\w-]+)*)',
                          head)
            if m:
                generated.append((os.path.relpath(path, _WS), m.group(2),
                                  m.group(3).split()))
    # If this finds nothing the test is vacuous, which is the failure mode
    # tests/run_all.py exists to reject -- so say so here too.
    assert len(generated) >= 10, generated

    for rel, script, flags in generated:
        cand = [os.path.join(_WS, "Meta", script), os.path.join(_WS, script)]
        found = next((p for p in cand if os.path.exists(p)), None)
        assert found, "%s says it is generated by %s, which does not exist" % (
            rel, script)
        with open(found, errors="replace") as f:
            src = f.read()
        for flag in flags:
            assert flag in src, \
                "%s says `%s %s` generates it, but that script never parses %s" \
                % (rel, script, " ".join(flags), flag)
        # A generator that writes nothing cannot have produced the file. This is
        # the assertion that fails for the original bug: emit_libweb_bazel.py had
        # no branch writing generated_srcs.bzl at all.
        assert re.search(r'\b(print|sys\.stdout\.write|\.write\()', src), \
            "%s names %s, which writes no output" % (rel, script)
