"""The Qt RUNTIME edge: the plugins Qt dlopens must come from the Qt it linked.

Case study finding 40. Ladybird's Bazel build linked Qt from @qt (rules_qt's
qt.local_repo, one SDK found via `qmake -query`) and then, at QApplication
construction, dlopened the QPA platform plugin from the HOST's plugin directory --
because Qt resolves plugins against a prefix baked into libQt6Core, which for an
official SDK is EMPTY, so it falls back to the executable's directory and then the
compiled-in system path. Two Qt builds in one process: a SIGSEGV in
QXcbConnection::initializeScreens where the versions differ, and a silent pass
where they agree (which is why it survived so long in this sandbox).

These tests guard the properties that make the fix a fix rather than a coincidence.
Each one corresponds to something that was actually wrong at some point while
writing it -- the staging depth bug, the missing use_repo, the emitter losing the
data edge on the next regeneration.

The real proof is by removal (hide the host's Qt plugin dir, run with no
LD_LIBRARY_PATH, see the window open); this is the cheap regression guard for it.
"""

import os
import re

_WS = os.path.join(os.path.dirname(__file__), "..", "examples", "ladybird",
                   "workspace")


def _read(rel):
    with open(os.path.join(_WS, rel)) as f:
        return f.read()


def test_plugins_come_from_the_same_sdk_as_the_libraries():
    """The plugin path must be READ from @qt, never written down here.

    This is the whole fix in one assertion: @qt's qtconf.bzl is generated by
    rules_qt from `qmake -query`, so taking QT_INSTALL_PLUGINS from it makes a
    plugin/library version skew unrepresentable. A hardcoded
    /usr/lib/x86_64-linux-gnu/qt6/plugins -- which is what the build effectively
    had, by falling back to it -- is the bug.
    """
    bzl = _read("qt_runtime.bzl")
    assert 'Label("@qt//:qtconf.bzl")' in bzl, \
        "the plugin dir must be read from @qt's own generated qtconf.bzl"
    assert 'values.get("QT_INSTALL_PLUGINS"' in bzl
    # And no ABSOLUTE host plugin path may be a value the code uses. Getting this
    # assertion right took three tries, and the near-misses are worth naming because
    # each is a legitimate mention of such a path:
    #   * comments describing the bug (/usr/lib/x86_64-linux-gnu/qt6/plugins IS the
    #     wrong directory being explained -- a test that cannot tell prose from a
    #     path punishes the explanation),
    #   * _SYSTEM_LIB_DIRS, which lists system lib dirs precisely in order to
    #     RECOGNISE a distro Qt and stage nothing,
    #   * error text and docstrings naming plugins/platforms/libqxcb.so as an
    #     example.
    # What must not appear is an absolute /usr/... path used as a plugin root, so the
    # check is on absolute-path STRING LITERALS outside the system-dir list.
    code = "\n".join([l for l in bzl.splitlines()
                      if not l.lstrip().startswith("#")])
    code = code.split("_SYSTEM_LIB_DIRS = [", 1)
    code = code[0] + (code[1].split("]", 1)[1] if len(code) > 1 else "")
    # (`/plugins/` is the path-COMPONENT matcher from the staging bug below, not a
    # host path -- an absolute host path starts with a real top-level directory.)
    host_roots = ("/usr/", "/opt/", "/home/", "/lib/", "/etc/")
    for literal in re.findall(r'"(/[^"]*)"', code):
        assert not literal.startswith(host_roots), \
            "a hardcoded host path defeats the point: %s" % literal


def test_qt_version_floor_is_checked():
    """finding 40's class: upstream declares a floor and the overlay must check it.

    UI/Qt/CMakeLists.txt has `find_package(Qt6 6.9 REQUIRED COMPONENTS Core
    Widgets)`. CMake refuses an older Qt with a clear message; the Bazel build
    compiled against whatever qmake was first on PATH.
    """
    bzl = _read("qt_runtime.bzl")
    assert "_QT_FLOOR = (6, 9)" in bzl, \
        "the floor must match UI/Qt/CMakeLists.txt's find_package(Qt6 6.9 REQUIRED)"
    # The failure has to name the fix, not just the fact (finding 39's rule).
    msg = bzl.split("qt_plugins: Qt {have} is too old", 1)[1].split("        ))", 1)[0]
    assert "qt6-base-dev" in msg, "the error must name the package to install"
    assert "MODULE.bazel" in msg, "the error must say where the SDK is chosen"
    assert "{have}" in msg and "{prefix}" in msg, \
        "and the Qt it actually found, and where -- 'too old' alone is not actionable"


def test_missing_platform_plugin_is_an_error_not_an_empty_filegroup():
    """A check that cannot fail must not look like one that passed (finding 35).

    An SDK with no platforms/ directory yields an empty staging tree, a clean
    build, and a GUI that cannot start. Same shape as glob(allow_empty = True).
    """
    bzl = _read("qt_runtime.bzl")
    assert '"platforms" not in groups' in bzl, \
        "a Qt with no QPA plugin must be a fetch-time failure"


def test_staging_strips_the_repo_name_not_the_substring():
    """`plugins/` is a substring of `qt_plugins/` -- and that was a real bug.

    Searching for "plugins/" in ../qt_plugins/plugins/platforms/libqxcb.so matches
    inside the REPOSITORY NAME, so everything staged one directory too deep
    (bazel-bin/plugins/plugins/...). It built cleanly and pointed qt.conf at an
    empty tree.
    """
    bzl = _read("qt_runtime.bzl")
    assert 'find("/plugins/")' in bzl, \
        "the match must be on the separated path component, not the substring"


def test_plugins_are_symlinked_not_copied():
    """A plugin finds its own SDK's private libs through RUNPATH $ORIGIN/../../lib.

    $ORIGIN resolves from the object's REAL path, so a symlink keeps that working
    and a copy breaks it -- reintroducing the very bug (the copy then resolves
    libQt6XcbQpa.so.6 from /usr).
    """
    bzl = _read("qt_runtime.bzl")
    assert "ctx.actions.symlink(" in bzl, "the staged plugins must be symlinks"
    assert "ctx.actions.copy" not in bzl


def test_qt_conf_replaces_the_prefix_relatively():
    """Prefix = . is what makes ONE file right in bazel-bin AND in runfiles.

    Setting Prefix at all is what stops /usr being scanned (it REPLACES the
    compiled-in prefix rather than being appended to it). An absolute path would
    be a host escape and would be wrong in one of the two layouts.
    """
    bzl = _read("qt_runtime.bzl")
    written = bzl.split("def _qt_conf_impl", 1)[1]
    assert '"[Paths]"' in written
    assert '"Prefix = ."' in written, "the prefix must be relative to the executable"
    assert '"Plugins = {}".format(ctx.attr.plugins_dir)' in written


def test_the_binary_declares_them_as_runtime_inputs():
    """Staged files nobody depends on are files that are not there in a clean build."""
    build = _read("BUILD.bazel")
    binary = build.split("name = 'ladybird'", 1)[1].split("\n)\n", 1)[0]
    assert "':qt_conf'" in binary and "':qt_plugins'" in binary, \
        "//:ladybird must carry qt.conf and the plugin tree in data"
    assert "'@qt_plugins//:runtime_libs'" in binary, \
        "and the SDK's private libraries as link inputs, or an SDK-bundled ICU " \
        "needs LD_LIBRARY_PATH at run time"
    assert "qt_plugin_tree(" in build and "qt_conf(" in build


def test_the_emitter_generates_that_edge():
    """BUILD.bazel is GENERATED; an edge only in the file is an edge one run deletes.

    The same drift this project keeps finding (finding 37): a hand-appended tail
    the emitter silently truncates on its next run.
    """
    emitter = _read("Meta/emit_build_bazel.py")
    assert "QT_RUNTIME_BLOCK" in emitter and "emit_qt_runtime()" in emitter
    assert 'extra_data=[":qt_conf", ":qt_plugins"]' in emitter
    assert '"@qt_plugins//:runtime_libs"' in emitter, \
        "the private-libs dep must come from QT_MAP's resolution, not by hand"
    assert 'load(":qt_runtime.bzl", "qt_conf", "qt_plugin_tree")' in \
        emitter.split("ALL_LOADS = ", 1)[1], "the generated file needs the load()"


def test_module_bazel_names_the_repo():
    """bzlmod requires every extension-created repo in a use_repo, or it is invisible."""
    mod = _read("MODULE.bazel")
    assert 'use_extension("//:qt_runtime.bzl", "qt_runtime")' in mod
    assert 'use_repo(qt_runtime, "qt_plugins")' in mod
    # Still kklochkov's rules_qt, still discovering the host SDK: this change adds
    # the runtime half, it does not swap the ruleset or pin a different Qt.
    assert 'bazel_dep(name = "rules_qt", version = "2.0.1")' in mod
    assert "qt.local_repo(" in mod


def test_every_plugin_type_is_staged():
    """Not a hand-picked list of the four types the GUI needs today.

    A list drifts, symlinks cost nothing, and a missing input method or native file
    dialog is a defect nobody notices for a month.
    """
    bzl = _read("qt_runtime.bzl")
    staging = bzl.split("def _qt_plugins_impl", 1)[1].split(
        "qt_plugins = repository_rule(", 1)[0]
    assert "root.readdir()" in staging, "the plugin types must be discovered"
    for hardcoded in ('"platformthemes"', '"styles"', '"imageformats"'):
        assert hardcoded not in staging, \
            "a hardcoded plugin type list is the thing to avoid (%s)" % hardcoded


def test_repo_rule_is_local():
    """The SDK is a host path; a cached repo would survive changing it.

    rules_qt's own qt.local_repo is local = True for the same reason.
    """
    bzl = _read("qt_runtime.bzl")
    rule = bzl.split("qt_plugins = repository_rule(", 1)[1].split(")\n", 1)[0]
    assert "local = True" in rule


TESTS = [v for k, v in sorted(globals().items()) if k.startswith("test_")]

if __name__ == "__main__":
    for t in TESTS:
        t()
        print("ok", t.__name__)
    print("%d passed" % len(TESTS))
