"""The Qt RUNTIME edge: the plugins Qt dlopens must come from the Qt it linked.

Case study finding 40. Ladybird's Bazel build linked Qt from @qt (rules_qt's
qt.local_repo, one SDK found via `qmake -query`) and then, at QApplication
construction, dlopened the QPA platform plugin from the HOST's plugin directory --
because Qt resolves plugins against a prefix baked into libQt6Core, which for an
official SDK is EMPTY, so it falls back to the executable's directory and then the
compiled-in system path. Two Qt builds in one process: a SIGSEGV in
QXcbConnection::initializeScreens where the versions differ, and a silent pass
where they agree (which is why it survived so long in this sandbox).

These tests guard the properties that make the fix a fix rather than a coincidence.
Each one corresponds to something that was actually wrong at some point while
writing it -- the staging depth bug, the missing use_repo, the emitter losing the
data edge on the next regeneration.

The real proof is by removal (hide the host's Qt plugin dir, run with no
LD_LIBRARY_PATH, see the window open); this is the cheap regression guard for it.
"""

import os
import re

_WS = os.path.join(os.path.dirname(__file__), "..", "examples", "ladybird",
                   "workspace")


def _read(rel):
    with open(os.path.join(_WS, rel)) as f:
        return f.read()


def test_plugins_come_from_the_same_sdk_as_the_libraries():
    """The plugin path must be READ from @qt, never written down here.

    This is the whole fix in one assertion: @qt's qtconf.bzl is generated by
    rules_qt from `qmake -query`, so taking QT_INSTALL_PLUGINS from it makes a
    plugin/library version skew unrepresentable. A hardcoded
    /usr/lib/x86_64-linux-gnu/qt6/plugins -- which is what the build effectively
    had, by falling back to it -- is the bug.
    """
    bzl = _read("qt_runtime.bzl")
    assert 'Label("@qt//:qtconf.bzl")' in bzl, \
        "the plugin dir must be read from @qt's own generated qtconf.bzl"
    assert 'values.get("QT_INSTALL_PLUGINS"' in bzl
    # And no ABSOLUTE host plugin path may be a value the code uses. Getting this
    # assertion right took three tries, and the near-misses are worth naming because
    # each is a legitimate mention of such a path:
    #   * comments describing the bug (/usr/lib/x86_64-linux-gnu/qt6/plugins IS the
    #     wrong directory being explained -- a test that cannot tell prose from a
    #     path punishes the explanation),
    #   * _SYSTEM_LIB_DIRS, which lists system lib dirs precisely in order to
    #     RECOGNISE a distro Qt and stage nothing,
    #   * error text and docstrings naming plugins/platforms/libqxcb.so as an
    #     example.
    # What must not appear is an absolute /usr/... path used as a plugin root, so the
    # check is on absolute-path STRING LITERALS outside the system-dir list.
    code = "\n".join([l for l in bzl.splitlines()
                      if not l.lstrip().startswith("#")])
    code = code.split("_SYSTEM_LIB_DIRS = [", 1)
    code = code[0] + (code[1].split("]", 1)[1] if len(code) > 1 else "")
    # (`/plugins/` is the path-COMPONENT matcher from the staging bug below, not a
    # host path -- an absolute host path starts with a real top-level directory.)
    host_roots = ("/usr/", "/opt/", "/home/", "/lib/", "/etc/")
    for literal in re.findall(r'"(/[^"]*)"', code):
        assert not literal.startswith(host_roots), \
            "a hardcoded host path defeats the point: %s" % literal


def test_qt_version_floor_is_checked():
    """finding 40's class: upstream declares a floor and the overlay must check it.

    UI/Qt/CMakeLists.txt has `find_package(Qt6 6.9 REQUIRED COMPONENTS Core
    Widgets)`. CMake refuses an older Qt with a clear message; the Bazel build
    compiled against whatever qmake was first on PATH.
    """
    bzl = _read("qt_runtime.bzl")
    assert "_QT_FLOOR = (6, 9)" in bzl, \
        "the floor must match UI/Qt/CMakeLists.txt's find_package(Qt6 6.9 REQUIRED)"
    # The failure has to name the fix, not just the fact (finding 39's rule).
    msg = bzl.split("qt_plugins: Qt {have} is too old", 1)[1].split("        ))", 1)[0]
    assert "qt6-base-dev" in msg, "the error must name the package to install"
    assert "MODULE.bazel" in msg, "the error must say where the SDK is chosen"
    assert "{have}" in msg and "{prefix}" in msg, \
        "and the Qt it actually found, and where -- 'too old' alone is not actionable"


def test_missing_platform_plugin_is_an_error_not_an_empty_filegroup():
    """A check that cannot fail must not look like one that passed (finding 35).

    An SDK with no platforms/ directory yields an empty staging tree, a clean
    build, and a GUI that cannot start. Same shape as glob(allow_empty = True).
    """
    bzl = _read("qt_runtime.bzl")
    assert '"platforms" not in groups' in bzl, \
        "a Qt with no QPA plugin must be a fetch-time failure"


def test_staging_strips_the_repo_name_not_the_substring():
    """`plugins/` is a substring of `qt_plugins/` -- and that was a real bug.

    Searching for "plugins/" in ../qt_plugins/plugins/platforms/libqxcb.so matches
    inside the REPOSITORY NAME, so everything staged one directory too deep
    (bazel-bin/plugins/plugins/...). It built cleanly and pointed qt.conf at an
    empty tree.
    """
    bzl = _read("qt_runtime.bzl")
    assert 'find("/plugins/")' in bzl, \
        "the match must be on the separated path component, not the substring"


def test_plugins_are_symlinked_not_copied():
    """A plugin finds its own SDK's private libs through RUNPATH $ORIGIN/../../lib.

    $ORIGIN resolves from the object's REAL path, so a symlink keeps that working
    and a copy breaks it -- reintroducing the very bug (the copy then resolves
    libQt6XcbQpa.so.6 from /usr).
    """
    bzl = _read("qt_runtime.bzl")
    assert "ctx.actions.symlink(" in bzl, "the staged plugins must be symlinks"
    assert "ctx.actions.copy" not in bzl


def test_qt_conf_replaces_the_prefix_relatively():
    """Prefix = . is what makes ONE file right in bazel-bin AND in runfiles.

    Setting Prefix at all is what stops /usr being scanned (it REPLACES the
    compiled-in prefix rather than being appended to it). An absolute path would
    be a host escape and would be wrong in one of the two layouts.
    """
    bzl = _read("qt_runtime.bzl")
    written = bzl.split("def _qt_conf_impl", 1)[1]
    assert '"[Paths]"' in written
    assert '"Prefix = ."' in written, "the prefix must be relative to the executable"
    assert '"Plugins = {}".format(ctx.attr.plugins_dir)' in written


def test_the_binary_declares_them_as_runtime_inputs():
    """Staged files nobody depends on are files that are not there in a clean build."""
    build = _read("BUILD.bazel")
    binary = build.split("name = 'ladybird'", 1)[1].split("\n)\n", 1)[0]
    assert "':qt_conf'" in binary and "':qt_plugins'" in binary, \
        "//:ladybird must carry qt.conf and the plugin tree in data"
    assert "'@qt_plugins//:runtime_libs'" in binary, \
        "and the SDK's private libraries as link inputs, or an SDK-bundled ICU " \
        "needs LD_LIBRARY_PATH at run time"
    assert "qt_plugin_tree(" in build and "qt_conf(" in build


def test_the_emitter_generates_that_edge():
    """BUILD.bazel is GENERATED; an edge only in the file is an edge one run deletes.

    The same drift this project keeps finding (finding 37): a hand-appended tail
    the emitter silently truncates on its next run.
    """
    emitter = _read("Meta/emit_build_bazel.py")
    assert "QT_RUNTIME_BLOCK" in emitter and "emit_qt_runtime()" in emitter
    assert 'extra_data=[":qt_conf", ":qt_plugins"]' in emitter
    assert '"@qt_plugins//:runtime_libs"' in emitter, \
        "the private-libs dep must come from qt_label()'s resolution, not by hand"
    assert 'load(":qt_runtime.bzl", "qt_conf", "qt_plugin_tree")' in \
        emitter.split("ALL_LOADS = ", 1)[1], "the generated file needs the load()"


def test_module_bazel_names_the_repo():
    """bzlmod requires every extension-created repo in a use_repo, or it is invisible."""
    mod = _read("MODULE.bazel")
    assert 'use_extension("//:qt_runtime.bzl", "qt_runtime")' in mod
    assert 'use_repo(qt_runtime, "qt_plugins")' in mod
    # Still kklochkov's rules_qt, still discovering the host SDK: this change adds
    # the runtime half, it does not swap the ruleset or pin a different Qt.
    assert 'bazel_dep(name = "rules_qt", version = "2.0.1")' in mod
    assert "qt.local_repo(" in mod


def test_every_plugin_type_is_staged():
    """Not a hand-picked list of the four types the GUI needs today.

    A list drifts, symlinks cost nothing, and a missing input method or native file
    dialog is a defect nobody notices for a month.
    """
    bzl = _read("qt_runtime.bzl")
    staging = bzl.split("def _qt_plugins_impl", 1)[1].split(
        "qt_plugins = repository_rule(", 1)[0]
    assert "root.readdir()" in staging, "the plugin types must be discovered"
    for hardcoded in ('"platformthemes"', '"styles"', '"imageformats"'):
        assert hardcoded not in staging, \
            "a hardcoded plugin type list is the thing to avoid (%s)" % hardcoded


def test_repo_rule_is_local():
    """The SDK is a host path; a cached repo would survive changing it.

    rules_qt's own qt.local_repo is local = True for the same reason.
    """
    bzl = _read("qt_runtime.bzl")
    rule = bzl.split("qt_plugins = repository_rule(", 1)[1].split(")\n", 1)[0]
    assert "local = True" in rule



def test_a_qt_module_upstream_starts_requiring_resolves_without_an_edit():
    """The Qt mapping is a RULE, because the three-entry table went stale.

    CMake names Qt targets Qt6<Module>; rules_qt names one cc_library per module
    of the discovered SDK as @qt//:Qt<Module>. That is a rename, and it was
    written as a dict of the three modules Ladybird used when it was measured
    (Core, Gui, Widgets). At 71fb301a upstream turned Qt6::Positioning from
    OPTIONAL to REQUIRED for UI/Qt/GeolocationProviderQt.cpp; the dict had no
    key, so the dep became an UNKNOWN and //:ladybird failed to compile with
    "QGeoPositionInfo: No such file or directory".

    A table of the deps a project has today cannot express "and whatever it needs
    tomorrow", so this asserts the derivation -- including that a NON-Qt name
    still falls through (returning a label for it would put a nonexistent
    @qt//:X in the build) .
    """
    import importlib.util
    os.environ["LADYBIRD_ROOT"] = _WS
    spec = importlib.util.spec_from_file_location(
        "_ebb_src", os.path.join(_WS, "Meta", "emit_build_bazel.py"))
    src = _read("Meta/emit_build_bazel.py")
    # Exec just the function, not the module: emit_build_bazel does real work at
    # import time (it parses the reference build's build.ninja), and this is a
    # pure string rule.
    ns = {}
    body = "def qt_label" + src.split("def qt_label", 1)[1].split("\ndef ", 1)[0]
    exec(body, ns)
    qt_label = ns["qt_label"]
    assert qt_label("Qt6Core") == "@qt//:QtCore"
    assert qt_label("Qt6Gui") == "@qt//:QtGui"
    assert qt_label("Qt6Widgets") == "@qt//:QtWidgets"
    # THE regression: the module nobody wrote down.
    assert qt_label("Qt6Positioning") == "@qt//:QtPositioning"
    # And modules Ladybird does not use today, to show the rule is not a longer list.
    assert qt_label("Qt6Network") == "@qt//:QtNetwork"
    assert qt_label("Qt6Multimedia") == "@qt//:QtMultimedia"
    # Not Qt: must NOT resolve, so it is reported as UNKNOWN rather than becoming
    # a label for a target that does not exist.
    for other in ("xkbcommon", "glib-2.0", "OpenGL", "Qt6", "vulkan", ""):
        assert qt_label(other) is None, other
    # Structural: no dict may map Qt module names to labels again.
    assert "QT_MAP" not in src, "the Qt table is back"


def test_the_moc_list_follows_what_cmake_compiles_not_a_name():
    """A conditionally-compiled Q_OBJECT header, decided by measurement.

    moc_headers() returns the UI/Qt headers CMake's AUTOMOC would moc. It ended
    with a hardcoded `not h.endswith("GeolocationProviderQt.h")`, justified in a
    docstring by "Qt6::Positioning is not found in this configuration" -- a fact
    about the machine that captured it. At 71fb301a Positioning is required and
    CMake compiles GeolocationProviderQt.cpp, so the exclusion silently dropped a
    real moc target. Wrong in both directions: moc'ing a header CMake does not is
    a target only Bazel builds; skipping one it does is a missing vtable at link.

    The condition is now "does the reference build compile the sibling .cpp",
    which is in the model, so it cannot disagree with CMake.
    """
    src = _read("Meta/emit_build_bazel.py")
    fn = src.split("def moc_headers", 1)[1].split("\ndef ", 1)[0]
    assert "GeolocationProviderQt" not in fn.split('"""', 2)[-1],         "moc_headers filters by FILE NAME again"
    assert "compiled" in fn and "CppCompile" in fn,         "the filter must read the reference build's compile list"
    # And the generated file reflects it: the header is moc'd at this pin.
    build = _read("BUILD.bazel")
    moc = build.split("qt_cc_moc(", 1)[1].split(")", 1)[0]
    assert "UI/Qt/GeolocationProviderQt.h" in moc, moc
    # ...paired with the dep that makes it compile, or the moc output does not build.
    assert "'@qt//:QtPositioning'" in build


def test_a_dropped_absolute_include_root_is_reported_not_silently_skipped():
    """The emitter must not hide the difference between its input and .bazelrc.

    An absolute include root (/usr/include/glib-2.0) cannot be a per-target
    copt -- Bazel rejects a path outside the execution root even as -isystem --
    so the emitter drops it and .bazelrc carries it globally as
    CPLUS_INCLUDE_PATH. The drop was a bare `continue`, which means a root CMake
    compiles with and .bazelrc lacks produces NO output at all.

    That is how the last failure of this repin happened, and I caused it: having
    just fixed four hand-copied facts, I hand-copied three of glib's roots out of
    the model and missed the rest. The build failed ~3,800 actions later on
    `UI/Qt/ExternalURLHandler.cpp:19: fatal error: gio/gdesktopappinfo.h: No such
    file or directory` -- gio-unix-2.0 is a separate root from glib-2.0, and
    blkid/libmount/sysprof-6 arrive transitively through glib's pkg-config.
    Re-running the emitter with the check in place named all four at once.

    Deliberately a WARNING, not a failure: which host escapes are acceptable is a
    judgement (README gap 3), and Qt's roots are correctly absent because
    rules_qt carries them on the dep edge. What is not a judgement is whether the
    emitter says anything at all.
    """
    src = _read("Meta/emit_build_bazel.py")
    # The bare skip is gone.
    assert "record_host_include(i)" in src, \
        "absolute include roots are dropped without being recorded"
    assert "def report_host_includes" in src and "report_host_includes()" in \
        src.split("def report_host_includes", 1)[1], \
        "the shortfall is collected but never reported"
    # The roots that ride on a dep edge must be exempt, or the warning cries wolf
    # about Qt on every run and gets ignored -- which is how a real one hides.
    exempt = src.split("HOST_INCLUDE_EXEMPT = ", 1)[1].split(")", 1)[0]
    assert "qt6" in exempt and "vcpkg_installed" in exempt, exempt

    # And .bazelrc actually carries the six roots this configuration needs, glib's
    # non-obvious ones included. This is the assertion that would have failed
    # while the build was broken.
    rc = _read("bazelrc.txt")
    paths = set()
    for m in re.finditer(r"CPLUS_INCLUDE_PATH=(\S+)", rc):
        paths |= set(m.group(1).split(":"))
    for root in ("/usr/include/libdrm", "/usr/include/glib-2.0",
                 "/usr/lib/x86_64-linux-gnu/glib-2.0/include",
                 "/usr/include/gio-unix-2.0", "/usr/include/blkid",
                 "/usr/include/libmount", "/usr/include/sysprof-6"):
        assert root in paths, "%s missing from CPLUS_INCLUDE_PATH" % root
    # Target and exec configs must agree: a root in one and not the other is the
    # finding-26 skew, and here it would mean a genrule tool that cannot compile.
    envs = re.findall(r"--(?:host_)?action_env=CPLUS_INCLUDE_PATH=(\S+)", rc)
    assert len(envs) == 2, envs
    assert envs[0] == envs[1], "target and exec CPLUS_INCLUDE_PATH differ"

TESTS = [v for k, v in sorted(globals().items()) if k.startswith("test_")]

if __name__ == "__main__":
    for t in TESTS:
        t()
        print("ok", t.__name__)
    print("%d passed" % len(TESTS))


def test_every_qt_module_the_build_links_is_preflighted_with_its_package():
    """A Qt module the HOST lacks must be named here, not by Bazel's output base.

    rules_qt's qt.local_repo DERIVES its cc_library targets by listing the host
    Qt's lib directory (`_create_libs_symlinks`, qt_local_repo.bzl), so a module
    the host does not have is simply never declared. What the reader then sees is:

      ERROR: .../external/rules_qt++qt+qt/BUILD.bazel: no such target
      '@@rules_qt++qt+qt//:QtPositioning': target 'QtPositioning' not declared in
      package '' ... and referenced by '//:ladybird'

    Ulf hit exactly that. It says nothing about Qt, nothing about apt, and points
    at a generated file in an output base that the reader did not write and cannot
    fix. Same class as finding 38 (an unpinned host tool) and as the four failed
    configures of the 71fb301a repin: a host probe whose absence is reported as a
    defect in your own code.

    The version FLOOR check next to it was already the right idea with the wrong
    scope -- "is the SDK new enough" but never "does the SDK have the parts we
    link". Both are properties of the discovered SDK.

    This test is the anti-drift half: _QT_MODULES is an INDEPENDENT statement of
    what the build needs (deriving it from BUILD.bazel would only prove the
    generator agrees with itself), so it can go stale exactly the way the qt_label
    table did. Asserting the two agree is what catches a Qt module appearing in a
    future repin without a preflight entry.
    """
    rt = _read("qt_runtime.bzl")
    build = _read("BUILD.bazel")

    # What the build actually links.
    linked = set(re.findall(r"@qt//:(Qt\w+)", build))
    assert linked, "no @qt//:Qt* deps in BUILD.bazel -- did the label scheme change?"

    # What the preflight knows about.
    block = rt.split("_QT_MODULES = {", 1)[1].split("}", 1)[0]
    preflighted = dict(re.findall(r'"(Qt\w+)":\s*"([^"]+)"', block))
    assert preflighted, "_QT_MODULES is empty or unparseable"

    missing = sorted(linked - set(preflighted))
    assert not missing, (
        "these Qt modules are linked by BUILD.bazel but have no _QT_MODULES entry, "
        "so a host without them gets Bazel's 'no such target' error naming a "
        "generated BUILD file instead of the apt package: %s" % missing)

    # Every entry must name a package, or the message cannot tell anyone what to do.
    for mod, pkg in sorted(preflighted.items()):
        assert pkg and not pkg.startswith("Qt"), \
            "%s maps to %r, which is not a package name" % (mod, pkg)

    # The regression that motivated this: Positioning became REQUIRED at 71fb301a.
    assert preflighted.get("QtPositioning") == "qt6-positioning-dev", \
        "QtPositioning must map to the package that ships libQt6Positioning.so"


def test_the_module_preflight_reads_the_same_libs_dir_rules_qt_derives_from():
    """The check must ask the question qt.local_repo will answer, not a proxy.

    A repository rule cannot query another repo's targets, so "will @qt declare
    QtPositioning?" has to be answered from the same input qt.local_repo uses:
    QT_INSTALL_LIBS, listed for libQt<major><Module>.so*. Anything else (asking
    for the target, probing a header, trusting the version) can disagree with what
    rules_qt actually does, which would give a false pass or a false failure.

    Verified against real Bazel both ways: a prefix with libQt6Positioning.so*
    removed fails with the apt package named, and the same prefix with it restored
    resolves @qt_plugins//:runtime_libs.
    """
    rt = _read("qt_runtime.bzl")
    impl = rt.split("def _qt_plugins_impl", 1)[1]
    assert "QT_INSTALL_LIBS" in impl, \
        "the module preflight does not read QT_INSTALL_LIBS, the dir rules_qt derives from"
    # Must be the same name-mangling as _create_lib_name: first dot-field, prefix
    # stripped -- libQt6Positioning.so.6.10.2 is QtPositioning.
    assert 'split(".")' in impl, \
        "libQt6Positioning.so.6.10.2 must reduce to QtPositioning like _create_lib_name does"
    # The failure has to be actionable: package names and the cache caveat.
    fail_msg = impl.split("missing {n} module", 1)[1].split('))', 1)[0] \
        if "missing {n} module" in impl else ""
    assert "apt install" in fail_msg, "the failure does not say how to install the module"
    assert "sync --configure" in fail_msg or "clean --expunge" in fail_msg, \
        ("the failure does not mention that @qt is cached, so a reader who installs "
         "the package and re-runs can get the same error and conclude it did not work")
