# AUTO-GENERATED by Meta/emit_cargo_bazel.py — do not edit.
load(":cargo.bzl", "cargo_binary", "cargo_crate", "cargo_lib", "rust_sysroot")
load(":cargo_index.bzl", "CARGO_CRATE_FILES", "CARGO_CRATE_SPECS")

# Ladybird's 10 production Rust crates and flapc, BUILT BY BAZEL from the
# 154 crates.io crates Bazel fetched -- replacing the prebuilt 260 MB
# librust_combined.a that was copied out of Build/full/cargo/, the `ar -M`
# merge that produced it (README step 1b), and the reference build's flapc
# binary. Nothing here names Build/full.
#
# Every attribute comes from CARGO_CRATE_SPECS, which
# Meta/emit_cargo_bazel.py parses out of import_rust_crate() in CMake, so a
# feature or header list cannot drift from the reference build without the
# emitter's --report saying so.

def cargo_ring():
    # The pinned toolchain (rust-toolchain.toml says 1.96.1), assembled from
    # three fetched components into one tree rustc can find itself in.
    rust_sysroot(
        name = "rust_sysroot",
        components = [
            '@rust_cargo_1_96_1//:tree',
            '@rust_rust_std_1_96_1//:tree',
            '@rust_rustc_1_96_1//:tree',
        ],
    )

    # The crate sources: ONE list for all the crates, because they are one
    # cargo WORKSPACE. Each of them path-depends on
    # Libraries/RustAllocator.rs and several are path-dependencies of each
    # other, so cargo resolves the whole workspace whichever crate you ask
    # for. Over-declaring costs a rebuild of 11 crates when any .rs changes;
    # under-declaring silently reuses a stale archive. The trade is the right
    # way round, and it is real debt: per-crate source sets need the
    # path-dependency graph read out of the manifests.
    crate_srcs = native.glob(['Cargo.toml', 'Cargo.lock', 'rust-toolchain.toml', 'Libraries/RustAllocator.rs', 'Libraries/*/Rust/**', 'Libraries/LibJS/BytecodeDef/**'], allow_empty = False) + ['//Libraries/LibWeb:rust_crate_srcs']

    cargo_crate(
        name = 'libgfx_rust',
        crate = 'libgfx_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['libgfx_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['libgfx_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['libgfx_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['libgfx_rust']["manifest"],
        srcs = crate_srcs,
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'libgfx_rust_lib',
        crate = ':libgfx_rust',
    )

    cargo_crate(
        name = 'libjs_rust',
        crate = 'libjs_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['libjs_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['libjs_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['libjs_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['libjs_rust']["manifest"],
        # Build-script inputs, taken from the reference build's DEPFILES
        # rather than from reading build.rs: this crate's build script
        # generates Rust from these, so they are compile inputs.
        srcs = crate_srcs + ['Libraries/LibJS/Bytecode/Bytecode.def'],
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'libjs_rust_lib',
        crate = ':libjs_rust',
    )

    cargo_crate(
        name = 'libregex_rust',
        crate = 'libregex_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['libregex_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['libregex_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['libregex_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['libregex_rust']["manifest"],
        srcs = crate_srcs,
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'libregex_rust_lib',
        crate = ':libregex_rust',
    )

    cargo_crate(
        name = 'libtextcodec_rust',
        crate = 'libtextcodec_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['libtextcodec_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['libtextcodec_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['libtextcodec_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['libtextcodec_rust']["manifest"],
        srcs = crate_srcs,
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'libtextcodec_rust_lib',
        crate = ':libtextcodec_rust',
    )

    cargo_crate(
        name = 'libunicode_rust',
        crate = 'libunicode_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['libunicode_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['libunicode_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['libunicode_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['libunicode_rust']["manifest"],
        srcs = crate_srcs,
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'libunicode_rust_lib',
        crate = ':libunicode_rust',
    )

    cargo_crate(
        name = 'liburl_rust',
        crate = 'liburl_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['liburl_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['liburl_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['liburl_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['liburl_rust']["manifest"],
        srcs = crate_srcs,
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'liburl_rust_lib',
        crate = ':liburl_rust',
    )

    cargo_crate(
        name = 'libweb_content_blocker_rust',
        crate = 'libweb_content_blocker_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['libweb_content_blocker_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['libweb_content_blocker_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['libweb_content_blocker_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['libweb_content_blocker_rust']["manifest"],
        srcs = crate_srcs,
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'libweb_content_blocker_rust_lib',
        crate = ':libweb_content_blocker_rust',
    )

    cargo_crate(
        name = 'libweb_css_rust',
        crate = 'libweb_css_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['libweb_css_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['libweb_css_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['libweb_css_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['libweb_css_rust']["manifest"],
        srcs = crate_srcs,
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'libweb_css_rust_lib',
        crate = ':libweb_css_rust',
    )

    cargo_crate(
        name = 'libweb_layout_rust',
        crate = 'libweb_layout_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['libweb_layout_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['libweb_layout_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['libweb_layout_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['libweb_layout_rust']["manifest"],
        srcs = crate_srcs,
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'libweb_layout_rust_lib',
        crate = ':libweb_layout_rust',
    )

    cargo_crate(
        name = 'libweb_rust',
        crate = 'libweb_rust',
        crates = CARGO_CRATE_FILES,
        crate_features = CARGO_CRATE_SPECS['libweb_rust']["features"],
        ffi_headers = CARGO_CRATE_SPECS['libweb_rust']["ffi_headers"],
        ffi_prefix = CARGO_CRATE_SPECS['libweb_rust']["ffi_prefix"],
        manifest = CARGO_CRATE_SPECS['libweb_rust']["manifest"],
        srcs = crate_srcs,
        sysroot = ":rust_sysroot",
    )

    # The consumable target: this crate's archive to link and this
    # crate's generated FFI headers to include, one for one with
    # CMake's per-library edge. NOT a shared --start-group over all
    # ten archives: the crates have no true cross-crate symbol
    # references (measured: 0), the shared symbols are each crate's
    # own copy of rust-std, and a group makes ld satisfy one crate's
    # std symbol from another crate's object -- dragging that
    # crate's C++ FFI into a target that never linked it. See the
    # block comment in cargo.bzl.
    cargo_lib(
        name = 'libweb_rust_lib',
        crate = ':libweb_rust',
    )

    # flapc, the Flap-DSL -> interpreter-assembly compiler. Its workspace is
    # `exclude`d from the root one and has its own lock with exactly 3
    # packages (flapc, in-tree bytecode_def, and smallvec from crates.io
    # pinned =1.15.1 -- the same version AND checksum the big workspace pins,
    # so it is the same fetch rule, not a second one).
    cargo_binary(
        name = "flapc",
        bin = "flapc",
        crate = "flapc",
        crates = CARGO_CRATE_FILES,
        manifest = "Libraries/LibJS/Flap/Cargo.toml",
        srcs = native.glob(['Libraries/LibJS/Flap/Cargo.toml', 'Libraries/LibJS/Flap/Cargo.lock', 'Libraries/LibJS/Flap/src/**', 'Libraries/LibJS/Flap/benches/**', 'Libraries/LibJS/Flap/tests/**', 'Libraries/LibJS/BytecodeDef/**', 'Libraries/LibJS/Bytecode/Bytecode.def', 'Libraries/LibJS/Interpreter/interpreter.flap', 'rust-toolchain.toml'], allow_empty = False),
        sysroot = ":rust_sysroot",
    )
