# AUTO-GENERATED by Meta/emit_cargo_bazel.py — do not edit.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# 155 crates.io crates, every sha256 lifted verbatim out of the two
# Cargo.lock files. Nothing is re-hashed here and nothing was captured:
# the lock file is the pin and the URL is a function of (name, version),
# so this regenerates with no cargo, no network and no CMake.
#
# A `.crate` IS a gzipped tar whose single top-level dir is
# <name>-<version>/, so http_archive unpacks it directly with
# strip_prefix and an explicit type="tgz" (the .crate extension is
# not one http_archive recognises) -- no custom repository rule and no
# per-crate BUILD file: the vendor directory cargo wants is assembled
# by a normal build action later (see cargo.bzl), not at fetch time.

def cargo_crates():
    http_archive(
        name = 'crate_adblock_0_12_5',
        urls = ['https://static.crates.io/crates/adblock/adblock-0.12.5.crate'],
        sha256 = 'db6fe7702c798519299bcbe011ff6f1dc9e3aedc1f3171178cddf71e1736bf95',
        strip_prefix = 'adblock-0.12.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_addr_0_15_6',
        urls = ['https://static.crates.io/crates/addr/addr-0.15.6.crate'],
        sha256 = 'a93b8a41dbe230ad5087cc721f8d41611de654542180586b315d9f4cf6b72bef',
        strip_prefix = 'addr-0.15.6',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_aho_corasick_1_1_4',
        urls = ['https://static.crates.io/crates/aho-corasick/aho-corasick-1.1.4.crate'],
        sha256 = 'ddd31a130427c27518df266943a5308ed92d4b226cc639f5a8f1002816174301',
        strip_prefix = 'aho-corasick-1.1.4',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_allocator_api2_0_2_21',
        urls = ['https://static.crates.io/crates/allocator-api2/allocator-api2-0.2.21.crate'],
        sha256 = '683d7910e743518b0e34f1186f92494becacb047c7b6bf616c96772180fef923',
        strip_prefix = 'allocator-api2-0.2.21',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_anstream_1_0_0',
        urls = ['https://static.crates.io/crates/anstream/anstream-1.0.0.crate'],
        sha256 = '824a212faf96e9acacdbd09febd34438f8f711fb84e09a8916013cd7815ca28d',
        strip_prefix = 'anstream-1.0.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_anstyle_1_0_14',
        urls = ['https://static.crates.io/crates/anstyle/anstyle-1.0.14.crate'],
        sha256 = '940b3a0ca603d1eade50a4846a2afffd5ef57a9feac2c0e2ec2e14f9ead76000',
        strip_prefix = 'anstyle-1.0.14',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_anstyle_parse_1_0_0',
        urls = ['https://static.crates.io/crates/anstyle-parse/anstyle-parse-1.0.0.crate'],
        sha256 = '52ce7f38b242319f7cabaa6813055467063ecdc9d355bbb4ce0c68908cd8130e',
        strip_prefix = 'anstyle-parse-1.0.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_anstyle_query_1_1_5',
        urls = ['https://static.crates.io/crates/anstyle-query/anstyle-query-1.1.5.crate'],
        sha256 = '40c48f72fd53cd289104fc64099abca73db4166ad86ea0b4341abe65af83dadc',
        strip_prefix = 'anstyle-query-1.1.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_anstyle_wincon_3_0_11',
        urls = ['https://static.crates.io/crates/anstyle-wincon/anstyle-wincon-3.0.11.crate'],
        sha256 = '291e6a250ff86cd4a820112fb8898808a366d8f9f58ce16d1f538353ad55747d',
        strip_prefix = 'anstyle-wincon-3.0.11',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_anyhow_1_0_102',
        urls = ['https://static.crates.io/crates/anyhow/anyhow-1.0.102.crate'],
        sha256 = '7f202df86484c868dbad7eaa557ef785d5c66295e41b460ef922eca0723b842c',
        strip_prefix = 'anyhow-1.0.102',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_arbitrary_1_4_2',
        urls = ['https://static.crates.io/crates/arbitrary/arbitrary-1.4.2.crate'],
        sha256 = 'c3d036a3c4ab069c7b410a2ce876bd74808d2d0888a82667669f8e783a898bf1',
        strip_prefix = 'arbitrary-1.4.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_arrayvec_0_7_6',
        urls = ['https://static.crates.io/crates/arrayvec/arrayvec-0.7.6.crate'],
        sha256 = '7c02d123df017efcdfbd739ef81735b36c5ba83ec3c59c80a9d7ecc718f92e50',
        strip_prefix = 'arrayvec-0.7.6',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_autocfg_1_5_0',
        urls = ['https://static.crates.io/crates/autocfg/autocfg-1.5.0.crate'],
        sha256 = 'c08606f8c3cbf4ce6ec8e28fb0014a2c086708fe954eaa885384a6165172e7e8',
        strip_prefix = 'autocfg-1.5.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_base64_0_22_1',
        urls = ['https://static.crates.io/crates/base64/base64-0.22.1.crate'],
        sha256 = '72b3254f16251a8381aa12e40e3c4d2f0199f8c6508fbecb9d91f575e0fbb8c6',
        strip_prefix = 'base64-0.22.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_bitflags_2_11_0',
        urls = ['https://static.crates.io/crates/bitflags/bitflags-2.11.0.crate'],
        sha256 = '843867be96c8daad0d758b57df9392b6d8d271134fce549de6ce169ff98a92af',
        strip_prefix = 'bitflags-2.11.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_bumpalo_3_20_2',
        urls = ['https://static.crates.io/crates/bumpalo/bumpalo-3.20.2.crate'],
        sha256 = '5d20789868f4b01b2f2caec9f5c4e0213b41e3e5702a50157d699ae31ced2fcb',
        strip_prefix = 'bumpalo-3.20.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_calendrical_calculations_0_2_4',
        urls = ['https://static.crates.io/crates/calendrical_calculations/calendrical_calculations-0.2.4.crate'],
        sha256 = '5abbd6eeda6885048d357edc66748eea6e0268e3dd11f326fff5bd248d779c26',
        strip_prefix = 'calendrical_calculations-0.2.4',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cbindgen_0_29_2',
        urls = ['https://static.crates.io/crates/cbindgen/cbindgen-0.29.2.crate'],
        sha256 = 'befbfd072a8e81c02f8c507aefce431fe5e7d051f83d48a23ffc9b9fe5a11799',
        strip_prefix = 'cbindgen-0.29.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cfg_if_1_0_4',
        urls = ['https://static.crates.io/crates/cfg-if/cfg-if-1.0.4.crate'],
        sha256 = '9330f8b2ff13f34540b44e946ef35111825727b38d33286ef986142615121801',
        strip_prefix = 'cfg-if-1.0.4',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_chardetng_1_0_0',
        urls = ['https://static.crates.io/crates/chardetng/chardetng-1.0.0.crate'],
        sha256 = '13de944a44b5064ee5d3a5ceccc49a41bfec50f2580e66f82e87703acdb88b53',
        strip_prefix = 'chardetng-1.0.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_clap_4_6_0',
        urls = ['https://static.crates.io/crates/clap/clap-4.6.0.crate'],
        sha256 = 'b193af5b67834b676abd72466a96c1024e6a6ad978a1f484bd90b85c94041351',
        strip_prefix = 'clap-4.6.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_clap_builder_4_6_0',
        urls = ['https://static.crates.io/crates/clap_builder/clap_builder-4.6.0.crate'],
        sha256 = '714a53001bf66416adb0e2ef5ac857140e7dc3a0c48fb28b2f10762fc4b5069f',
        strip_prefix = 'clap_builder-4.6.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_clap_lex_1_1_0',
        urls = ['https://static.crates.io/crates/clap_lex/clap_lex-1.1.0.crate'],
        sha256 = 'c8d4a3bb8b1e0c1050499d1815f5ab16d04f0959b233085fb31653fbfc9d98f9',
        strip_prefix = 'clap_lex-1.1.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_colorchoice_1_0_5',
        urls = ['https://static.crates.io/crates/colorchoice/colorchoice-1.0.5.crate'],
        sha256 = '1d07550c9036bf2ae0c684c4297d503f838287c83c53686d05370d0e139ae570',
        strip_prefix = 'colorchoice-1.0.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_core_maths_0_1_1',
        urls = ['https://static.crates.io/crates/core_maths/core_maths-0.1.1.crate'],
        sha256 = '77745e017f5edba1a9c1d854f6f3a52dac8a12dd5af5d2f54aecf61e43d80d30',
        strip_prefix = 'core_maths-0.1.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_bforest_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-bforest/cranelift-bforest-0.116.1.crate'],
        sha256 = 'e15d04a0ce86cb36ead88ad68cf693ffd6cda47052b9e0ac114bc47fd9cd23c4',
        strip_prefix = 'cranelift-bforest-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_bitset_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-bitset/cranelift-bitset-0.116.1.crate'],
        sha256 = '7c6e3969a7ce267259ce244b7867c5d3bc9e65b0a87e81039588dfdeaede9f34',
        strip_prefix = 'cranelift-bitset-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_codegen_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-codegen/cranelift-codegen-0.116.1.crate'],
        sha256 = '2c22032c4cb42558371cf516bb47f26cdad1819d3475c133e93c49f50ebf304e',
        strip_prefix = 'cranelift-codegen-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_codegen_meta_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-codegen-meta/cranelift-codegen-meta-0.116.1.crate'],
        sha256 = 'c904bc71c61b27fc57827f4a1379f29de64fe95653b620a3db77d59655eee0b8',
        strip_prefix = 'cranelift-codegen-meta-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_codegen_shared_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-codegen-shared/cranelift-codegen-shared-0.116.1.crate'],
        sha256 = '40180f5497572f644ce88c255480981ae2ec1d7bb4d8e0c0136a13b87a2f2ceb',
        strip_prefix = 'cranelift-codegen-shared-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_control_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-control/cranelift-control-0.116.1.crate'],
        sha256 = '26d132c6d0bd8a489563472afc171759da0707804a65ece7ceb15a8c6d7dd5ef',
        strip_prefix = 'cranelift-control-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_entity_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-entity/cranelift-entity-0.116.1.crate'],
        sha256 = '4b2d0d9618275474fbf679dd018ac6e009acbd6ae6850f6a67be33fb3b00b323',
        strip_prefix = 'cranelift-entity-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_frontend_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-frontend/cranelift-frontend-0.116.1.crate'],
        sha256 = '4fac41e16729107393174b0c9e3730fb072866100e1e64e80a1a963b2e484d57',
        strip_prefix = 'cranelift-frontend-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_isle_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-isle/cranelift-isle-0.116.1.crate'],
        sha256 = '1ca20d576e5070044d0a72a9effc2deacf4d6aa650403189d8ea50126483944d',
        strip_prefix = 'cranelift-isle-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_module_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-module/cranelift-module-0.116.1.crate'],
        sha256 = '4d55612bebcf16ff7306c8a6f5bdb6d45662b8aa1ee058ecce8807ad87db719b',
        strip_prefix = 'cranelift-module-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_cranelift_native_0_116_1',
        urls = ['https://static.crates.io/crates/cranelift-native/cranelift-native-0.116.1.crate'],
        sha256 = 'b8dee82f3f1f2c4cba9177f1cc5e350fe98764379bcd29340caa7b01f85076c7',
        strip_prefix = 'cranelift-native-0.116.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_displaydoc_0_2_5',
        urls = ['https://static.crates.io/crates/displaydoc/displaydoc-0.2.5.crate'],
        sha256 = '97369cbbc041bc366949bc74d34658d6cda5621039731c6310521892a3a20ae0',
        strip_prefix = 'displaydoc-0.2.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_either_1_16_0',
        urls = ['https://static.crates.io/crates/either/either-1.16.0.crate'],
        sha256 = '91622ff5e7162018101f2fea40d6ebf4a78bbe5a49736a2020649edf9693679e',
        strip_prefix = 'either-1.16.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_encoding_rs_0_8_35',
        urls = ['https://static.crates.io/crates/encoding_rs/encoding_rs-0.8.35.crate'],
        sha256 = '75030f3c4f45dafd7586dd6780965a8c7e8e285a5ecb86713e63a79c5b2766f3',
        strip_prefix = 'encoding_rs-0.8.35',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_equivalent_1_0_2',
        urls = ['https://static.crates.io/crates/equivalent/equivalent-1.0.2.crate'],
        sha256 = '877a4ace8713b0bcf2a4e7eec82529c029f1d0619886d18145fea96c3ffe5c0f',
        strip_prefix = 'equivalent-1.0.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_errno_0_3_14',
        urls = ['https://static.crates.io/crates/errno/errno-0.3.14.crate'],
        sha256 = '39cab71617ae0d63f51a36d69f866391735b51691dbda63cf6f96d042b63efeb',
        strip_prefix = 'errno-0.3.14',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_fARM64_0_0_2',
        urls = ['https://static.crates.io/crates/fARM64/fARM64-0.0.2.crate'],
        sha256 = '07944644247de4696c3e847a61d939928474563df1d6fc3cc5583a89008c60f7',
        strip_prefix = 'fARM64-0.0.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_fallible_iterator_0_3_0',
        urls = ['https://static.crates.io/crates/fallible-iterator/fallible-iterator-0.3.0.crate'],
        sha256 = '2acce4a10f12dc2fb14a218589d4f1f62ef011b2d0cc4b3cb1bba8e94da14649',
        strip_prefix = 'fallible-iterator-0.3.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_fastrand_2_4_0',
        urls = ['https://static.crates.io/crates/fastrand/fastrand-2.4.0.crate'],
        sha256 = 'a043dc74da1e37d6afe657061213aa6f425f855399a11d3463c6ecccc4dfda1f',
        strip_prefix = 'fastrand-2.4.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_flatbuffers_25_12_19',
        urls = ['https://static.crates.io/crates/flatbuffers/flatbuffers-25.12.19.crate'],
        sha256 = '35f6839d7b3b98adde531effaf34f0c2badc6f4735d26fe74709d8e513a96ef3',
        strip_prefix = 'flatbuffers-25.12.19',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_foldhash_0_1_5',
        urls = ['https://static.crates.io/crates/foldhash/foldhash-0.1.5.crate'],
        sha256 = 'd9c4f5dac5e15c24eb999c26181a6ca40b39fe946cbe4c263c7209467bc83af2',
        strip_prefix = 'foldhash-0.1.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_foldhash_0_2_0',
        urls = ['https://static.crates.io/crates/foldhash/foldhash-0.2.0.crate'],
        sha256 = '77ce24cb58228fbb8aa041425bb1050850ac19177686ea6e0f41a70416f56fdb',
        strip_prefix = 'foldhash-0.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_form_urlencoded_1_2_2',
        urls = ['https://static.crates.io/crates/form_urlencoded/form_urlencoded-1.2.2.crate'],
        sha256 = 'cb4cb245038516f5f85277875cdaa4f7d2c9a0fa0468de06ed190163b1581fcf',
        strip_prefix = 'form_urlencoded-1.2.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_getrandom_0_4_2',
        urls = ['https://static.crates.io/crates/getrandom/getrandom-0.4.2.crate'],
        sha256 = '0de51e6874e94e7bf76d726fc5d13ba782deca734ff60d5bb2fb2607c7406555',
        strip_prefix = 'getrandom-0.4.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_gimli_0_31_1',
        urls = ['https://static.crates.io/crates/gimli/gimli-0.31.1.crate'],
        sha256 = '07e28edb80900c19c28f1072f2e8aeca7fa06b23cd4169cefe1af5aa3260783f',
        strip_prefix = 'gimli-0.31.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_hashbrown_0_14_5',
        urls = ['https://static.crates.io/crates/hashbrown/hashbrown-0.14.5.crate'],
        sha256 = 'e5274423e17b7c9fc20b6e7e208532f9b19825d82dfd615708b70edd83df41f1',
        strip_prefix = 'hashbrown-0.14.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_hashbrown_0_15_5',
        urls = ['https://static.crates.io/crates/hashbrown/hashbrown-0.15.5.crate'],
        sha256 = '9229cfe53dfd69f0609a49f65461bd93001ea1ef889cd5529dd176593f5338a1',
        strip_prefix = 'hashbrown-0.15.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_hashbrown_0_16_1',
        urls = ['https://static.crates.io/crates/hashbrown/hashbrown-0.16.1.crate'],
        sha256 = '841d1cc9bed7f9236f321df977030373f4a4163ae1a7dbfe1a51a2c1a51d9100',
        strip_prefix = 'hashbrown-0.16.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_heck_0_5_0',
        urls = ['https://static.crates.io/crates/heck/heck-0.5.0.crate'],
        sha256 = '2304e00983f87ffb38b55b444b5e3b60a884b5d30c0fca7d82fe33449bbe55ea',
        strip_prefix = 'heck-0.5.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_iced_x86_1_21_0',
        urls = ['https://static.crates.io/crates/iced-x86/iced-x86-1.21.0.crate'],
        sha256 = '7c447cff8c7f384a7d4f741cfcff32f75f3ad02b406432e8d6c878d56b1edf6b',
        strip_prefix = 'iced-x86-1.21.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_calendar_2_2_1',
        urls = ['https://static.crates.io/crates/icu_calendar/icu_calendar-2.2.1.crate'],
        sha256 = 'a2b2acc6263f494f1df50685b53ff8e57869e47d5c6fe39c23d518ae9a4f3e45',
        strip_prefix = 'icu_calendar-2.2.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_calendar_data_2_2_0',
        urls = ['https://static.crates.io/crates/icu_calendar_data/icu_calendar_data-2.2.0.crate'],
        sha256 = '118577bcf3a0fa7c6ac0a7d6e951814da84ee56b9b1f68fb4d8d10b08cefaf4d',
        strip_prefix = 'icu_calendar_data-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_collections_2_2_0',
        urls = ['https://static.crates.io/crates/icu_collections/icu_collections-2.2.0.crate'],
        sha256 = '2984d1cd16c883d7935b9e07e44071dca8d917fd52ecc02c04d5fa0b5a3f191c',
        strip_prefix = 'icu_collections-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_locale_2_2_0',
        urls = ['https://static.crates.io/crates/icu_locale/icu_locale-2.2.0.crate'],
        sha256 = 'd5a396343c7208121dc86e35623d3dfe19814a7613cfd14964994cdc9c9a2e26',
        strip_prefix = 'icu_locale-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_locale_core_2_2_0',
        urls = ['https://static.crates.io/crates/icu_locale_core/icu_locale_core-2.2.0.crate'],
        sha256 = '92219b62b3e2b4d88ac5119f8904c10f8f61bf7e95b640d25ba3075e6cac2c29',
        strip_prefix = 'icu_locale_core-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_locale_data_2_2_0',
        urls = ['https://static.crates.io/crates/icu_locale_data/icu_locale_data-2.2.0.crate'],
        sha256 = 'd5fdcc9ac77c6d74ff5cf6e65ef3181d6af32003b16fce3a77fb451d2f695993',
        strip_prefix = 'icu_locale_data-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_normalizer_2_2_0',
        urls = ['https://static.crates.io/crates/icu_normalizer/icu_normalizer-2.2.0.crate'],
        sha256 = 'c56e5ee99d6e3d33bd91c5d85458b6005a22140021cc324cea84dd0e72cff3b4',
        strip_prefix = 'icu_normalizer-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_normalizer_data_2_2_0',
        urls = ['https://static.crates.io/crates/icu_normalizer_data/icu_normalizer_data-2.2.0.crate'],
        sha256 = 'da3be0ae77ea334f4da67c12f149704f19f81d1adf7c51cf482943e84a2bad38',
        strip_prefix = 'icu_normalizer_data-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_properties_2_2_0',
        urls = ['https://static.crates.io/crates/icu_properties/icu_properties-2.2.0.crate'],
        sha256 = 'bee3b67d0ea5c2cca5003417989af8996f8604e34fb9ddf96208a033901e70de',
        strip_prefix = 'icu_properties-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_properties_data_2_2_0',
        urls = ['https://static.crates.io/crates/icu_properties_data/icu_properties_data-2.2.0.crate'],
        sha256 = '8e2bbb201e0c04f7b4b3e14382af113e17ba4f63e2c9d2ee626b720cbce54a14',
        strip_prefix = 'icu_properties_data-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_icu_provider_2_2_0',
        urls = ['https://static.crates.io/crates/icu_provider/icu_provider-2.2.0.crate'],
        sha256 = '139c4cf31c8b5f33d7e199446eff9c1e02decfc2f0eec2c8d71f65befa45b421',
        strip_prefix = 'icu_provider-2.2.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_id_arena_2_3_0',
        urls = ['https://static.crates.io/crates/id-arena/id-arena-2.3.0.crate'],
        sha256 = '3d3067d79b975e8844ca9eb072e16b31c3c1c36928edf9c6789548c524d0d954',
        strip_prefix = 'id-arena-2.3.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_idna_1_1_0',
        urls = ['https://static.crates.io/crates/idna/idna-1.1.0.crate'],
        sha256 = '3b0875f23caa03898994f6ddc501886a45c7d3d62d04d2d90788d47be1b1e4de',
        strip_prefix = 'idna-1.1.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_idna_adapter_1_2_2',
        urls = ['https://static.crates.io/crates/idna_adapter/idna_adapter-1.2.2.crate'],
        sha256 = 'cb68373c0d6620ef8105e855e7745e18b0d00d3bdb07fb532e434244cdb9a714',
        strip_prefix = 'idna_adapter-1.2.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_indexmap_2_13_1',
        urls = ['https://static.crates.io/crates/indexmap/indexmap-2.13.1.crate'],
        sha256 = '45a8a2b9cb3e0b0c1803dbb0758ffac5de2f425b23c28f518faabd9d805342ff',
        strip_prefix = 'indexmap-2.13.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_is_terminal_polyfill_1_70_2',
        urls = ['https://static.crates.io/crates/is_terminal_polyfill/is_terminal_polyfill-1.70.2.crate'],
        sha256 = 'a6cb138bb79a146c1bd460005623e142ef0181e3d0219cb493e02f7d08a35695',
        strip_prefix = 'is_terminal_polyfill-1.70.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_itertools_0_13_0',
        urls = ['https://static.crates.io/crates/itertools/itertools-0.13.0.crate'],
        sha256 = '413ee7dfc52ee1a4949ceeb7dbc8a33f2d6c088194d9f922fb8318faf1f01186',
        strip_prefix = 'itertools-0.13.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_itoa_1_0_18',
        urls = ['https://static.crates.io/crates/itoa/itoa-1.0.18.crate'],
        sha256 = '8f42a60cbdf9a97f5d2305f08a87dc4e09308d1276d28c869c684d7777685682',
        strip_prefix = 'itoa-1.0.18',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_ixdtf_0_6_5',
        urls = ['https://static.crates.io/crates/ixdtf/ixdtf-0.6.5.crate'],
        sha256 = '2ceaf4c6c48465bead8cb6a0b7c4ee0c86ecbb31239032b9c66ab9a08d2f3ee1',
        strip_prefix = 'ixdtf-0.6.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_lazy_static_1_5_0',
        urls = ['https://static.crates.io/crates/lazy_static/lazy_static-1.5.0.crate'],
        sha256 = 'bbd2bcb4c963f2ddae06a2efc7e9f3591312473c50c6685e1f298068316e66fe',
        strip_prefix = 'lazy_static-1.5.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_leb128fmt_0_1_0',
        urls = ['https://static.crates.io/crates/leb128fmt/leb128fmt-0.1.0.crate'],
        sha256 = '09edd9e8b54e49e587e4f6295a7d29c3ea94d469cb40ab8ca70b288248a81db2',
        strip_prefix = 'leb128fmt-0.1.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_libc_0_2_184',
        urls = ['https://static.crates.io/crates/libc/libc-0.2.184.crate'],
        sha256 = '48f5d2a454e16a5ea0f4ced81bd44e4cfc7bd3a507b61887c99fd3538b28e4af',
        strip_prefix = 'libc-0.2.184',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_libm_0_2_16',
        urls = ['https://static.crates.io/crates/libm/libm-0.2.16.crate'],
        sha256 = 'b6d2cec3eae94f9f509c767b45932f1ada8350c4bdb85af2fcab4a3c14807981',
        strip_prefix = 'libm-0.2.16',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_linux_raw_sys_0_12_1',
        urls = ['https://static.crates.io/crates/linux-raw-sys/linux-raw-sys-0.12.1.crate'],
        sha256 = '32a66949e030da00e8c7d4434b251670a91556f4144941d37452769c25d58a53',
        strip_prefix = 'linux-raw-sys-0.12.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_litemap_0_8_2',
        urls = ['https://static.crates.io/crates/litemap/litemap-0.8.2.crate'],
        sha256 = '92daf443525c4cce67b150400bc2316076100ce0b3686209eb8cf3c31612e6f0',
        strip_prefix = 'litemap-0.8.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_log_0_4_29',
        urls = ['https://static.crates.io/crates/log/log-0.4.29.crate'],
        sha256 = '5e5032e24019045c762d3c0f28f5b6b8bbf38563a65908389bf7978758920897',
        strip_prefix = 'log-0.4.29',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_memchr_2_8_0',
        urls = ['https://static.crates.io/crates/memchr/memchr-2.8.0.crate'],
        sha256 = 'f8ca58f447f06ed17d5fc4043ce1b10dd205e060fb3ce5b979b8ed8e59ff3f79',
        strip_prefix = 'memchr-2.8.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_num_bigint_0_4_6',
        urls = ['https://static.crates.io/crates/num-bigint/num-bigint-0.4.6.crate'],
        sha256 = 'a5e44f723f1133c9deac646763579fdb3ac745e418f2a7af9cd0c431da1f20b9',
        strip_prefix = 'num-bigint-0.4.6',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_num_integer_0_1_46',
        urls = ['https://static.crates.io/crates/num-integer/num-integer-0.1.46.crate'],
        sha256 = '7969661fd2958a5cb096e56c8e1ad0444ac2bbcd0061bd28660485a44879858f',
        strip_prefix = 'num-integer-0.1.46',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_num_traits_0_2_19',
        urls = ['https://static.crates.io/crates/num-traits/num-traits-0.2.19.crate'],
        sha256 = '071dfc062690e90b734c0b2273ce72ad0ffa95f0c74596bc250dcfd960262841',
        strip_prefix = 'num-traits-0.2.19',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_once_cell_1_21_4',
        urls = ['https://static.crates.io/crates/once_cell/once_cell-1.21.4.crate'],
        sha256 = '9f7c3e4beb33f85d45ae3e3a1792185706c8e16d043238c593331cc7cd313b50',
        strip_prefix = 'once_cell-1.21.4',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_once_cell_polyfill_1_70_2',
        urls = ['https://static.crates.io/crates/once_cell_polyfill/once_cell_polyfill-1.70.2.crate'],
        sha256 = '384b8ab6d37215f3c5301a95a4accb5d64aa607f1fcb26a11b5303878451b4fe',
        strip_prefix = 'once_cell_polyfill-1.70.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_percent_encoding_2_3_2',
        urls = ['https://static.crates.io/crates/percent-encoding/percent-encoding-2.3.2.crate'],
        sha256 = '9b4f627cb1b25917193a259e49bdad08f671f8d9708acfd5fe0a8c1455d87220',
        strip_prefix = 'percent-encoding-2.3.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_potential_utf_0_1_5',
        urls = ['https://static.crates.io/crates/potential_utf/potential_utf-0.1.5.crate'],
        sha256 = '0103b1cef7ec0cf76490e969665504990193874ea05c85ff9bab8b911d0a0564',
        strip_prefix = 'potential_utf-0.1.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_precomputed_hash_0_1_1',
        urls = ['https://static.crates.io/crates/precomputed-hash/precomputed-hash-0.1.1.crate'],
        sha256 = '925383efa346730478fb4838dbe9137d2a47675ad789c546d150a6e1dd4ab31c',
        strip_prefix = 'precomputed-hash-0.1.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_prettyplease_0_2_37',
        urls = ['https://static.crates.io/crates/prettyplease/prettyplease-0.2.37.crate'],
        sha256 = '479ca8adacdd7ce8f1fb39ce9ecccbfe93a3f1344b3d0d97f20bc0196208f62b',
        strip_prefix = 'prettyplease-0.2.37',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_proc_macro2_1_0_106',
        urls = ['https://static.crates.io/crates/proc-macro2/proc-macro2-1.0.106.crate'],
        sha256 = '8fd00f0bb2e90d81d1044c2b32617f68fcb9fa3bb7640c23e9c748e53fb30934',
        strip_prefix = 'proc-macro2-1.0.106',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_psl_2_1_210',
        urls = ['https://static.crates.io/crates/psl/psl-2.1.210.crate'],
        sha256 = '27fbd4d9b2eb0b6e0cbd654bce70243f460cbc8dc92df6747e3fb911ce1cd4a8',
        strip_prefix = 'psl-2.1.210',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_psl_types_2_0_11',
        urls = ['https://static.crates.io/crates/psl-types/psl-types-2.0.11.crate'],
        sha256 = '33cb294fe86a74cbcf50d4445b37da762029549ebeea341421c7c70370f86cac',
        strip_prefix = 'psl-types-2.0.11',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_quote_1_0_45',
        urls = ['https://static.crates.io/crates/quote/quote-1.0.45.crate'],
        sha256 = '41f2619966050689382d2b44f664f4bc593e129785a36d6ee376ddf37259b924',
        strip_prefix = 'quote-1.0.45',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_r_efi_6_0_0',
        urls = ['https://static.crates.io/crates/r-efi/r-efi-6.0.0.crate'],
        sha256 = 'f8dcc9c7d52a811697d2151c701e0d08956f92b0e24136cf4cf27b57a6a0d9bf',
        strip_prefix = 'r-efi-6.0.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_regalloc2_0_11_2',
        urls = ['https://static.crates.io/crates/regalloc2/regalloc2-0.11.2.crate'],
        sha256 = 'dc06e6b318142614e4a48bc725abbf08ff166694835c43c9dae5a9009704639a',
        strip_prefix = 'regalloc2-0.11.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_regex_1_12_3',
        urls = ['https://static.crates.io/crates/regex/regex-1.12.3.crate'],
        sha256 = 'e10754a14b9137dd7b1e3e5b0493cc9171fdd105e0ab477f51b72e7f3ac0e276',
        strip_prefix = 'regex-1.12.3',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_regex_automata_0_4_14',
        urls = ['https://static.crates.io/crates/regex-automata/regex-automata-0.4.14.crate'],
        sha256 = '6e1dd4122fc1595e8162618945476892eefca7b88c52820e74af6262213cae8f',
        strip_prefix = 'regex-automata-0.4.14',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_regex_syntax_0_8_10',
        urls = ['https://static.crates.io/crates/regex-syntax/regex-syntax-0.8.10.crate'],
        sha256 = 'dc897dd8d9e8bd1ed8cdad82b5966c3e0ecae09fb1907d58efaa013543185d0a',
        strip_prefix = 'regex-syntax-0.8.10',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_rustc_hash_1_1_0',
        urls = ['https://static.crates.io/crates/rustc-hash/rustc-hash-1.1.0.crate'],
        sha256 = '08d43f7aa6b08d49f382cde6a7982047c3426db949b1424bc4b7ec9ae12c6ce2',
        strip_prefix = 'rustc-hash-1.1.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_rustc_hash_2_1_2',
        urls = ['https://static.crates.io/crates/rustc-hash/rustc-hash-2.1.2.crate'],
        sha256 = '94300abf3f1ae2e2b8ffb7b58043de3d399c73fa6f4b73826402a5c457614dbe',
        strip_prefix = 'rustc-hash-2.1.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_rustc_version_0_4_1',
        urls = ['https://static.crates.io/crates/rustc_version/rustc_version-0.4.1.crate'],
        sha256 = 'cfcb3a22ef46e85b45de6ee7e79d063319ebb6594faafcf1c225ea92ab6e9b92',
        strip_prefix = 'rustc_version-0.4.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_rustix_1_1_4',
        urls = ['https://static.crates.io/crates/rustix/rustix-1.1.4.crate'],
        sha256 = 'b6fe4565b9518b83ef4f91bb47ce29620ca828bd32cb7e408f0062e9930ba190',
        strip_prefix = 'rustix-1.1.4',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_seahash_4_1_0',
        urls = ['https://static.crates.io/crates/seahash/seahash-4.1.0.crate'],
        sha256 = '1c107b6f4780854c8b126e228ea8869f4d7b71260f962fefb57b996b8959ba6b',
        strip_prefix = 'seahash-4.1.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_semver_1_0_28',
        urls = ['https://static.crates.io/crates/semver/semver-1.0.28.crate'],
        sha256 = '8a7852d02fc848982e0c167ef163aaff9cd91dc640ba85e263cb1ce46fae51cd',
        strip_prefix = 'semver-1.0.28',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_serde_1_0_228',
        urls = ['https://static.crates.io/crates/serde/serde-1.0.228.crate'],
        sha256 = '9a8e94ea7f378bd32cbbd37198a4a91436180c5bb472411e48b5ec2e2124ae9e',
        strip_prefix = 'serde-1.0.228',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_serde_core_1_0_228',
        urls = ['https://static.crates.io/crates/serde_core/serde_core-1.0.228.crate'],
        sha256 = '41d385c7d4ca58e59fc732af25c3983b67ac852c1a25000afe1175de458b67ad',
        strip_prefix = 'serde_core-1.0.228',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_serde_derive_1_0_228',
        urls = ['https://static.crates.io/crates/serde_derive/serde_derive-1.0.228.crate'],
        sha256 = 'd540f220d3187173da220f885ab66608367b6574e925011a9353e4badda91d79',
        strip_prefix = 'serde_derive-1.0.228',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_serde_json_1_0_149',
        urls = ['https://static.crates.io/crates/serde_json/serde_json-1.0.149.crate'],
        sha256 = '83fc039473c5595ace860d8c4fafa220ff474b3fc6bfdb4293327f1a37e94d86',
        strip_prefix = 'serde_json-1.0.149',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_serde_spanned_1_1_1',
        urls = ['https://static.crates.io/crates/serde_spanned/serde_spanned-1.1.1.crate'],
        sha256 = '6662b5879511e06e8999a8a235d848113e942c9124f211511b16466ee2995f26',
        strip_prefix = 'serde_spanned-1.1.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_smallvec_1_15_1',
        urls = ['https://static.crates.io/crates/smallvec/smallvec-1.15.1.crate'],
        sha256 = '67b1b7a3b5fe4f1376887184045fcf45c69e92af734b7aaddc05fb777b6fbd03',
        strip_prefix = 'smallvec-1.15.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_stable_deref_trait_1_2_1',
        urls = ['https://static.crates.io/crates/stable_deref_trait/stable_deref_trait-1.2.1.crate'],
        sha256 = '6ce2be8dc25455e1f91df71bfa12ad37d7af1092ae736f3a6cd0e37bc7810596',
        strip_prefix = 'stable_deref_trait-1.2.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_strsim_0_11_1',
        urls = ['https://static.crates.io/crates/strsim/strsim-0.11.1.crate'],
        sha256 = '7da8b5736845d9f2fcb837ea5d9e2628564b3b043a70948a3f0b778838c5fb4f',
        strip_prefix = 'strsim-0.11.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_syn_2_0_117',
        urls = ['https://static.crates.io/crates/syn/syn-2.0.117.crate'],
        sha256 = 'e665b8803e7b1d2a727f4023456bbbbe74da67099c585258af0ad9c5013b9b99',
        strip_prefix = 'syn-2.0.117',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_synstructure_0_13_2',
        urls = ['https://static.crates.io/crates/synstructure/synstructure-0.13.2.crate'],
        sha256 = '728a70f3dbaf5bab7f0c4b1ac8d7ae5ea60a4b5549c8a5914361c99147a709d2',
        strip_prefix = 'synstructure-0.13.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_target_lexicon_0_13_5',
        urls = ['https://static.crates.io/crates/target-lexicon/target-lexicon-0.13.5.crate'],
        sha256 = 'adb6935a6f5c20170eeceb1a3835a49e12e19d792f6dd344ccc76a985ca5a6ca',
        strip_prefix = 'target-lexicon-0.13.5',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_tempfile_3_27_0',
        urls = ['https://static.crates.io/crates/tempfile/tempfile-3.27.0.crate'],
        sha256 = '32497e9a4c7b38532efcdebeef879707aa9f794296a4f0244f6f69e9bc8574bd',
        strip_prefix = 'tempfile-3.27.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_thiserror_1_0_69',
        urls = ['https://static.crates.io/crates/thiserror/thiserror-1.0.69.crate'],
        sha256 = 'b6aaf5339b578ea85b50e080feb250a3e8ae8cfcdff9a461c9ec2904bc923f52',
        strip_prefix = 'thiserror-1.0.69',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_thiserror_impl_1_0_69',
        urls = ['https://static.crates.io/crates/thiserror-impl/thiserror-impl-1.0.69.crate'],
        sha256 = '4fee6c4efc90059e10f81e6d42c60a18f76588c3d74cb83a0b242a2b6c7504c1',
        strip_prefix = 'thiserror-impl-1.0.69',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_tinystr_0_8_3',
        urls = ['https://static.crates.io/crates/tinystr/tinystr-0.8.3.crate'],
        sha256 = 'c8323304221c2a851516f22236c5722a72eaa19749016521d6dff0824447d96d',
        strip_prefix = 'tinystr-0.8.3',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_toml_0_9_12_spec_1_1_0',
        urls = ['https://static.crates.io/crates/toml/toml-0.9.12+spec-1.1.0.crate'],
        sha256 = 'cf92845e79fc2e2def6a5d828f0801e29a2f8acc037becc5ab08595c7d5e9863',
        strip_prefix = 'toml-0.9.12+spec-1.1.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_toml_datetime_0_7_5_spec_1_1_0',
        urls = ['https://static.crates.io/crates/toml_datetime/toml_datetime-0.7.5+spec-1.1.0.crate'],
        sha256 = '92e1cfed4a3038bc5a127e35a2d360f145e1f4b971b551a2ba5fd7aedf7e1347',
        strip_prefix = 'toml_datetime-0.7.5+spec-1.1.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_toml_parser_1_1_2_spec_1_1_0',
        urls = ['https://static.crates.io/crates/toml_parser/toml_parser-1.1.2+spec-1.1.0.crate'],
        sha256 = 'a2abe9b86193656635d2411dc43050282ca48aa31c2451210f4202550afb7526',
        strip_prefix = 'toml_parser-1.1.2+spec-1.1.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_toml_writer_1_1_1_spec_1_1_0',
        urls = ['https://static.crates.io/crates/toml_writer/toml_writer-1.1.1+spec-1.1.0.crate'],
        sha256 = '756daf9b1013ebe47a8776667b466417e2d4c5679d441c26230efd9ef78692db',
        strip_prefix = 'toml_writer-1.1.1+spec-1.1.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_unicode_ident_1_0_24',
        urls = ['https://static.crates.io/crates/unicode-ident/unicode-ident-1.0.24.crate'],
        sha256 = 'e6e4313cd5fcd3dad5cafa179702e2b244f760991f45397d14d4ebf38247da75',
        strip_prefix = 'unicode-ident-1.0.24',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_unicode_xid_0_2_6',
        urls = ['https://static.crates.io/crates/unicode-xid/unicode-xid-0.2.6.crate'],
        sha256 = 'ebc1c04c71510c7f702b52b7c350734c9ff1295c464a03335b00bb84fc54f853',
        strip_prefix = 'unicode-xid-0.2.6',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_url_2_5_8',
        urls = ['https://static.crates.io/crates/url/url-2.5.8.crate'],
        sha256 = 'ff67a8a4397373c3ef660812acab3268222035010ab8680ec4215f38ba3d0eed',
        strip_prefix = 'url-2.5.8',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_utf8_iter_1_0_4',
        urls = ['https://static.crates.io/crates/utf8_iter/utf8_iter-1.0.4.crate'],
        sha256 = 'b6c140620e7ffbb22c2dee59cafe6084a59b5ffc27a8859a5f0d494b5d52b6be',
        strip_prefix = 'utf8_iter-1.0.4',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_utf8parse_0_2_2',
        urls = ['https://static.crates.io/crates/utf8parse/utf8parse-0.2.2.crate'],
        sha256 = '06abde3611657adf66d383f00b093d7faecc7fa57071cce2578660c9f1010821',
        strip_prefix = 'utf8parse-0.2.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wasip2_1_0_2_wasi_0_2_9',
        urls = ['https://static.crates.io/crates/wasip2/wasip2-1.0.2+wasi-0.2.9.crate'],
        sha256 = '9517f9239f02c069db75e65f174b3da828fe5f5b945c4dd26bd25d89c03ebcf5',
        strip_prefix = 'wasip2-1.0.2+wasi-0.2.9',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wasip3_0_4_0_wasi_0_3_0_rc_2026_01_06',
        urls = ['https://static.crates.io/crates/wasip3/wasip3-0.4.0+wasi-0.3.0-rc-2026-01-06.crate'],
        sha256 = '5428f8bf88ea5ddc08faddef2ac4a67e390b88186c703ce6dbd955e1c145aca5',
        strip_prefix = 'wasip3-0.4.0+wasi-0.3.0-rc-2026-01-06',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wasm_encoder_0_244_0',
        urls = ['https://static.crates.io/crates/wasm-encoder/wasm-encoder-0.244.0.crate'],
        sha256 = '990065f2fe63003fe337b932cfb5e3b80e0b4d0f5ff650e6985b1048f62c8319',
        strip_prefix = 'wasm-encoder-0.244.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wasm_metadata_0_244_0',
        urls = ['https://static.crates.io/crates/wasm-metadata/wasm-metadata-0.244.0.crate'],
        sha256 = 'bb0e353e6a2fbdc176932bbaab493762eb1255a7900fe0fea1a2f96c296cc909',
        strip_prefix = 'wasm-metadata-0.244.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wasmparser_0_244_0',
        urls = ['https://static.crates.io/crates/wasmparser/wasmparser-0.244.0.crate'],
        sha256 = '47b807c72e1bac69382b3a6fb3dbe8ea4c0ed87ff5629b8685ae6b9a611028fe',
        strip_prefix = 'wasmparser-0.244.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_windows_link_0_2_1',
        urls = ['https://static.crates.io/crates/windows-link/windows-link-0.2.1.crate'],
        sha256 = 'f0805222e57f7521d6a62e36fa9163bc891acd422f971defe97d64e70d0a4fe5',
        strip_prefix = 'windows-link-0.2.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_windows_sys_0_61_2',
        urls = ['https://static.crates.io/crates/windows-sys/windows-sys-0.61.2.crate'],
        sha256 = 'ae137229bcbd6cdf0f7b80a31df61766145077ddf49416a728b02cb3921ff3fc',
        strip_prefix = 'windows-sys-0.61.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_winnow_0_7_15',
        urls = ['https://static.crates.io/crates/winnow/winnow-0.7.15.crate'],
        sha256 = 'df79d97927682d2fd8adb29682d1140b343be4ac0f08fd68b7765d9c059d3945',
        strip_prefix = 'winnow-0.7.15',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_winnow_1_0_1',
        urls = ['https://static.crates.io/crates/winnow/winnow-1.0.1.crate'],
        sha256 = '09dac053f1cd375980747450bfc7250c264eaae0583872e845c0c7cd578872b5',
        strip_prefix = 'winnow-1.0.1',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wit_bindgen_0_51_0',
        urls = ['https://static.crates.io/crates/wit-bindgen/wit-bindgen-0.51.0.crate'],
        sha256 = 'd7249219f66ced02969388cf2bb044a09756a083d0fab1e566056b04d9fbcaa5',
        strip_prefix = 'wit-bindgen-0.51.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wit_bindgen_core_0_51_0',
        urls = ['https://static.crates.io/crates/wit-bindgen-core/wit-bindgen-core-0.51.0.crate'],
        sha256 = 'ea61de684c3ea68cb082b7a88508a8b27fcc8b797d738bfc99a82facf1d752dc',
        strip_prefix = 'wit-bindgen-core-0.51.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wit_bindgen_rust_0_51_0',
        urls = ['https://static.crates.io/crates/wit-bindgen-rust/wit-bindgen-rust-0.51.0.crate'],
        sha256 = 'b7c566e0f4b284dd6561c786d9cb0142da491f46a9fbed79ea69cdad5db17f21',
        strip_prefix = 'wit-bindgen-rust-0.51.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wit_bindgen_rust_macro_0_51_0',
        urls = ['https://static.crates.io/crates/wit-bindgen-rust-macro/wit-bindgen-rust-macro-0.51.0.crate'],
        sha256 = '0c0f9bfd77e6a48eccf51359e3ae77140a7f50b1e2ebfe62422d8afdaffab17a',
        strip_prefix = 'wit-bindgen-rust-macro-0.51.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wit_component_0_244_0',
        urls = ['https://static.crates.io/crates/wit-component/wit-component-0.244.0.crate'],
        sha256 = '9d66ea20e9553b30172b5e831994e35fbde2d165325bec84fc43dbf6f4eb9cb2',
        strip_prefix = 'wit-component-0.244.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_wit_parser_0_244_0',
        urls = ['https://static.crates.io/crates/wit-parser/wit-parser-0.244.0.crate'],
        sha256 = 'ecc8ac4bc1dc3381b7f59c34f00b67e18f910c2c0f50015669dde7def656a736',
        strip_prefix = 'wit-parser-0.244.0',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_writeable_0_6_3',
        urls = ['https://static.crates.io/crates/writeable/writeable-0.6.3.crate'],
        sha256 = '1ffae5123b2d3fc086436f8834ae3ab053a283cfac8fe0a0b8eaae044768a4c4',
        strip_prefix = 'writeable-0.6.3',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_yoke_0_8_2',
        urls = ['https://static.crates.io/crates/yoke/yoke-0.8.2.crate'],
        sha256 = 'abe8c5fda708d9ca3df187cae8bfb9ceda00dd96231bed36e445a1a48e66f9ca',
        strip_prefix = 'yoke-0.8.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_yoke_derive_0_8_2',
        urls = ['https://static.crates.io/crates/yoke-derive/yoke-derive-0.8.2.crate'],
        sha256 = 'de844c262c8848816172cef550288e7dc6c7b7814b4ee56b3e1553f275f1858e',
        strip_prefix = 'yoke-derive-0.8.2',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_yuv_0_8_13',
        urls = ['https://static.crates.io/crates/yuv/yuv-0.8.13.crate'],
        sha256 = '47d3a7e2cda3061858987ee2fb028f61695f5ee13f9490d75be6c3900df9a4ea',
        strip_prefix = 'yuv-0.8.13',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_zerofrom_0_1_7',
        urls = ['https://static.crates.io/crates/zerofrom/zerofrom-0.1.7.crate'],
        sha256 = '69faa1f2a1ea75661980b013019ed6687ed0e83d069bc1114e2cc74c6c04c4df',
        strip_prefix = 'zerofrom-0.1.7',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_zerofrom_derive_0_1_7',
        urls = ['https://static.crates.io/crates/zerofrom-derive/zerofrom-derive-0.1.7.crate'],
        sha256 = '11532158c46691caf0f2593ea8358fed6bbf68a0315e80aae9bd41fbade684a1',
        strip_prefix = 'zerofrom-derive-0.1.7',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_zerotrie_0_2_4',
        urls = ['https://static.crates.io/crates/zerotrie/zerotrie-0.2.4.crate'],
        sha256 = '0f9152d31db0792fa83f70fb2f83148effb5c1f5b8c7686c3459e361d9bc20bf',
        strip_prefix = 'zerotrie-0.2.4',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_zerovec_0_11_6',
        urls = ['https://static.crates.io/crates/zerovec/zerovec-0.11.6.crate'],
        sha256 = '90f911cbc359ab6af17377d242225f4d75119aec87ea711a880987b18cd7b239',
        strip_prefix = 'zerovec-0.11.6',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_zerovec_derive_0_11_3',
        urls = ['https://static.crates.io/crates/zerovec-derive/zerovec-derive-0.11.3.crate'],
        sha256 = '625dc425cab0dca6dc3c3319506e6593dcb08a9f387ea3b284dbd52a92c40555',
        strip_prefix = 'zerovec-derive-0.11.3',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )
    http_archive(
        name = 'crate_zmij_1_0_21',
        urls = ['https://static.crates.io/crates/zmij/zmij-1.0.21.crate'],
        sha256 = 'b8848ee67ecc8aedbaf3e4122217aff892639231befc6a1b58d29fff4c2cabaa',
        strip_prefix = 'zmij-1.0.21',
        type = "tgz",
        build_file_content = _CRATE_BUILD,
    )

# Files only -- deliberately NOT `exclude_directories = 0`. Globbing the
# directories as well makes Bazel stage both a directory and its
# contents into the sandbox, which fails with a bare "File exists" on
# the first one (adblock's benches/) -- a message that names the path
# but not the cause. The staging script rebuilds the tree from the file
# paths, so the directory entries were never needed.
_CRATE_BUILD = """filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
"""
