# AUTO-GENERATED by Meta/emit_cargo_bazel.py — do not edit.
# http_archive is a REPOSITORY rule, so under bzlmod it cannot be
# called from MODULE.bazel -- it has to come from a module extension.
# That indirection is also what lets one use_repo() name 158 repos
# without MODULE.bazel enumerating a single URL or hash.
load(":cargo_crates.bzl", "cargo_crates")
load(":cargo.bzl", "rust_toolchain_archives")

def _cargo_deps_impl(_ctx):
    cargo_crates()
    # The pinned toolchain is fetched the same way the crates are:
    # rust-toolchain.toml names a channel, and honouring it without
    # rustup means three versioned http_archives.
    rust_toolchain_archives()

cargo_deps = module_extension(implementation = _cargo_deps_impl)
