# AUTO-GENERATED by Meta/emit_root_codegen_bazel.py — do not edit.
load("@rules_cc//cc:defs.bzl", "cc_library")
# 20 Python-generator genrules for the root package,
# 2 glslang shader headers, 2 self-built-tool genrules
# (byte-parity: Meta/bazel_parity_harness.py).

def root_codegen():
    native.genrule(
        name = 'gen_HSTSPreloadData',
        srcs = ['Build/caches/HSTSPreload/transport_security_state_static.json'] + ["//Meta:generators"],
        outs = ['Libraries/LibHTTP/HSTSPreloadData.h', 'Libraries/LibHTTP/HSTSPreloadData.cpp'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_hsts_preload_data.py -h $(location Libraries/LibHTTP/HSTSPreloadData.h) -c $(location Libraries/LibHTTP/HSTSPreloadData.cpp) -p $(location Build/caches/HSTSPreload/transport_security_state_static.json)",
    )
    native.genrule(
        name = 'gen_Op',
        srcs = ['Libraries/LibJS/Bytecode/Bytecode.def'] + ["//Meta:generators"],
        outs = ['Libraries/LibJS/Bytecode/Op.h', 'Libraries/LibJS/Bytecode/Op.cpp', 'Libraries/LibJS/Bytecode/OpCodes.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_libjs_bytecode_def_derived.py -h $(location Libraries/LibJS/Bytecode/Op.h) -c $(location Libraries/LibJS/Bytecode/Op.cpp) -i $(location Libraries/LibJS/Bytecode/Bytecode.def) -x $(location Libraries/LibJS/Bytecode/OpCodes.h)",
    )
    native.genrule(
        name = 'gen_RequestClientEndpoint',
        srcs = ['Services/RequestServer/RequestClient.ipc'] + ["//Meta:generators"],
        outs = ['Services/RequestServer/RequestClientEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/RequestServer/RequestClient.ipc) --output $(location Services/RequestServer/RequestClientEndpoint.h)",
    )
    native.genrule(
        name = 'gen_RequestServerEndpoint',
        srcs = ['Services/RequestServer/RequestServer.ipc'] + ["//Meta:generators"],
        outs = ['Services/RequestServer/RequestServerEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/RequestServer/RequestServer.ipc) --output $(location Services/RequestServer/RequestServerEndpoint.h)",
    )
    native.genrule(
        name = 'gen_TIFFMetadata',
        srcs = ['Libraries/LibGfx/TIFFGenerator.py'] + ["//Meta:generators"],
        outs = ['Libraries/LibGfx/ImageFormats/TIFFMetadata.h', 'Libraries/LibGfx/ImageFormats/TIFFTagHandler.cpp'],
        cmd = "mkdir -p $(RULEDIR)/Libraries/LibGfx/ImageFormats && PYTHONHASHSEED=0 python3 Libraries/LibGfx/TIFFGenerator.py -o $(RULEDIR)/Libraries/LibGfx/ImageFormats",
    )
    native.genrule(
        name = 'gen_ImageDecoderClientEndpoint',
        srcs = ['Services/ImageDecoder/ImageDecoderClient.ipc'] + ["//Meta:generators"],
        outs = ['Services/ImageDecoder/ImageDecoderClientEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/ImageDecoder/ImageDecoderClient.ipc) --output $(location Services/ImageDecoder/ImageDecoderClientEndpoint.h)",
    )
    native.genrule(
        name = 'gen_ImageDecoderServerEndpoint',
        srcs = ['Services/ImageDecoder/ImageDecoderServer.ipc'] + ["//Meta:generators"],
        outs = ['Services/ImageDecoder/ImageDecoderServerEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/ImageDecoder/ImageDecoderServer.ipc) --output $(location Services/ImageDecoder/ImageDecoderServerEndpoint.h)",
    )
    native.genrule(
        name = 'gen_UIProcessServerEndpoint',
        srcs = ['Libraries/LibWebView/UIProcessServer.ipc'] + ["//Meta:generators"],
        outs = ['Libraries/LibWebView/UIProcessServerEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Libraries/LibWebView/UIProcessServer.ipc) --output $(location Libraries/LibWebView/UIProcessServerEndpoint.h)",
    )
    native.genrule(
        name = 'gen_UIProcessClientEndpoint',
        srcs = ['Libraries/LibWebView/UIProcessClient.ipc'] + ["//Meta:generators"],
        outs = ['Libraries/LibWebView/UIProcessClientEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Libraries/LibWebView/UIProcessClient.ipc) --output $(location Libraries/LibWebView/UIProcessClientEndpoint.h)",
    )
    native.genrule(
        name = 'gen_CompositorControlClientEndpoint',
        srcs = ['Services/Compositor/CompositorControlClient.ipc'] + ["//Meta:generators"],
        outs = ['Services/Compositor/CompositorControlClientEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/Compositor/CompositorControlClient.ipc) --output $(location Services/Compositor/CompositorControlClientEndpoint.h)",
    )
    native.genrule(
        name = 'gen_CompositorControlServerEndpoint',
        srcs = ['Services/Compositor/CompositorControlServer.ipc'] + ["//Meta:generators"],
        outs = ['Services/Compositor/CompositorControlServerEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/Compositor/CompositorControlServer.ipc) --output $(location Services/Compositor/CompositorControlServerEndpoint.h)",
    )
    native.genrule(
        name = 'gen_CompositorWebContentClientEndpoint',
        srcs = ['Services/Compositor/CompositorWebContentClient.ipc'] + ["//Meta:generators"],
        outs = ['Services/Compositor/CompositorWebContentClientEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/Compositor/CompositorWebContentClient.ipc) --output $(location Services/Compositor/CompositorWebContentClientEndpoint.h)",
    )
    native.genrule(
        name = 'gen_CompositorWebContentServerEndpoint',
        srcs = ['Services/Compositor/CompositorWebContentServer.ipc'] + ["//Meta:generators"],
        outs = ['Services/Compositor/CompositorWebContentServerEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/Compositor/CompositorWebContentServer.ipc) --output $(location Services/Compositor/CompositorWebContentServerEndpoint.h)",
    )
    native.genrule(
        name = 'gen_WebContentClientEndpoint',
        srcs = ['Services/WebContent/WebContentClient.ipc'] + ["//Meta:generators"],
        outs = ['Services/WebContent/WebContentClientEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/WebContent/WebContentClient.ipc) --output $(location Services/WebContent/WebContentClientEndpoint.h)",
    )
    native.genrule(
        name = 'gen_WebContentServerEndpoint',
        srcs = ['Services/WebContent/WebContentServer.ipc'] + ["//Meta:generators"],
        outs = ['Services/WebContent/WebContentServerEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/WebContent/WebContentServer.ipc) --output $(location Services/WebContent/WebContentServerEndpoint.h)",
    )
    native.genrule(
        name = 'gen_WebDriverClientEndpoint',
        srcs = ['Services/WebContent/WebDriverClient.ipc'] + ["//Meta:generators"],
        outs = ['Services/WebContent/WebDriverClientEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/WebContent/WebDriverClient.ipc) --output $(location Services/WebContent/WebDriverClientEndpoint.h)",
    )
    native.genrule(
        name = 'gen_WebDriverServerEndpoint',
        srcs = ['Services/WebContent/WebDriverServer.ipc'] + ["//Meta:generators"],
        outs = ['Services/WebContent/WebDriverServerEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/WebContent/WebDriverServer.ipc) --output $(location Services/WebContent/WebDriverServerEndpoint.h)",
    )
    native.genrule(
        name = 'gen_WebUIClientEndpoint',
        srcs = ['Services/WebContent/WebUIClient.ipc'] + ["//Meta:generators"],
        outs = ['Services/WebContent/WebUIClientEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/WebContent/WebUIClient.ipc) --output $(location Services/WebContent/WebUIClientEndpoint.h)",
    )
    native.genrule(
        name = 'gen_WebUIServerEndpoint',
        srcs = ['Services/WebContent/WebUIServer.ipc'] + ["//Meta:generators"],
        outs = ['Services/WebContent/WebUIServerEndpoint.h'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_ipc_definitions.py --input $(location Services/WebContent/WebUIServer.ipc) --output $(location Services/WebContent/WebUIServerEndpoint.h)",
    )
    native.genrule(
        name = 'gen_WebGLCommandReplayer',
        srcs = ['//Libraries/LibWeb:WebGL/GLFunctions.json'] + ["//Meta:generators"],
        outs = ['Services/Compositor/WebGLCommandReplayer.h', 'Services/Compositor/WebGLCommandReplayer.cpp'],
        cmd = "PYTHONHASHSEED=0 python3 Meta/Generators/generate_compositor_webgl_replayer.py -h $(location Services/Compositor/WebGLCommandReplayer.h) -c $(location Services/Compositor/WebGLCommandReplayer.cpp) -j $(location //Libraries/LibWeb:WebGL/GLFunctions.json)",
    )
    # Two chained self-built tools. generate_interpreter_layout is
    # built by Bazel (//:generate_interpreter_layout) and emits the
    # struct offsets flapc needs; flapc then compiles the Flap DSL to
    # the interpreter assembly. tools=[] makes each a declared,
    # hashed input, so the .S is Bazel output rather than a shim over
    # CMake's build tree. flapc is Bazel-built too now (//:flapc,
    # a cargo_binary from its own 3-package lock), so neither tool
    # nor output in this chain comes from the reference build.
    native.genrule(
        name = 'gen_interpreter_layout',
        outs = ['Libraries/LibJS/Interpreter/layout.conf'],
        tools = ["//:generate_interpreter_layout"],
        srcs = ['//:vcpkg_installed_exec'],
        cmd = "$(location //:generate_interpreter_layout) > $@",
    )
    native.genrule(
        name = 'gen_interpreter_asm',
        srcs = ['Libraries/LibJS/Interpreter/interpreter.flap', 'Libraries/LibJS/Bytecode/Bytecode.def', ':Libraries/LibJS/Interpreter/layout.conf'],
        outs = ['Libraries/LibJS/Interpreter/interpreter_x86_64.S'],
        tools = ['//:flapc'],
        cmd = "$(location //:flapc) --arch x86_64 --object-format elf --constants $(location :Libraries/LibJS/Interpreter/layout.conf) --bytecode-def $(location Libraries/LibJS/Bytecode/Bytecode.def) --input $(location Libraries/LibJS/Interpreter/interpreter.flap) --output $@",
    )
    cc_library(
        name = 'generated_libraries_headers',
        hdrs = [':Libraries/LibGfx/ImageFormats/TIFFMetadata.h', ':Libraries/LibHTTP/HSTSPreloadData.h', ':Libraries/LibJS/Bytecode/Op.h', ':Libraries/LibJS/Bytecode/OpCodes.h', ':Libraries/LibWebView/UIProcessClientEndpoint.h', ':Libraries/LibWebView/UIProcessServerEndpoint.h'],
        includes = ['Libraries'],
    )
    cc_library(
        name = 'generated_services_headers',
        hdrs = [':Services/Compositor/CompositorControlClientEndpoint.h', ':Services/Compositor/CompositorControlServerEndpoint.h', ':Services/Compositor/CompositorWebContentClientEndpoint.h', ':Services/Compositor/CompositorWebContentServerEndpoint.h', ':Services/Compositor/WebGLCommandReplayer.h', ':Services/ImageDecoder/ImageDecoderClientEndpoint.h', ':Services/ImageDecoder/ImageDecoderServerEndpoint.h', ':Services/RequestServer/RequestClientEndpoint.h', ':Services/RequestServer/RequestServerEndpoint.h', ':Services/WebContent/WebContentClientEndpoint.h', ':Services/WebContent/WebContentServerEndpoint.h', ':Services/WebContent/WebDriverClientEndpoint.h', ':Services/WebContent/WebDriverServerEndpoint.h', ':Services/WebContent/WebUIClientEndpoint.h', ':Services/WebContent/WebUIServerEndpoint.h'],
        includes = ['Services'],
    )
    # glslangValidator (host tool, absolute path -- same escape as
    # python3 above) compiles the Vulkan shaders to SPIR-V and emits
    # them as C arrays named by --vn.
    native.genrule(
        name = 'gen_WebContentViewLinuxFragShader',
        srcs = ['UI/Qt/Shaders/WebContentViewLinux.frag'],
        outs = ['UI/Qt/WebContentViewLinuxFragShader.h'],
        cmd = "/usr/bin/glslangValidator -V --vn webcontent_frag_shader_spv -o $(location UI/Qt/WebContentViewLinuxFragShader.h) $(location UI/Qt/Shaders/WebContentViewLinux.frag)",
    )
    native.genrule(
        name = 'gen_WebContentViewLinuxVertShader',
        srcs = ['UI/Qt/Shaders/WebContentViewLinux.vert'],
        outs = ['UI/Qt/WebContentViewLinuxVertShader.h'],
        cmd = "/usr/bin/glslangValidator -V --vn webcontent_vert_shader_spv -o $(location UI/Qt/WebContentViewLinuxVertShader.h) $(location UI/Qt/Shaders/WebContentViewLinux.vert)",
    )
    cc_library(
        name = 'generated_shader_headers',
        hdrs = [':UI/Qt/WebContentViewLinuxFragShader.h', ':UI/Qt/WebContentViewLinuxVertShader.h'],
        includes = ['UI/Qt'],
    )
