# Chromium's HSTS preload table, pinned to a commit. GENERATED by
# Meta/pin_hsts_preload.py -- see that script to re-pin; do not hand-edit.
#
# WHY THIS FILE EXISTS. `Meta/CMake/hsts_preload.cmake` downloads
# net/http/transport_security_state_static.json from Chromium's **main** at
# configure time -- an unversioned ref. The generator turns it into a ~95,000
# entry `constexpr Array` of domains LibHTTP forces to HTTPS, so "whatever main
# served the day you configured" decides a security-relevant table, and two
# developers who configured on different days build different browsers.
#
# The fix belongs upstream (pin the URL in hsts_preload.cmake). We cannot make
# that change from here, so we pin DOWNSTREAM: Bazel fetches one immutable
# commit URL with a sha256, and the upstream unpinned fetch is filed as a bug.
#
# Pinning downstream is only honest if it does not break byte-parity with CMake,
# and this pin does not: the bytes this commit serves are byte-identical to the
# ones CMake's `main` fetch downloaded for the reference build (10,521,748 bytes,
# checked with --expect-same-as, which refuses to write this file otherwise).
# Pinning to a Chromium *release tag* would NOT have that property: 139.0.7258.5
# serves 18.7 MB and generates 168,593 entries against this commit's 94,626.
#
# Two consequences worth knowing:
#
#   * CMake still tracks `main`, so a CMake configure NEWER than this pin will
#     disagree with Bazel. That is now a visible, dated disagreement between one
#     pinned input and one unpinned one, instead of two unpinned fetches that
#     happened to agree. `download_file` is a no-op when the file already exists
#     (verified with ENABLE_NETWORK_DOWNLOADS=OFF), so staging the Bazel-fetched
#     file into Build/caches/HSTSPreload/ before configuring makes CMake consume
#     this same pin -- see README, "Getting the three inputs".
#   * Bumping the pin is a deliberate, reviewable act: re-run
#     Meta/pin_hsts_preload.py, which resolves the newest commit touching the
#     path, downloads it, and writes this file with the hash it measured.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

# The pinned commit: "[HSTS] Update bulk entries" (2026-07-24).
# raw.githubusercontent.com paths are immutable for a full commit sha, unlike the
# `main` path CMake uses.
HSTS_PRELOAD_COMMIT = "3d75766484199c1fbefd269a4b168cccdb36fbca"

HSTS_PRELOAD_SHA256 = "59c3301277b3418e716d818d26110edb0737edb871c5bba7462158da1b2d1bd9"

HSTS_PRELOAD_URL = "https://raw.githubusercontent.com/chromium/chromium/{}/net/http/transport_security_state_static.json".format(
    HSTS_PRELOAD_COMMIT,
)

def _hsts_preload_impl(_ctx):
    http_file(
        name = "hsts_preload_json",
        urls = [HSTS_PRELOAD_URL],
        sha256 = HSTS_PRELOAD_SHA256,
        downloaded_file_path = "transport_security_state_static.json",
    )

hsts_preload = module_extension(implementation = _hsts_preload_impl)
