# AUTO-GENERATED by Meta/emit_vcpkg_bazel.py — do not edit.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

# 4 git-sourced externals. vcpkg_from_git bypasses asset caching
# entirely, but DOES honour a pre-placed downloads/<PORT>-<REF>.tar.gz,
# which is what these become. The SHA512 is of the `git archive` output,
# so it is only stable because git archive is deterministic for a fixed
# ref -- verified by two independent runs producing identical bytes.

VCPKG_GIT_ARCHIVES = {
    'angle-4028ebf8710ee39d2286cb0f847f9b95c59f84d8.tar.gz': 'e75e75e7ab76f02b4a4972c64b5a3c05883fca5adc7d5564cfbd237943b2d5afa7160f771911ab5234c261e8cf7e10cadb1816be52c783f7e39edfe31b8ce248',
    'libyuv-d98915a654d3564e4802a0004add46221c4e4348.tar.gz': 'b1d76b6ea0804f35c2c2ae83b6f0284baecd2f4bf1e49af29d930eaa28e0d1a1639cfb882e71e30641ceaeacbdbe6128899c50445ed24cfe7f3ed128ccfb5c34',
    'skia-bb217acdca1cc0c16b704669dd6f91a1b509c406.tar.gz': 'd2502a9490b3645cf3cf600fc291fe84af28e0e7aff2fe92fa5f7d141decaa4c279def87401d470820ae4447110e5b517d0cb897dee2b1dbce7e62fd6e8d5892',
    'skia-e3f919ccfe3ef542cfc983a82146070258fb57f8.tar.gz': '96e2627893e5e7b7a5564d2d34025f9750a06d754a8d527a5377a7a4f8c3985ea9a8f17e4ea69f18889f47578f6dd1fae6bcf232cba657db9edc5c423e64b90e',
}
