# AUTO-GENERATED by Meta/emit_vcpkg_bazel.py — do not edit.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

# 77 upstream distfiles. Each `integrity` is vcpkg's own published
# SHA512 from the baseline-resolved portfile, hex->base64; nothing is
# re-hashed here, so this is not a trust downgrade.

def vcpkg_distfiles():
    http_file(
        name = 'vcpkg_AOMediaCodec_libavif_v1_4_2_tar_gz_cbf318278840',
        urls = ['https://github.com/AOMediaCodec/libavif/archive/v1.4.2.tar.gz'],
        downloaded_file_path = 'AOMediaCodec-libavif-v1.4.2.tar.gz',
        integrity = 'sha512-y/MYJ4hAWKzFTTsfoPIFnwImkWCaduD5E5gdW4wb5g9SBpolthyIjAnpYxYdH0yb9pLAcWqw7gZ6TMqk422c4Q==',  # captured
    )
    http_file(
        name = 'vcpkg_DetectSSE2_cmake_219a4c8591ee',
        urls = ['https://github.com/WebKit/WebKit/raw/0742522b24152262b04913242cb0b3c48de92ba0/Source/cmake/DetectSSE2.cmake'],
        downloaded_file_path = 'DetectSSE2.cmake',
        integrity = 'sha512-IZpMhZHuMdEes9HkgDzDydRXOYS7Jeysbyx25qPatZjACwFX0PlLGAFt5nhuSdiymhYWk6XOI9dhyP5qeYwbyg==',  # captured
    )
    http_file(
        name = 'vcpkg_GNOME_libxml2_v2_15_3_tar_gz_f65df793fca5',
        urls = ['https://github.com/GNOME/libxml2/archive/v2.15.3.tar.gz'],
        downloaded_file_path = 'GNOME-libxml2-v2.15.3.tar.gz',
        integrity = 'sha512-9l33k/yl5GVSr7qlawTEd0gpqV4BKm3E3D0Q5ohKYRjjCkJuQiUW4dIekcSh00ywClzuYa81yrA8cfubXAnhOA==',  # captured
    )
    http_file(
        name = 'vcpkg_GPUOpen_LibrariesAndSDKs_VulkanMemoryAllocator_v3_4_0_tar_gz_563acbcd8912',
        urls = ['https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/archive/v3.4.0.tar.gz'],
        downloaded_file_path = 'GPUOpen-LibrariesAndSDKs-VulkanMemoryAllocator-v3.4.0.tar.gz',
        integrity = 'sha512-VjrLzYkS0Q2SwjcV66es8OfBaDrzYCH0FbNvNZwszgZfOQbjlcMigqhBDsXIF5+8tkEpNcZimkk1dHXUtEEOKg==',  # captured
    )
    http_file(
        name = 'vcpkg_KhronosGroup_EGL_Registry_3ae2b7c48690d2ce13cc6db3db02dfc0572be65e_tar_gz_c7b09ded4964',
        urls = ['https://github.com/KhronosGroup/EGL-Registry/archive/3ae2b7c48690d2ce13cc6db3db02dfc0572be65e.tar.gz'],
        downloaded_file_path = 'KhronosGroup-EGL-Registry-3ae2b7c48690d2ce13cc6db3db02dfc0572be65e.tar.gz',
        integrity = 'sha512-x7Cd7Ulk+kJ1Rr00WikyUQW3kHm1lkIhTcjwTeET9C3ivEJy27vUqAHZKvwgKXRC/foSBDoJAM8eKxzYPyYIgw==',  # captured
    )
    http_file(
        name = 'vcpkg_KhronosGroup_OpenGL_Registry_0b449b97cdf1043eef5e1f0e235cbbab6ec10c86_tar_gz_148e1bfe4cc1',
        urls = ['https://github.com/KhronosGroup/OpenGL-Registry/archive/0b449b97cdf1043eef5e1f0e235cbbab6ec10c86.tar.gz'],
        downloaded_file_path = 'KhronosGroup-OpenGL-Registry-0b449b97cdf1043eef5e1f0e235cbbab6ec10c86.tar.gz',
        integrity = 'sha512-FI4b/kzBmbzCwjsi0LPkmIopOJ1/UQukpjQGctu3q5m7g20sCFh0mUhN9wTVGhrfTw3Dow1a2Jd+4K0zkWOxfg==',  # captured
    )
    http_file(
        name = 'vcpkg_KhronosGroup_Vulkan_Headers_vulkan_sdk_1_4_350_1_tar_gz_eee702ee5ff4',
        urls = ['https://github.com/KhronosGroup/Vulkan-Headers/archive/vulkan-sdk-1.4.350.1.tar.gz'],
        downloaded_file_path = 'KhronosGroup-Vulkan-Headers-vulkan-sdk-1.4.350.1.tar.gz',
        integrity = 'sha512-7ucC7l/0R5hpAeRJidlqXjj3739n4gFcjbYoAlHLI7acueGgVosKQ9w9+CBoUHntMZmKHcRwT1ZJdo4m21FHsQ==',  # captured
    )
    http_file(
        name = 'vcpkg_WebKitCompilerFlags_cmake_8b281ffcf920',
        urls = ['https://github.com/WebKit/WebKit/raw/0742522b24152262b04913242cb0b3c48de92ba0/Source/cmake/WebKitCompilerFlags.cmake'],
        downloaded_file_path = 'WebKitCompilerFlags.cmake',
        integrity = 'sha512-iygf/PkgnIRaX9rkik4F8Iymd8N6f7ANknDegb0QMWDSbgkXJM6N+NQorWBJALUgKyIf7Vuv/9S/AAJXGO+djg==',  # captured
    )
    http_file(
        name = 'vcpkg_WebKitMacros_cmake_565175443d5d',
        urls = ['https://github.com/WebKit/WebKit/raw/0742522b24152262b04913242cb0b3c48de92ba0/Source/cmake/WebKitMacros.cmake'],
        downloaded_file_path = 'WebKitMacros.cmake',
        integrity = 'sha512-VlF1RD1dG4EZr1BBZL+ThA6MeG/EeeRf65jKVCNRuR0uoAJl1/jfppYJdd6BgCvEOyoq8skPxEvaGuRtlsiSRw==',  # captured
    )
    http_file(
        name = 'vcpkg_abseil_abseil_cpp_20260107_1_tar_gz_f5012885d6b6',
        urls = ['https://github.com/abseil/abseil-cpp/archive/20260107.1.tar.gz'],
        downloaded_file_path = 'abseil-abseil-cpp-20260107.1.tar.gz',
        integrity = 'sha512-9QEohda2hEqc9e2SrVRouHV9sz3+E2S/sjL/+SjgbFUMfrRVf0UYaorE0YsXjfm+JnaBq6tKbeQII7V0r76ZYA==',  # captured
    )
    http_file(
        name = 'vcpkg_automake_1_17_tar_gz_11357dfab8cb',
        urls = ['https://ftpmirror.gnu.org/gnu/automake/automake-1.17.tar.gz', 'https://ftp.gnu.org/gnu/automake/automake-1.17.tar.gz', 'https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/automake/automake-1.17.tar.gz', 'https://mirrors.kernel.org/gnu/automake/automake-1.17.tar.gz'],
        downloaded_file_path = 'automake-1.17.tar.gz',
        integrity = 'sha512-ETV9+rjL9LXZTZ0G5HVzLKAd+CvvEoSIijS9VYr8N7GiOb7RtesYqdvMMmNE+3sbMB93u4OFEx644eEYtneIOg==',  # captured
    )
    http_file(
        name = 'vcpkg_bzip2_1_0_8_tar_gz_083f5e675d73',
        urls = ['https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz'],
        downloaded_file_path = 'bzip2-1.0.8.tar.gz',
        integrity = 'sha512-CD9eZ11z8yM8eTDr4gQlpTP+7eqqnYzIaDExKmWBzvvm7Q0I0vqJvoEILypavavKizwIC/lyGKG9WdwRijC58w==',  # captured
    )
    http_file(
        name = 'vcpkg_cisco_openh264_v2_6_0_tar_gz_26a03acde715',
        urls = ['https://github.com/cisco/openh264/archive/v2.6.0.tar.gz'],
        downloaded_file_path = 'cisco-openh264-v2.6.0.tar.gz',
        integrity = 'sha512-JqA6zecVOmtAuZ8AZBdyQzokTHKjzEvKbZA887dwF00Cg2mi+3Oy8HdOESTbDiaXWO7W2Il1NHqBXgNmyCDSRw==',  # captured
    )
    http_file(
        name = 'vcpkg_cmake_4_4_0_linux_x86_64_tar_gz_3df4aaa128a4',
        urls = ['https://github.com/Kitware/CMake/releases/download/v4.4.0/cmake-4.4.0-linux-x86_64.tar.gz'],
        downloaded_file_path = 'cmake-4.4.0-linux-x86_64.tar.gz',
        integrity = 'sha512-PfSqoSikOO1I3KxwZf01X/U47tjzlEkSmNDbY6iR1nHaJHyPomLk+mv5lCnWMKurMX1aAkgWj+ID0cpJeNq02g==',  # captured
    )
    http_file(
        name = 'vcpkg_curl_curl_curl_8_21_0_tar_gz_0ab6c99c3d5b',
        urls = ['https://github.com/curl/curl/archive/curl-8_21_0.tar.gz'],
        downloaded_file_path = 'curl-curl-curl-8_21_0.tar.gz',
        integrity = 'sha512-CrbJnD1bhvtlxSbbUXwxWbEdsvjYJVLWNcSIcFnAYCKIYDyTt1TODsVD6i8nUSLM7CyNzYZsJhG1uUnHKO5y3w==',  # captured
    )
    http_file(
        name = 'vcpkg_davea42_libdwarf_code_v2_3_1_tar_gz_e8eb74c622ce',
        urls = ['https://github.com/davea42/libdwarf-code/archive/v2.3.1.tar.gz'],
        downloaded_file_path = 'davea42-libdwarf-code-v2.3.1.tar.gz',
        integrity = 'sha512-6Ot0xiLO21Etgt/zE86cWsIGSnp6BpHHdiE7OEwcZND1SaqrHvcy3LqMctUgSM6mQdmQnTslA8+WdgrY6BrnfA==',  # captured
    )
    http_file(
        name = 'vcpkg_dbus_dbus_dbus_1_16_2_tar_gz_8ad3ab55bf6e',
        urls = ['https://gitlab.freedesktop.org//dbus/dbus/-/archive/dbus-1.16.2/dbus-dbus-1.16.2.tar.gz'],
        downloaded_file_path = 'dbus-dbus-dbus-1.16.2.tar.gz',
        integrity = 'sha512-itOrVb9uK75v+HEwLChAwMuCtOx4WwXxRsV3yh6TGCUIQBKskCUeKMMORNER5cpXEbKTSfTw5ooJukk5LmOsiQ==',  # captured
    )
    http_file(
        name = 'vcpkg_facebook_zstd_v1_5_7_tar_gz_26e441267305',
        urls = ['https://github.com/facebook/zstd/archive/v1.5.7.tar.gz'],
        downloaded_file_path = 'facebook-zstd-v1.5.7.tar.gz',
        integrity = 'sha512-JuRBJnMF9uWAgEYPlquYZFIZqQ0pClM0ELGwsdL4cHIclfg4TjQu5kfF6Wg4Wlt+MMLQQ0DDf1mz5thnYsMmDA==',  # captured
    )
    http_file(
        name = 'vcpkg_fastfloat_fast_float_v8_2_10_tar_gz_eec563358117',
        urls = ['https://github.com/fastfloat/fast_float/archive/v8.2.10.tar.gz'],
        downloaded_file_path = 'fastfloat-fast_float-v8.2.10.tar.gz',
        integrity = 'sha512-7sVjNYEXtZPogqkGkHSiadgR6JiUV6DVflDF0vTVNLaCAwgIK7cMCoqDiFE+krZPEsUhM4nv9yatBIPqy6lh/w==',  # captured
    )
    http_file(
        name = 'vcpkg_ffmpeg_ffmpeg_n7_1_1_tar_gz_6b9a5ee501be',
        urls = ['https://github.com/ffmpeg/ffmpeg/archive/n7.1.1.tar.gz'],
        downloaded_file_path = 'ffmpeg-ffmpeg-n7.1.1.tar.gz',
        integrity = 'sha512-a5pe5QG+Qdarx1eaEGJjsx94cyHLxF3t7per+ZK/gjbNsjlFcd0lanQVT0ogAY1Cmufn8ECWEd3E1vUp2STRdQ==',  # captured
    )
    http_file(
        name = 'vcpkg_fmt_backport_4813_patch_afda8fdfcdcb',
        urls = ['https://github.com/fmtlib/fmt/commit/588b3a0f8f6a8bcf2a959cae882d5b2703e86737.patch?full_index=1'],
        downloaded_file_path = 'fmt-backport-4813.patch',
        integrity = 'sha512-r9qP383LSw3V301NrpaleoX7nEtl0LSdUSWPCRPUrtk+0Ubr+W7XsndJCx3ebHEX9DMyATBxRBqWwxR1IN6DaA==',  # captured
    )
    http_file(
        name = 'vcpkg_fmtlib_fmt_12_2_0_tar_gz_5ac2ba0f54a4',
        urls = ['https://github.com/fmtlib/fmt/archive/12.2.0.tar.gz'],
        downloaded_file_path = 'fmtlib-fmt-12.2.0.tar.gz',
        integrity = 'sha512-WsK6D1SkhJme1UB9grd6rRcM6kmiZ97NLA7trfOxRBPiqD/MjpypwWZAWV4Bm4Y24WD3IxTYvlBlMyToKsdF6w==',  # captured
    )
    http_file(
        name = 'vcpkg_fontconfig_fontconfig_2_17_1_tar_gz_8e05cad63cd0',
        urls = ['https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.17.1/fontconfig-2.17.1.tar.gz'],
        downloaded_file_path = 'fontconfig-fontconfig-2.17.1.tar.gz',
        integrity = 'sha512-jgXK1jzQxcoV0TWeGaYFkSGY/MDsbswR1aDvWW1y55XNgSjk01BxbmPLwBYSw4B7FFW4FTkBMzeQMWFwye+OdQ==',  # captured
    )
    http_file(
        name = 'vcpkg_freetype_freetype_VER_2_13_3_tar_gz_fccfaa15eb79',
        urls = ['https://gitlab.freedesktop.org//freetype/freetype/-/archive/VER-2-13-3/freetype-VER-2-13-3.tar.gz'],
        downloaded_file_path = 'freetype-freetype-VER-2-13-3.tar.gz',
        integrity = 'sha512-/M+qFet5oQWYG/Y03zSsnd8cU1UOwLM0kDobIfn4v16ys/lHblVK+hEqD8pY7IWrIS1nTf2FNnDv7IdrrL6KUw==',  # captured
    )
    http_file(
        name = 'vcpkg_giflib_6_1_3_tar_gz_fb1d63196947',
        urls = ['https://sourceforge.net/projects/giflib/files/giflib-6.1.3.tar.gz/download'],
        downloaded_file_path = 'giflib-6.1.3.tar.gz',
        integrity = 'sha512-+x1jGWlHRejNrHxX6WvTqH2/2Xjyv9AOgmdC21M5gBHEP5puf0N1sOd7FiNY3foU2FvOZSaA+1lntyxGd1wO2w==',  # captured
    )
    http_file(
        name = 'vcpkg_gn_linux_amd64_zip_d49575bd383b',
        urls = ['https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/fj2NZKMkIYZNH6uYG0bn8OsW_lZB5JKz3JeScMCLAGQC'],
        downloaded_file_path = 'gn-linux-amd64.zip',
        integrity = 'sha512-1JV1vTg7aqzhJXpulDnOCiBhc+wsq5TVMS8G20EuCciap1sfTGn13KQ4nRWkicIRpzQ5pm9DfDSxi8kO76C3dQ==',  # captured
    )
    http_file(
        name = 'vcpkg_gni_to_cmake_py_cf9dab1b59cd',
        urls = ['https://github.com/WebKit/WebKit/raw/0742522b24152262b04913242cb0b3c48de92ba0/Source/ThirdParty/ANGLE/gni-to-cmake.py'],
        downloaded_file_path = 'gni-to-cmake.py',
        integrity = 'sha512-z52rG1nNRLnOBaLcRjYRXncN/n1c+9kMP+9lliisgVXFe4ZkgPfP6aCv6zH/XOXu10Rz84YSCn/FkQ6LAyvWHQ==',  # captured
    )
    http_file(
        name = 'vcpkg_google_angle_79ac1a8cd767a32cce6401203e20c4bd4ca4d539_tar_gz_a3d5d09460f0',
        urls = ['https://github.com/google/angle/archive/79ac1a8cd767a32cce6401203e20c4bd4ca4d539.tar.gz'],
        downloaded_file_path = 'google-angle-79ac1a8cd767a32cce6401203e20c4bd4ca4d539.tar.gz',
        integrity = 'sha512-o9XQlGDwXx8cCBQRvxX1hbuK3V89t8SFTcLPLvH9It1bLdXT3ni/uLza6EWd2Vgffc4zGs00BTyHyEz+bD0TTA==',  # captured
    )
    http_file(
        name = 'vcpkg_google_brotli_v1_2_0_tar_gz_f94542afd2ec',
        urls = ['https://github.com/google/brotli/archive/v1.2.0.tar.gz'],
        downloaded_file_path = 'google-brotli-v1.2.0.tar.gz',
        integrity = 'sha512-+UVCr9Ls2WzEH9IagFo9oxQoGuVYwQZQ8+bZynMrhCW7qP3jEoI/ClZMfeOZO9qrW0M3jtq2Xrt5jO+2/XAiVg==',  # captured
    )
    http_file(
        name = 'vcpkg_google_highway_1_4_0_tar_gz_819422857d6a',
        urls = ['https://github.com/google/highway/archive/1.4.0.tar.gz'],
        downloaded_file_path = 'google-highway-1.4.0.tar.gz',
        integrity = 'sha512-gZQihX1qdOOpNsQCaY4HjbW3uI+0N2fmJCnse9lU/pOwF+dQKaTfShqX7zokhhB+71JH2nUetIdkDepAnz8vog==',  # captured
    )
    http_file(
        name = 'vcpkg_google_skia_e7c90ecca9444fe09598f1630ab7cee2c0ee027a_tar_gz_f52286fcac1d',
        urls = ['https://github.com/google/skia/archive/e7c90ecca9444fe09598f1630ab7cee2c0ee027a.tar.gz'],
        downloaded_file_path = 'google-skia-e7c90ecca9444fe09598f1630ab7cee2c0ee027a.tar.gz',
        integrity = 'sha512-9SKG/KwdGytFBG199yzuOEtmTwtRLEtKdrynQ3R/IRP+9pkQWbTnGtgE0CCRAwA7oPAaqQr6x4beIKUuhIQBjQ==',  # captured
    )
    http_file(
        name = 'vcpkg_google_woff2_v1_0_2_tar_gz_c788bba1530a',
        urls = ['https://github.com/google/woff2/archive/v1.0.2.tar.gz'],
        downloaded_file_path = 'google-woff2-v1.0.2.tar.gz',
        integrity = 'sha512-x4i7oVMK7EY+dV6QH5NC9LWZ46B/VGRf7x3DiKtdXDBiVTXl3Tjp55LgSmQFdLqlDu77a3M4q0A3VfSk4MMETQ==',  # captured
    )
    http_file(
        name = 'vcpkg_google_wuffs_mirror_release_c_v0_3_4_tar_gz_d22136a1adf3',
        urls = ['https://github.com/google/wuffs-mirror-release-c/archive/v0.3.4.tar.gz'],
        downloaded_file_path = 'google-wuffs-mirror-release-c-v0.3.4.tar.gz',
        integrity = 'sha512-0iE2oa3zN1c5RO7ZFxQsa96Hegm9ZXOAEMbDZ8ej/J5Fc/1NyEack3mf4eMkd2DmXmSCnoMIce57Mz/XLrxinQ==',  # captured
    )
    http_file(
        name = 'vcpkg_gperf_3_3_tar_gz_246b75b8ce7d',
        urls = ['https://ftpmirror.gnu.org/gnu/gperf/gperf-3.3.tar.gz', 'https://ftp.gnu.org/gnu/gperf/gperf-3.3.tar.gz', 'https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/gperf/gperf-3.3.tar.gz', 'https://mirrors.kernel.org/gnu/gperf/gperf-3.3.tar.gz'],
        downloaded_file_path = 'gperf-3.3.tar.gz',
        integrity = 'sha512-JGt1uM59d9aoclzRXxzy5o2kBIElc68dW/MtvmrUIo9IdXuu/He8sfVZfCOXBDwE0x2KBKtQe/p6gPheGrYEXw==',  # captured
    )
    http_file(
        name = 'vcpkg_harfbuzz_harfbuzz_10_2_0_tar_gz_697205a571bb',
        urls = ['https://github.com/harfbuzz/harfbuzz/archive/10.2.0.tar.gz'],
        downloaded_file_path = 'harfbuzz-harfbuzz-10.2.0.tar.gz',
        integrity = 'sha512-aXIFpXG7PVLYNZjoUR4uIefNFWMKrDLY3rQ1TkYu/aalzkZRDPShwYNl3/6TXPLk8f2mXRd58XybtgxQMxW/XA==',  # captured
    )
    http_file(
        name = 'vcpkg_icu4c_78_3_sources_tgz_04a49455e148',
        urls = ['https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz'],
        downloaded_file_path = 'icu4c-78.3-sources.tgz',
        integrity = 'sha512-BKSUVeFIkDDFIKS/0mZPohceeTjQjyrNu8sf2pdmOf2LHwcE8u7Im6Wae20RjOqrbsWgluQNkIWgiV2RziJSRQ==',  # captured
    )
    http_file(
        name = 'vcpkg_include_CMakeLists_txt_a7ddf3c6df75',
        urls = ['https://github.com/WebKit/WebKit/raw/0742522b24152262b04913242cb0b3c48de92ba0/Source/ThirdParty/ANGLE/include/CMakeLists.txt'],
        downloaded_file_path = 'include_CMakeLists.txt',
        integrity = 'sha512-p93zxt91ZeIy+H7GUcxP2EJAuIZmCeI+Pm5B0iUy/TTHDg87BhIP09bZMMopwdDUcNTIy3ADpm+MGoQKQvMpSQ==',  # captured
    )
    http_file(
        name = 'vcpkg_jeremy_rifkin_cpptrace_v1_0_2_tar_gz_4ae394fb3c21',
        urls = ['https://github.com/jeremy-rifkin/cpptrace/archive/v1.0.2.tar.gz'],
        downloaded_file_path = 'jeremy-rifkin-cpptrace-v1.0.2.tar.gz',
        integrity = 'sha512-SuOU+zwhFJvyRBp1TuvmOealU0knQmtlB4Bse+4LHJguBHyXKQTUcvHGYK21vjiB5+Om7d0Y5OnTdq44VdUKfA==',  # captured
    )
    http_file(
        name = 'vcpkg_libedit_20240808_3_1_tar_gz_b11d64947f94',
        urls = ['https://thrysoee.dk/editline/libedit-20240808-3.1.tar.gz'],
        downloaded_file_path = 'libedit-20240808-3.1.tar.gz',
        integrity = 'sha512-sR1klH+UhLsjILD7z9yURmmTrx36DYU4U7c8Ii6V1sHnjYjQwwWSm5W/eoUAkSlHXJ/vCshZW0PXVUPYUFKk/w==',  # captured
    )
    http_file(
        name = 'vcpkg_libexpat_libexpat_R_2_8_2_tar_gz_e60e6d6ae9d0',
        urls = ['https://github.com/libexpat/libexpat/archive/R_2_8_2.tar.gz'],
        downloaded_file_path = 'libexpat-libexpat-R_2_8_2.tar.gz',
        integrity = 'sha512-5g5taunQEV9BGG8G84VACAVIY/CymljUQUL1swBXpJQzcUXYILXhgnC4yj53njGKdX/Ma/ZNbSBOVJjfXushlQ==',  # captured
    )
    http_file(
        name = 'vcpkg_libidn2_2_3_7_tar_gz_eab5702bc0ba',
        urls = ['https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/libidn/libidn2-2.3.7.tar.gz', 'https://ftpmirror.gnu.org/gnu/libidn/libidn2-2.3.7.tar.gz', 'https://ftp.gnu.org/gnu/libidn/libidn2-2.3.7.tar.gz', 'https://mirrors.kernel.org/gnu/libidn/libidn2-2.3.7.tar.gz'],
        downloaded_file_path = 'libidn2-2.3.7.tar.gz',
        integrity = 'sha512-6rVwK8C67UVJL43eQ6TS6jVgrYBkXl+eDPqNO1e8zX/XgtBGOOAAugeSSl2fhedgCVtVGJGIxAF7lHBb75tKZg==',  # captured
    )
    http_file(
        name = 'vcpkg_libjpeg_turbo_libjpeg_turbo_3_2_0_tar_gz_1ce063e9e126',
        urls = ['https://github.com/libjpeg-turbo/libjpeg-turbo/archive/3.2.0.tar.gz'],
        downloaded_file_path = 'libjpeg-turbo-libjpeg-turbo-3.2.0.tar.gz',
        integrity = 'sha512-HOBj6eEm1VAZOF2jpv9FIamjlY7eqxXiRlrjQ1Am2sblmCd+6gZhc62kfaNxWdD3gSsiJ4acEN0UHc/i3eq3IA==',  # captured
    )
    http_file(
        name = 'vcpkg_libjxl_libjxl_v0_11_2_tar_gz_a7e1f7d060b3',
        urls = ['https://github.com/libjxl/libjxl/archive/v0.11.2.tar.gz'],
        downloaded_file_path = 'libjxl-libjxl-v0.11.2.tar.gz',
        integrity = 'sha512-p+H30GCzWPQ4LoQ2fWaqKFCu87RSSg/f4/It0lj7njXdp1QPhZ2L9MMvMcYaegPbZ39EkKn0cs0lhpqdAHlzNg==',  # captured
    )
    http_file(
        name = 'vcpkg_libpng_1_6_58_apng_patch_gz_95a6f5bb7148',
        urls = ['https://downloads.sourceforge.net/project/libpng-apng/libpng16/1.6.58/libpng-1.6.58-apng.patch.gz'],
        downloaded_file_path = 'libpng-1.6.58-apng.patch.gz',
        integrity = 'sha512-lab1u3FItcSNzNc4Ede8+XUqYxp7tPSFZnCn2hKnFZWBrBvOF0kxg0N5Tg9cuGlycRui7A9SPBaPCZH6lAaH1Q==',  # captured
    )
    http_file(
        name = 'vcpkg_libproxy_libproxy_0_4_18_tar_gz_1148d688a9f0',
        urls = ['https://github.com/libproxy/libproxy/archive/0.4.18.tar.gz'],
        downloaded_file_path = 'libproxy-libproxy-0.4.18.tar.gz',
        integrity = 'sha512-EUjWiKnwcCc6GisRCniFYXiXmQiWYCkru6Wfvwqcr30oywOanM3Lk191Lh40c5stL0x4Sxuzu6oD0Qjns4pHVA==',  # captured
    )
    http_file(
        name = 'vcpkg_libpsl_public_suffix_list_0ed17e_dat_7969c40b0600',
        urls = ['https://raw.githubusercontent.com/publicsuffix/list/0ed17ee161ed2ae551c78f3b399ac8f2724d2154/public_suffix_list.dat'],
        downloaded_file_path = 'libpsl-public_suffix_list-0ed17e.dat',
        integrity = 'sha512-eWnECwYAuvJ4avDmUDtCgtSHtmA0GMQfKMOznpzZMgrGbA0uj7+it5TkYfJoQ+NHnWDsJKxcCZD+jwxr+u7mnQ==',  # captured
    )
    http_file(
        name = 'vcpkg_libsdl_org_SDL_release_3_2_28_tar_gz_9e188c992caa',
        urls = ['https://github.com/libsdl-org/SDL/archive/release-3.2.28.tar.gz'],
        downloaded_file_path = 'libsdl-org-SDL-release-3.2.28.tar.gz',
        integrity = 'sha512-nhiMmSyqf3/wMHifeSYAfSJy9RtMOqf8lPWPaCOBC95xzhSZkMeO7kfyZHHfKnuH1PwliBwzntICax5ZBSvOOQ==',  # captured
    )
    http_file(
        name = 'vcpkg_libtiff_libtiff_v4_7_2_tar_gz_c4dcde3c79e5',
        urls = ['https://gitlab.com/libtiff/libtiff/-/archive/v4.7.2/libtiff-v4.7.2.tar.gz'],
        downloaded_file_path = 'libtiff-libtiff-v4.7.2.tar.gz',
        integrity = 'sha512-xNzePHnl1pxyMfiGLi5ag9kNnM5pT7KkgEgAsvjxvJ21BLklLYHc6HLuyDWLM6Oh293cu2GB9vuNHX/A6an8ag==',  # captured
    )
    http_file(
        name = 'vcpkg_libtom_libtommath_v1_3_0_tar_gz_3dbd7053a670',
        urls = ['https://github.com/libtom/libtommath/archive/v1.3.0.tar.gz'],
        downloaded_file_path = 'libtom-libtommath-v1.3.0.tar.gz',
        integrity = 'sha512-Pb1wU6Zwr6VjoGmpeF8apMqxSiELzQXY/H2yW9PczjaxCj9PVMqS11ppT4kSJvAb32rBW6yv65OovmsExXm+sw==',  # captured
    )
    http_file(
        name = 'vcpkg_libunistring_1_2_tar_xz_5fbb5a0a864d',
        urls = ['https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/libunistring/libunistring-1.2.tar.xz', 'https://ftpmirror.gnu.org/gnu/libunistring/libunistring-1.2.tar.xz', 'https://ftp.gnu.org/gnu/libunistring/libunistring-1.2.tar.xz', 'https://mirrors.kernel.org/gnu/libunistring/libunistring-1.2.tar.xz'],
        downloaded_file_path = 'libunistring-1.2.tar.xz',
        integrity = 'sha512-X7taCoZNtzptGM3qezEjfakH//DvKI86jbbr26jvYa2IVeX8eAwrv2MiGNj6Wd0RlzTlk3ymTcd/U/MPE7gLFw==',  # captured
    )
    http_file(
        name = 'vcpkg_libuuid_1_0_3_tar_gz_77488caccc66',
        urls = ['https://sourceforge.net/projects/libuuid/files/libuuid-1.0.3.tar.gz/download'],
        downloaded_file_path = 'libuuid-1.0.3.tar.gz',
        integrity = 'sha512-d0iMrMxmUD9vLe1738TTvCwgskqNyVsgUWM8aV6Z7CeHb/uv44JpuTmCbh/bBu6jKPB7eWyeCqyhIzGnhxdVBw==',  # captured
    )
    http_file(
        name = 'vcpkg_madler_zlib_v1_3_1_tar_gz_8c9642495baf',
        urls = ['https://github.com/madler/zlib/archive/v1.3.1.tar.gz'],
        downloaded_file_path = 'madler-zlib-v1.3.1.tar.gz',
        integrity = 'sha512-jJZCSVuv1vrUq5+2fwmyaMaf+a8PTyDPFd/BiFL/HzEr2MpB3nYbP42OkOd9efLMrNPUxbGeR17PCdAh/f6QiA==',  # captured
    )
    http_file(
        name = 'vcpkg_meson_1_9_0_tar_gz_ecd69b6734be',
        urls = ['https://github.com/mesonbuild/meson/archive/1.9.0.tar.gz'],
        downloaded_file_path = 'meson-1.9.0.tar.gz',
        integrity = 'sha512-7NabZzS+FMRn99tn3YjA5X6/rYPOPdraEx/z5DrJZFI+EIPXx/OAMDOpp2rbwyrSbdLjrKaYhCaQAMpkEwveBw==',  # captured
    )
    http_file(
        name = 'vcpkg_microsoft_mimalloc_v2_2_7_tar_gz_19f5481c9882',
        urls = ['https://github.com/microsoft/mimalloc/archive/v2.2.7.tar.gz'],
        downloaded_file_path = 'microsoft-mimalloc-v2.2.7.tar.gz',
        integrity = 'sha512-GfVIHJiCLGonni8tJtbFSRjhi8r9UVp2yjo4RfOl5ZkjbqBC+cra95Pc4MHt40fXbML8VQMJQog2KngDTU2PcQ==',  # captured
    )
    http_file(
        name = 'vcpkg_mm2_Little_CMS_lcms2_19_1_tar_gz_1b2781ed8898',
        urls = ['https://github.com/mm2/Little-CMS/archive/lcms2.19.1.tar.gz'],
        downloaded_file_path = 'mm2-Little-CMS-lcms2.19.1.tar.gz',
        integrity = 'sha512-GyeB7YiY5l8VvhfPATChUA7Av1ylFZ+HHf9WkuOHdHvpUm/u8Lx8NwIAZW/Aqr4wNnRgQShaOXjpCt7CANaF8g==',  # captured
    )
    http_file(
        name = 'vcpkg_nghttp2_nghttp2_v1_69_0_tar_gz_1029fb86935a',
        urls = ['https://github.com/nghttp2/nghttp2/archive/v1.69.0.tar.gz'],
        downloaded_file_path = 'nghttp2-nghttp2-v1.69.0.tar.gz',
        integrity = 'sha512-ECn7hpNaiPxRjMLZdt/1JTJ3+X4B8ysfc8Xfltz3/gKAqDqenWdsPZbKpUIwDcfPph8qQLGxHSwrUn6HCpdLUw==',  # captured
    )
    http_file(
        name = 'vcpkg_ngtcp2_nghttp3_v1_17_0_tar_gz_23d85a2abfa8',
        urls = ['https://github.com/ngtcp2/nghttp3/archive/v1.17.0.tar.gz'],
        downloaded_file_path = 'ngtcp2-nghttp3-v1.17.0.tar.gz',
        integrity = 'sha512-I9haKr+oFDMEnXsbBEC1sErjUVgw2wNH2jNaMLk8i+jiXS9z4ZjNuSB+K1HOkk8TO6tzFM3nbYD3PFHB/Rw2xA==',  # captured
    )
    http_file(
        name = 'vcpkg_ngtcp2_ngtcp2_v1_24_0_tar_gz_04a5762d6eac',
        urls = ['https://github.com/ngtcp2/ngtcp2/archive/v1.24.0.tar.gz'],
        downloaded_file_path = 'ngtcp2-ngtcp2-v1.24.0.tar.gz',
        integrity = 'sha512-BKV2LW6scidDHrjik9J4be6ffQRnpYS9019OM8fG/257AQ5uiU+r33gPY3c3NinBCk1B7/o3TiEp2fmx5TeHPg==',  # captured
    )
    http_file(
        name = 'vcpkg_ngtcp2_sfparse_f2046eaa1acba7c5467399b1e1e1f354d22d1f48_tar_gz_b3cbcce6d96d',
        urls = ['https://github.com/ngtcp2/sfparse/archive/f2046eaa1acba7c5467399b1e1e1f354d22d1f48.tar.gz'],
        downloaded_file_path = 'ngtcp2-sfparse-f2046eaa1acba7c5467399b1e1e1f354d22d1f48.tar.gz',
        integrity = 'sha512-s8vM5tltxzHSGmeUCgXBYD1D7pdmgZ4dF0ypPHr8f6YkeqgYNoyvuzFETgGYq1u6RYCHcqPKieRZ+NLA/65vXQ==',  # captured
    )
    http_file(
        name = 'vcpkg_ninja_linux_1_13_2_zip_714b900cf10b',
        urls = ['https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-linux.zip'],
        downloaded_file_path = 'ninja-linux-1.13.2.zip',
        integrity = 'sha512-cUuQDPELfssbZByR9O9pYlDGSYTllVqAiOSlONboB39D5V9tpH787b4xbGjVGp6Y/v9Rc06w6sGxeqha9WmHUw==',  # vcpkg-tool
    )
    http_file(
        name = 'vcpkg_openssl_openssl_openssl_3_6_3_tar_gz_a89c08101fa1',
        urls = ['https://github.com/openssl/openssl/archive/openssl-3.6.3.tar.gz'],
        downloaded_file_path = 'openssl-openssl-openssl-3.6.3.tar.gz',
        integrity = 'sha512-qJwIEB+h1+PAmxT0qQ1FC88zak9qPm5OqZDk3t3NnOJQRy+RFEOP0TT/S0f+k91HIyMIVnCIsrHAsutQ47Vr3w==',  # captured
    )
    http_file(
        name = 'vcpkg_patchelf_0_19_0_x86_64_tar_gz_2a65c9cbdddc',
        urls = ['https://github.com/NixOS/patchelf/releases/download/0.19.0/patchelf-0.19.0-x86_64.tar.gz'],
        downloaded_file_path = 'patchelf-0.19.0-x86_64.tar.gz',
        integrity = 'sha512-KmXJy93cx5Us29bpiizz2gE4bPDwuSemu8/oEx7PC/sXxTQkZjW15qCQZS7lTJA/n5xPPx0kEtulnyh64q6AcA==',  # captured
    )
    http_file(
        name = 'vcpkg_pdfjs_5_6_205_dist_zip_66fecdb8a80d',
        urls = ['https://github.com/mozilla/pdf.js/releases/download/v5.6.205/pdfjs-5.6.205-dist.zip'],
        downloaded_file_path = 'pdfjs-5.6.205-dist.zip',
        integrity = 'sha512-Zv7NuKgNATtZLDYehavX7upbw18BMbdxzCWhh413N3BEWNxxVnCqzjx9NDf4U4jf8EeW/hF+7wG+gf0NGS9zog==',  # captured
    )
    http_file(
        name = 'vcpkg_pkgconf_pkgconf_pkgconf_3_0_3_tar_gz_4e49bb7b10c6',
        urls = ['https://github.com/pkgconf/pkgconf/archive/pkgconf-3.0.3.tar.gz'],
        downloaded_file_path = 'pkgconf-pkgconf-pkgconf-3.0.3.tar.gz',
        integrity = 'sha512-Tkm7exDG/ev6EXW0wzE4uK7KJYLkmttce6ZtCOhhR3HvBgsMJnO9CYwa7YIcit4abdJ2wfSsbim9fvy49MBALg==',  # captured
    )
    http_file(
        name = 'vcpkg_pnggroup_libpng_v1_6_58_tar_gz_65f54d805e1f',
        urls = ['https://github.com/pnggroup/libpng/archive/v1.6.58.tar.gz'],
        downloaded_file_path = 'pnggroup-libpng-v1.6.58.tar.gz',
        integrity = 'sha512-ZfVNgF4ffEal/DNbmE5MvU+TTg8C+/ZnPBOAC0mkwR++tAmO6/szB5UnpWw9kz6XYx+Rq2jbsxRCmCeE+SQazg==',  # captured
    )
    http_file(
        name = 'vcpkg_rockdaboot_libpsl_0_21_5_tar_gz_d8e224b2ce5d',
        urls = ['https://github.com/rockdaboot/libpsl/archive/0.21.5.tar.gz'],
        downloaded_file_path = 'rockdaboot-libpsl-0.21.5.tar.gz',
        integrity = 'sha512-2OIkss5dmmrHhwDriXXQmu9OWvfbKVOeXjOcXNEA8Scjcf5FdXq1OD3bzVab351peniTLqn99D/0jTzqAvZEzQ==',  # captured
    )
    http_file(
        name = 'vcpkg_simdjson_simdjson_v4_6_4_tar_gz_003b96daab30',
        urls = ['https://github.com/simdjson/simdjson/archive/v4.6.4.tar.gz'],
        downloaded_file_path = 'simdjson-simdjson-v4.6.4.tar.gz',
        integrity = 'sha512-ADuW2qswzK79rGCpZ2z2I69ahmIBb5iPwOyqLzbYtIupfyQx5kmN0W/CsdhBeYstBtq7C3SH79RSDA3iYOSQVg==',  # captured
    )
    http_file(
        name = 'vcpkg_simdutf_simdutf_v9_0_0_tar_gz_0c74226247cb',
        urls = ['https://github.com/simdutf/simdutf/archive/v9.0.0.tar.gz'],
        downloaded_file_path = 'simdutf-simdutf-v9.0.0.tar.gz',
        integrity = 'sha512-DHQiYkfL6VNo76h6uE9SF0hfFrzfep3vh0HGCGy4bmw3jwxDcDDSvgk0cm4+qcKLXfLlk9DGVMeCkcRVqNHhAw==',  # captured
    )
    http_file(
        name = 'vcpkg_sqlite_autoconf_3530300_tar_gz_355a8db490ec',
        urls = ['https://sqlite.org/2026/sqlite-autoconf-3530300.tar.gz'],
        downloaded_file_path = 'sqlite-autoconf-3530300.tar.gz',
        integrity = 'sha512-NVqNtJDsKmjCgBZE5WF4omQWw1V5JYamwckE3hFuJvhgK8NE5xchgcnZLEyeaWMZJD4WQFRg+th7I+6Zej752g==',  # captured
    )
    http_file(
        name = 'vcpkg_tukaani_project_xz_v5_8_3_tar_gz_8fb5e6a13397',
        urls = ['https://github.com/tukaani-project/xz/archive/v5.8.3.tar.gz'],
        downloaded_file_path = 'tukaani-project-xz-v5.8.3.tar.gz',
        integrity = 'sha512-j7XmoTOX0lnY/3SE+bY/imdS/xxj4aRgEXCtgXWq3vtRJqHK5/czcL/GwqC04cC61XpY/Ft4HT99ReWkg8CRzA==',  # captured
    )
    http_file(
        name = 'vcpkg_videolan_dav1d_1_5_3_tar_gz_8d976b931352',
        urls = ['https://github.com/videolan/dav1d/archive/1.5.3.tar.gz'],
        downloaded_file_path = 'videolan-dav1d-1.5.3.tar.gz',
        integrity = 'sha512-jZdrkxNSE9QThcICBUdSaaaCamjr/XFsTZp6P/KnlwPo3wVz5DIHyBtdtEgH0nIdsY7ITA/GvvmO+rhqLMy2zA==',  # captured
    )
    http_file(
        name = 'vcpkg_webmproject_libvpx_v1_16_0_tar_gz_07f5e352411d',
        urls = ['https://github.com/webmproject/libvpx/archive/v1.16.0.tar.gz'],
        downloaded_file_path = 'webmproject-libvpx-v1.16.0.tar.gz',
        integrity = 'sha512-B/XjUkEdbAvjMXBtGDWsibr77dy7rFVCtHMyN2bp6XT09oszWQ8qpQp9jWlGimQrUIy7CnxJqCyZM7B4IPnJ2Q==',  # captured
    )
    http_file(
        name = 'vcpkg_webmproject_libwebp_v1_6_0_tar_gz_298e0ad4c093',
        urls = ['https://github.com/webmproject/libwebp/archive/v1.6.0.tar.gz'],
        downloaded_file_path = 'webmproject-libwebp-v1.6.0.tar.gz',
        integrity = 'sha512-KY4K1MCTkiE7r1q7adMwxiA7YYgABz/i35HQHTUDQZfF0+KadFc7BpcUc8UsdFFPDm4PbIFi+SPi3RXLGmkq7w==',  # captured
    )
    http_file(
        name = 'vcpkg_xiph_ogg_v1_3_6_tar_gz_c247e1da8b12',
        urls = ['https://github.com/xiph/ogg/archive/v1.3.6.tar.gz'],
        downloaded_file_path = 'xiph-ogg-v1.3.6.tar.gz',
        integrity = 'sha512-wkfh2osS+LMycvr7bXwXGhomh8NjKXdDn6YLlszCrXUdiKKTG7Phjh3fLuougs3QqrCHsuxTk6kijHA0dvoBZw==',  # captured
    )
    http_file(
        name = 'vcpkg_xiph_opus_v1_5_2_tar_gz_4ffefd9c0356',
        urls = ['https://github.com/xiph/opus/archive/v1.5.2.tar.gz'],
        downloaded_file_path = 'xiph-opus-v1.5.2.tar.gz',
        integrity = 'sha512-T/79nANWcQJPlyDFEpv+OV3qBPDWtzAEHCgE6JsdtuTRljOtGuWIVa/DVQNCM1NzYecH8m3FOtrJFlVIMAOPqw==',  # captured
    )
    http_file(
        name = 'vcpkg_xiph_theora_v1_2_0_tar_gz_b2aac15528f0',
        urls = ['https://github.com/xiph/theora/archive/v1.2.0.tar.gz'],
        downloaded_file_path = 'xiph-theora-v1.2.0.tar.gz',
        integrity = 'sha512-sqrBVSjw74JYwJAuM+ghHohYw8fm6e63CMzlki3l8OQSJV3a9UClDA6/YB32xDdv0koL3X+N5EMsSubl1v/itg==',  # captured
    )
    http_file(
        name = 'vcpkg_xiph_vorbis_v1_3_7_tar_gz_bfb6f5dbfd49',
        urls = ['https://github.com/xiph/vorbis/archive/v1.3.7.tar.gz'],
        downloaded_file_path = 'xiph-vorbis-v1.3.7.tar.gz',
        integrity = 'sha512-v7b12/1J7TiysIs2Z8BtAuaPZJBooFDyGjzH4eVrJ6/VRqqjGZxPZEjwP25mqC+ancIkHIJtPR1Ky9ODObnp+w==',  # captured
    )
