# AUTO-GENERATED by Meta/emit_vcpkg_bazel.py — do not edit.
load(":vcpkg_distfiles.bzl", "vcpkg_distfiles")

def _vcpkg_deps_impl(_ctx):
    vcpkg_distfiles()

vcpkg_deps = module_extension(implementation = _vcpkg_deps_impl)
