#!/usr/bin/env python3
"""Emit Bazel genrules for Ladybird's Python-generator CUSTOM_COMMANDs.

Extracts each generator invocation from Build/full/build.ninja and rewrites it
as a Bazel genrule whose output is byte-identical to the CMake build (proven by
Meta/bazel_parity_harness.py). Absolute source paths become package-relative
$(location ...) refs; output paths (CMake's *.tmp) become genrule outs.

Usage: emit_codegen_bazel.py <LibDir e.g. Libraries/LibWeb>  > codegen.bzl
"""
import re, os, sys, shlex

ROOT = "/home/ubuntu/ladybird-work"
FULL = ROOT + "/Build/full"

def parse(lib_build_dir):
    txt = open(FULL + "/build.ninja").read()
    rules = []
    for b in re.split(r'\nbuild ', txt):
        if ': CUSTOM_COMMAND' not in b:
            continue
        m = re.search(r'\n  COMMAND = (.*)', b)
        if not m or 'Meta/Generators/' not in m.group(1):
            continue
        cmd = m.group(1)
        cd = re.match(r'\s*cd (\S+) &&', cmd).group(1)
        if cd != lib_build_dir:
            continue
        py = next((s for s in cmd.split(' && ')
                   if 'python3' in s and 'Generators/' in s), None)
        if not py:
            continue
        rules.append(py.strip())
    return rules

def convert(py, pkg_src_dir):
    """py: the 'python3 .../script.py <args>' segment. Returns (name, dict)."""
    script = re.search(r'Generators/(\S+\.py)', py).group(1)
    tail = shlex.split(py.split(script, 1)[1])
    outs, srcs, argv = [], [], []
    i = 0
    while i < len(tail):
        t = tail[i]
        if t.endswith('.tmp'):
            o = t[:-4]
            outs.append(o)
            argv.append('$(location %s)' % o)
        elif t.startswith(pkg_src_dir + '/'):
            rel = os.path.relpath(t, pkg_src_dir)
            srcs.append(rel)
            argv.append('$(location %s)' % rel)
        elif t.startswith(ROOT + '/'):
            # repo source outside this package -> keep absolute-relative label form
            rel = os.path.relpath(t, ROOT)
            srcs.append('//%s' % os.path.dirname(rel) + ':' + os.path.basename(rel)
                        if False else rel)
            argv.append('$(location //:%s)' % rel if False else rel)
        else:
            argv.append(shlex.quote(t) if ' ' in t else t)
        i += 1
    base = os.path.splitext(os.path.basename(outs[0]))[0] if outs else script
    name = 'gen_' + re.sub(r'[^A-Za-z0-9]', '_', base)
    return name, dict(script=script, outs=outs, srcs=srcs, args=' '.join(argv))

def main():
    lib = sys.argv[1]                       # e.g. Libraries/LibWeb
    lib_build = FULL + '/' + lib
    pkg_src = ROOT + '/' + lib
    rules = parse(lib_build)
    print('# AUTO-GENERATED by Meta/emit_codegen_bazel.py — do not edit.')
    print('# %d Python-generator genrules for %s (byte-parity: Meta/bazel_parity_harness.py)\n' % (len(rules), lib))
    print('def %s_codegen():' % lib.split('/')[-1].lower())
    seen = set()
    for py in rules:
        if 'generate_libweb_bindings.py' in py:
            continue  # mega-rule handled separately
        name, d = convert(py, pkg_src)
        if name in seen:
            continue
        seen.add(name)
        print('    native.genrule(')
        print('        name = %r,' % name)
        print('        srcs = %r + ["//Meta:generators"],' % d['srcs'])
        print('        outs = %r,' % d['outs'])
        print('        cmd = "python3 Meta/Generators/%s %s",' % (d['script'], d['args']))
        print('    )')

if __name__ == '__main__':
    main()
