name: "main"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  copyright-headers-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      ARCH: "x64"
      OS: "linux"

    steps:
      - uses: actions/checkout@v4

      - name: Check copyright headers
        if: success()
        run: |
          bazel run //infra/internal/check_copyright_headers
